//! `conformance/REPORT.md`: a layer × file matrix of ledger statuses.
//! Deterministic (no timestamps), so regenerating it only changes it when the
//! ledger or the suite changed.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use crate::check::{Violation, stale_index_hints};
use crate::harness::Results;
use crate::ledger::{Cell, Ledger};
use crate::matrix::{Column, HARNESSED, Phase};
use crate::suite::Suite;

/// Status columns of the report, in order.
const STATUSES: [&str; 5] = ["pass", "xfail", "degraded", "skip", "n/a"];

#[derive(Default, Clone, Copy)]
struct Counts([usize; 5]);

impl Counts {
    fn add(&mut self, cell: &Cell) {
        let i = STATUSES
            .iter()
            .position(|s| *s == cell.status())
            .unwrap_or(0);
        self.0[i] += 1;
    }

    fn render(self) -> String {
        let parts: Vec<String> = STATUSES
            .iter()
            .zip(self.0)
            .filter(|(_, n)| *n > 0)
            .map(|(s, n)| format!("{n} {s}"))
            .collect();
        if parts.is_empty() {
            "—".to_owned()
        } else {
            parts.join(", ")
        }
    }
}

/// Renders REPORT.md. `upstream` names the vendored suite (e.g. its PIN
/// commit); `results` are the layer harnesses' runs, when they ran.
pub fn render(
    suite: &Suite,
    ledger: &Ledger,
    violations: &[Violation],
    upstream: Option<&str>,
    results: Option<&Results>,
) -> String {
    let mut by_file: BTreeMap<&str, BTreeMap<Column, Counts>> = BTreeMap::new();
    let mut totals: BTreeMap<Column, Counts> = BTreeMap::new();
    let mut open: BTreeMap<Phase, BTreeMap<Column, usize>> = BTreeMap::new();
    for e in &ledger.entries {
        for (col, cell) in &e.cells {
            by_file
                .entry(e.key.file.as_str())
                .or_default()
                .entry(*col)
                .or_default()
                .add(cell);
            totals.entry(*col).or_default().add(cell);
            if let Cell::Xfail { until, .. } = cell {
                *open.entry(*until).or_default().entry(*col).or_default() += 1;
            }
        }
    }

    let mut out = String::new();
    out.push_str("# Conformance report\n\n");
    out.push_str(
        "Generated by `cargo xtask conformance-report` from `conformance/ledger.toml` and the \
         vendored WG suite (`third_party/message-format-wg/test/tests`). Do not edit by hand; \
         see `plans/01-conformance.md` §3–§4.\n\n",
    );
    let _ = writeln!(out, "* Current phase: **{}**", ledger.current_phase);
    if let Some(u) = upstream {
        let _ = writeln!(out, "* Suite: {u}");
    }
    let _ = writeln!(
        out,
        "* Tests: {} in {} files; ledger entries: {}",
        suite.tests().len(),
        suite.files().len(),
        ledger.entries.len()
    );
    let harnessed: Vec<&str> = HARNESSED.iter().map(|c| c.as_str()).collect();
    let _ = writeln!(
        out,
        "* Layers with a harness: {}",
        if harnessed.is_empty() {
            "none yet".to_owned()
        } else {
            harnessed.join(", ")
        }
    );
    if let Some(results) = results {
        let runs: Vec<String> = HARNESSED
            .iter()
            .map(|c| {
                let (passed, run) = results.tally(*c);
                format!("{c} {passed}/{run}")
            })
            .collect();
        let _ = writeln!(
            out,
            "* Harness runs (pass / applicable): {}",
            runs.join(", ")
        );
    }
    let _ = writeln!(
        out,
        "* Harness: **{}**\n",
        if violations.is_empty() {
            "green".to_owned()
        } else {
            format!("red — {} violation(s), listed below", violations.len())
        }
    );

    out.push_str("## Totals per layer\n\n");
    out.push_str(
        "| Layer | pass | xfail | degraded | skip | n/a |\n|---|---:|---:|---:|---:|---:|\n",
    );
    for col in Column::ALL {
        let c = totals.get(&col).copied().unwrap_or_default();
        let _ = writeln!(
            out,
            "| {col} | {} | {} | {} | {} | {} |",
            c.0[0], c.0[1], c.0[2], c.0[3], c.0[4]
        );
    }

    out.push_str(
        "\n## Layer × file\n\nL1–L6 run with all features on; L4d/L5d/L6d are the \
         default-features configuration. Each cell lists the non-zero status counts.\n\n",
    );
    out.push_str("| File | Tests |");
    for col in Column::ALL {
        let _ = write!(out, " {col} |");
    }
    out.push_str("\n|---|---:|");
    for _ in Column::ALL {
        out.push_str("---|");
    }
    out.push('\n');
    for (file, n) in suite.files() {
        let _ = write!(out, "| `{file}` | {n} |");
        let row = by_file.get(file.as_str());
        for col in Column::ALL {
            let c = row.and_then(|r| r.get(&col)).copied().unwrap_or_default();
            let _ = write!(out, " {} |", c.render());
        }
        out.push('\n');
    }
    let _ = write!(out, "| **all** | {} |", suite.tests().len());
    for col in Column::ALL {
        let c = totals.get(&col).copied().unwrap_or_default();
        let _ = write!(out, " {} |", c.render());
    }
    out.push('\n');

    out.push_str("\n## Open xfails by target phase\n\n| until |");
    for col in Column::ALL {
        let _ = write!(out, " {col} |");
    }
    out.push_str(" total |\n|---|");
    for _ in Column::ALL {
        out.push_str("---:|");
    }
    out.push_str("---:|\n");
    for (phase, cols) in &open {
        let _ = write!(out, "| {phase} |");
        for col in Column::ALL {
            let _ = write!(out, " {} |", cols.get(&col).copied().unwrap_or(0));
        }
        let _ = writeln!(out, " {} |", cols.values().sum::<usize>());
    }

    if !ledger.notes.is_empty() {
        out.push_str("\n## Notes\n\n");
        for n in &ledger.notes {
            let until = n.until.map(|u| format!(" until {u}")).unwrap_or_default();
            let _ = writeln!(out, "* `{}` — {}{until}: {}", n.id, n.status, n.reason);
        }
    }

    if !violations.is_empty() {
        out.push_str("\n## Violations\n\n");
        for v in violations {
            let _ = writeln!(out, "* {v}");
        }
    }

    let stale = stale_index_hints(suite, ledger);
    if !stale.is_empty() {
        out.push_str("\n## Stale index hints (not a failure)\n\n");
        for (key, was, is) in stale {
            let _ = writeln!(out, "* {key}: ledger says #{was}, suite has #{is}");
        }
    }
    out
}
