//! A stand-in for `mf2-build`'s 2.0 entry point (Phase 10 A2 probe):
//! `mf2_build::run()` is the whole build script, and it learns `mf2`'s
//! features from `links` metadata instead of from the including crate's own
//! `CARGO_FEATURE_*`.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::io::Write as _;
use std::path::PathBuf;

/// The whole build script of a crate that includes the generated module.
///
/// # Panics
///
/// Without `OUT_DIR`, which cargo always sets for a build script.
pub fn run() {
    let out = PathBuf::from(env::var_os("OUT_DIR").expect("cargo sets OUT_DIR"));
    let pkg = env::var("CARGO_PKG_NAME").unwrap_or_default();
    let target = env::var("TARGET").unwrap_or_default();

    // 2.0: `mf2`'s features, from its `links` metadata; else (a 1.x-shaped
    // crate that forwards features) this crate's own.
    let (source, features) = match env::var("DEP_MF2_V2_FEATURES") {
        Ok(value) => ("links", value),
        Err(_) => ("own CARGO_FEATURE_*", own_features()),
    };
    let dep_target = env::var("DEP_MF2_V2_TARGET").unwrap_or_else(|_| "(unset)".to_owned());
    let mut dep_vars: Vec<String> = env::vars()
        .filter(|(key, _)| key.starts_with("DEP_"))
        .map(|(key, value)| format!("{key}={value}"))
        .collect();
    dep_vars.sort();

    // What was seen, for the record: a warning (cargo shows those of path
    // packages) and, when asked, a line in a log file.
    println!(
        "cargo::warning={pkg} [{target}] via {source}: features=[{features}] mf2-target={dep_target} vars={}",
        dep_vars.join(" ")
    );
    if let Some(log) = env::var_os("P10_RUN_LOG") {
        if let Ok(mut file) = fs::OpenOptions::new().create(true).append(true).open(log) {
            let _ = writeln!(
                file,
                "{pkg}\t{target}\t{source}\t[{features}]\t{}",
                out.display()
            );
        }
    }

    let set: Vec<&str> = features.split(',').filter(|f| !f.is_empty()).collect();
    let module = generate(&set, source, &features, &dep_target, &dep_vars.join(" "));
    let path = out.join("mf2_generated.rs");
    // Written only when its bytes differ, as the real build does.
    if fs::read_to_string(&path).ok().as_deref() != Some(module.as_str()) {
        fs::write(&path, module).expect("OUT_DIR is writable");
    }
    // The sources the real build reads; nothing about features — a feature
    // change reaches this script as a new unit of `mf2`, if at all.
    println!("cargo::rerun-if-changed=locales");
}

fn own_features() -> String {
    let mut own: Vec<String> = env::vars()
        .filter_map(|(key, _)| {
            key.strip_prefix("CARGO_FEATURE_")
                .map(|f| f.to_ascii_lowercase().replace('_', "-"))
        })
        .filter(|f| f != "default")
        .collect();
    own.sort();
    own.join(",")
}

fn generate(
    set: &[&str],
    source: &str,
    features: &str,
    dep_target: &str,
    dep_vars: &str,
) -> String {
    let mut s = String::from("// @generated by the A2 probe's stand-in mf2-build.\n");
    let _ = writeln!(s, "/// What the build script saw, and where from.");
    let _ = writeln!(s, "pub const BUILD_SAW: &str = {features:?};");
    let _ = writeln!(s, "/// `links` or the including crate's own features.");
    let _ = writeln!(s, "pub const BUILD_SAW_SOURCE: &str = {source:?};");
    let _ = writeln!(
        s,
        "/// The `TARGET` of the `mf2` instance whose metadata arrived."
    );
    let _ = writeln!(s, "pub const BUILD_SAW_MF2_TARGET: &str = {dep_target:?};");
    let _ = writeln!(s, "/// Every `DEP_*` variable the script was given.");
    let _ = writeln!(s, "pub const BUILD_SAW_DEP_VARS: &str = {dep_vars:?};");
    // A choice made by the build script from the metadata.
    let _ = writeln!(
        s,
        "/// Decided by the build script.\npub const BUILD_DECIDED_SSR: bool = {};",
        set.contains(&"ssr")
    );
    let _ = writeln!(
        s,
        "/// Decided by the build script: what to emit.\npub const BUILD_DECIDED_EMIT: &str = {:?};",
        if set.contains(&"native") {
            "native"
        } else if set.contains(&"ssr") {
            "web server"
        } else if set.contains(&"hydrate") || set.contains(&"csr") {
            "web client"
        } else {
            "none"
        }
    );
    // Items that exist only when the build script decided so: an editor
    // resolves them only if its own run of this script saw the metadata.
    if set.contains(&"ssr") {
        s.push_str("/// Emitted by the build script because it saw `ssr`.\npub const EMITTED_FOR_SSR: bool = true;\n");
    }
    if set.contains(&"native") {
        s.push_str("/// Emitted by the build script because it saw `native`.\npub const EMITTED_FOR_NATIVE: bool = true;\n");
    }
    // Choices made at compile time by `mf2`'s cfg-forwarding macros: the
    // same text in every build.
    s.push_str(
        r#"
::mf2::__if_ssr! {
    /// Decided by `mf2`'s own `cfg(feature = "ssr")`.
    pub const MACRO_SAW_SSR: bool = true;
    /// The catalogs, embedded for the server only.
    pub static CATALOGS: &[(&str, &[u8])] = &[("en", b"catalog bytes")];
}
::mf2::__if_not_ssr! {
    /// Decided by `mf2`'s own `cfg(feature = "ssr")`.
    pub const MACRO_SAW_SSR: bool = false;
}
::mf2::__if_hydrate! {
    /// Present only in a `hydrate` build of `mf2`.
    pub const MACRO_SAW_HYDRATE: bool = true;
}

/// The host, picked by `mf2`'s features.
pub mod host {
    ::mf2::__use_host!(HOST);
}

/// One line comparing the build script's view with the compiled one.
// Which of these fire depends on the mode: a statement-level choice through
// a cfg-forwarding macro is linted differently in each build.
#[allow(unused_mut, unused_assignments)]
pub fn report() -> String {
    let mut hydrate = false;
    ::mf2::__if_hydrate! { hydrate = MACRO_SAW_HYDRATE; }
    let catalogs = {
        let mut n = 0;
        ::mf2::__if_ssr! { n = CATALOGS.len(); }
        n
    };
    format!(
        "build saw [{}] via {} (mf2 TARGET {}); mf2 compiled with [{}]; build decided ssr={} emit={}; macros chose ssr={} hydrate={} catalogs={} host={}",
        BUILD_SAW,
        BUILD_SAW_SOURCE,
        BUILD_SAW_MF2_TARGET,
        ::mf2::compiled_features(),
        BUILD_DECIDED_SSR,
        BUILD_DECIDED_EMIT,
        MACRO_SAW_SSR,
        hydrate,
        catalogs,
        host::HOST,
    )
}
"#,
    );
    s
}
