#!/usr/bin/env python3
"""P0.1: write per-shape variant templates (data only) for workload-gen.

A variant `<impl>--<shape>` renders every site of one shape with the
implementation under test (`tr` or `closure`) and every other site with the
`idlit` baseline literal (the site's MsgId as a short literal);
`<impl>--<shape>--none` does so only for the shape's sites without arguments
(modes none/rich), the shape's argument sites stay `idlit`.
Per-shape cost = (variant - idlit) / sites of that shape; fixed library cost
cancels in the M-delta between two scales (RESULT.md, "Method").

Usage: variants.py <out-dir> <closure-template-dir>
Writes <out-dir>/<variant>/template.toml (+ support.rs).
"""
import os
import sys
import tomllib

PROBE = os.path.realpath(os.path.join(os.path.dirname(__file__), ".."))
SHAPES = ["string", "child", "attr", "text_prop", "signal_prop", "string_prop", "deferred", "if_else"]
MODES = ["none", "rich", "plain", "signal", "get"]
CHAIN = {  # workload-gen's snippet fallbacks (bench/workload-gen/README.md)
    "none": ["none"],
    "rich": ["rich", "none"],
    "plain": ["plain", "none"],
    "get": ["get", "plain", "none"],
    "signal": ["signal", "get", "plain", "none"],
}


def load(d):
    with open(os.path.join(d, "template.toml"), "rb") as f:
        t = tomllib.load(f)
    t["_dir"] = os.path.realpath(d)
    sup = t.get("support")
    t["_support"] = open(os.path.join(d, sup)).read() if sup else ""
    return t


def table(t, shape):
    s = t.get("site", {})
    if shape in s:
        return s[shape]
    if shape in ("text_prop", "signal_prop"):
        return s.get("reactive_prop", {})
    return {}


def resolved(t, shape):
    tab = table(t, shape)
    out = {}
    for m in MODES:
        for k in CHAIN[m]:
            if k in tab:
                out[m] = tab[k]
                break
    return out


def q(s):
    """TOML basic string."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def write(out, name, impl, dummy, shape, only_none):
    lines = [
        f"# Generated by scripts/variants.py: {impl['name']} on [site.{shape}]"
        + (" (argument-free modes only)" if only_none else "")
        + ", idlit literal everywhere else.",
        f"name = {q(name)}",
        f"description = {q('P0.1 variant ' + name)}",
    ]
    deps = [d.replace("{{template_dir}}", impl["_dir"]) for d in impl.get("dependencies", [])]
    lines.append("dependencies = [" + ", ".join(q(d) for d in deps) + "]")
    lines.append(f"prelude = {q(impl.get('prelude', ''))}")
    if impl["_support"]:
        lines.append('support = "support.rs"')
    lines.append(f"boot = {q(impl.get('boot', ''))}")
    if "args" in impl:
        lines.append("\n[args]")
        for k, v in impl["args"].items():
            lines.append(f"{k} = {q(v)}")
    dfr = impl["deferred"] if shape == "deferred" else dummy["deferred"]
    lines.append("\n[deferred]")
    for k in ("type", "view", "string"):
        lines.append(f"{k} = {q(dfr[k])}")
    for s in SHAPES:
        d = resolved(dummy, s)
        if s == shape:
            i = resolved(impl, s)
            snip = {m: (i[m] if (not only_none or m in ("none", "rich")) else d[m]) for m in MODES}
        else:
            snip = d
        lines.append(f"\n[site.{s}]")
        for m in MODES:
            lines.append(f"{m} = {q(snip[m])}")
    d = os.path.join(out, name)
    os.makedirs(d, exist_ok=True)
    with open(os.path.join(d, "template.toml"), "w") as f:
        f.write("\n".join(lines) + "\n")
    if impl["_support"]:
        with open(os.path.join(d, "support.rs"), "w") as f:
            f.write(impl["_support"])


def main():
    out, closure_dir = sys.argv[1], sys.argv[2]
    dummy = load(os.path.join(PROBE, "templates", "idlit"))
    impls = {"tr": load(os.path.join(PROBE, "templates", "tr")), "closure": load(closure_dir)}
    names = []
    for key, impl in impls.items():
        for s in SHAPES:
            short = s.replace("_", "")
            write(out, f"{key}--{short}", impl, dummy, s, False)
            names.append(f"{key}--{short}")
            if s != "deferred":
                write(out, f"{key}--{short}--none", impl, dummy, s, True)
                names.append(f"{key}--{short}--none")
    print("\n".join(names))


if __name__ == "__main__":
    main()
