//! Component C000 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::__mf2::{tr, tr_args, ArgValue, MsgId};

fn s000_2(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(164)).to_string(),
        1 => tr(MsgId(524)).to_string(),
        _ => tr(MsgId(1263)).to_string(),
    }
}

fn s000_3(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(1291)).to_string()
}

fn s000_6(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(685)).to_string(),
        1 => tr(MsgId(1204)).to_string(),
        _ => tr(MsgId(434)).to_string(),
    }
}

fn s000_8(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(814)).to_string()
}

fn s000_9(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(1213)).to_string()
}

#[component]
pub fn C000() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{tr_args(MsgId(83), [ArgValue::from(who)])}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr_args(MsgId(134), [ArgValue::from(who)]).to_string(), 1 => tr_args(MsgId(967), [ArgValue::from(n)]).to_string(), _ => tr_args(MsgId(950), [ArgValue::from(n), ArgValue::from(who)]).to_string(), });
                }>{tr(MsgId(253))}</button>
                <p>{move || if flag.get() { tr_args(MsgId(196), [ArgValue::from(n)]) } else { tr_args(MsgId(246), [ArgValue::from(who)]) }}</p>
                <p>{move || tr_args(MsgId(1099), [ArgValue::from(name), ArgValue::from(name)])}</p>
                <p>{move || tr_args(MsgId(779), [ArgValue::from(name.get())])}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr_args(MsgId(1105), [ArgValue::from(n), ArgValue::from(n)]).to_string());
                }>{tr(MsgId(1512))}</button>
                <p>{tr(MsgId(473))}</p>
                <StringBadge text={tr(MsgId(442))}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{move || s000_2(count.get(), who, when)}</p>
                <StringBadge text={tr(MsgId(1283))}/>
                <p>{tr(MsgId(1274))}</p>
                <ul class="table" title={crate::tables::T000[0].label.to_string()}>
                    {crate::tables::T000.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <p>{s000_3(n, who, when)}</p>
                <SignalHint text={tr(MsgId(547))}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr(MsgId(188)).to_string());
                }>{tr(MsgId(308))}</button>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr(MsgId(1436)).to_string());
                }>{tr(MsgId(1078))}</button>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{move || s000_6(count.get(), who, when)}</p>
                <TextLabel text={tr(MsgId(606))}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr(MsgId(66)).to_string());
                }>{tr(MsgId(575))}</button>
                <p>{s000_8(n, who, when)}</p>
                <p>{s000_9(n, who, when)}</p>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 0">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
