//! Component C001 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::__mf2::{tr, tr_args, ArgValue, MsgId};

fn s001_0(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr_args(MsgId(1061), [ArgValue::from(n)]).to_string(),
        1 => tr_args(MsgId(957), [ArgValue::from(who)]).to_string(),
        _ => tr_args(MsgId(231), [ArgValue::from(who)]).to_string(),
    }
}

fn s001_3(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(680)).to_string()
}

fn s001_4(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(70)).to_string(),
        1 => tr(MsgId(824)).to_string(),
        _ => tr(MsgId(46)).to_string(),
    }
}

fn s001_5(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(939)).to_string()
}

fn s001_7(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(1597)).to_string(),
        1 => tr(MsgId(24)).to_string(),
        _ => tr(MsgId(1412)).to_string(),
    }
}

#[component]
pub fn C001() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <TextLabel text={tr_args(MsgId(672), [ArgValue::from(who), ArgValue::from(n), ArgValue::from(who)])}/>
                <p>{move || s001_0(count.get(), who, when)}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr_args(MsgId(698), [ArgValue::from(who), ArgValue::from(who)]).to_string());
                }>"Apply"</button>
                <StringBadge text={tr_args(MsgId(1374), [ArgValue::from(who)])}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr_args(MsgId(648), [ArgValue::from(n)]).to_string(), _ => tr(MsgId(1469)).to_string(), });
                }>"Apply"</button>
                <p>{move || tr_args(MsgId(370), [ArgValue::from(name)])}</p>
                <StringBadge text={tr(MsgId(716))}/>
                <p>{s001_3(n, who, when)}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{move || s001_4(count.get(), who, when)}</p>
                <input type="text" aria-label={tr(MsgId(90))} placeholder={tr(MsgId(1589))}/>
                <ul class="table" title={crate::tables::T001[0].label.to_string()}>
                    {crate::tables::T001.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <p>{move || if flag.get() { tr(MsgId(973)) } else { tr(MsgId(417)) }}</p>
                <StringBadge text={tr(MsgId(1327))}/>
                <SignalHint text={tr(MsgId(316))}/>
                <input type="text" aria-label={tr(MsgId(1438))} placeholder={tr(MsgId(375))}/>
                <SignalHint text={tr(MsgId(1402))}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{s001_5(n, who, when)}</p>
                <SignalHint text={tr(MsgId(1488))}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr(MsgId(1127)).to_string(), _ => tr(MsgId(548)).to_string(), });
                }>"Apply"</button>
                <SignalHint text={tr(MsgId(693))}/>
                <p>{move || s001_7(count.get(), who, when)}</p>
                <input type="text" aria-label={tr(MsgId(1220))}/>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 1">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
