//! Component C003 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::__mf2::{tr, tr_args, ArgValue, MsgId};

fn s003_1(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr_args(MsgId(1020), [ArgValue::from(n), ArgValue::from(n)]).to_string(),
        1 => tr_args(MsgId(1031), [ArgValue::from(who)]).to_string(),
        _ => tr(MsgId(1181)).to_string(),
    }
}

fn s003_2(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(505)).to_string(),
        1 => tr(MsgId(1142)).to_string(),
        _ => tr(MsgId(443)).to_string(),
    }
}

fn s003_4(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(597)).to_string(),
        1 => tr(MsgId(1059)).to_string(),
        _ => tr(MsgId(45)).to_string(),
    }
}

fn s003_7(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(2) {
        0 => tr(MsgId(1091)).to_string(),
        _ => tr(MsgId(1521)).to_string(),
    }
}

#[component]
pub fn C003() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <input type="text" aria-label={move || tr_args(MsgId(30), [ArgValue::from(name), ArgValue::from(name)])}/>
                <p>{tr_args(MsgId(1143), [ArgValue::from(who)])}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr_args(MsgId(382), [ArgValue::from(who)]).to_string(), 1 => tr_args(MsgId(1498), [ArgValue::from(who)]).to_string(), _ => tr_args(MsgId(292), [ArgValue::from(who)]).to_string(), });
                }>{tr(MsgId(1382))}</button>
                <p>{move || s003_1(count.get(), who, when)}</p>
                <ul class="table" title={crate::tables::T003[0].label.to_string()}>
                    {crate::tables::T003.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <p>{tr(MsgId(785))}</p>
                <p>{move || s003_2(count.get(), who, when)}</p>
                <TextLabel text={tr(MsgId(1415))}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr(MsgId(1130))}</p>
                <TextLabel text={tr(MsgId(41))}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr(MsgId(1576)).to_string(), _ => tr(MsgId(1272)).to_string(), });
                }>{tr(MsgId(88))}</button>
                <SignalHint text={tr(MsgId(744))}/>
                <p>{move || s003_4(count.get(), who, when)}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr(MsgId(29)).to_string());
                }>{tr(MsgId(1168))}</button>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr(MsgId(1280)).to_string(), 1 => tr(MsgId(458)).to_string(), _ => tr(MsgId(1281)).to_string(), });
                }>"Apply"</button>
                <p>{move || s003_7(count.get(), who, when)}</p>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 3">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
