//! Component C007 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::__mf2::{tr, tr_args, ArgValue, MsgId};

fn s007_0(n: i64, who: &'static str, when: &'static str) -> String {
    tr_args(MsgId(1457), [ArgValue::from(n), ArgValue::from(who)]).to_string()
}

fn s007_1(n: i64, who: &'static str, when: &'static str) -> String {
    tr_args(MsgId(752), [ArgValue::from(who), ArgValue::from(n)]).to_string()
}

fn s007_2(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr_args(MsgId(1060), [ArgValue::from(who), ArgValue::from(who)]).to_string(),
        1 => tr_args(MsgId(1437), [ArgValue::from(who)]).to_string(),
        _ => tr(MsgId(722)).to_string(),
    }
}

fn s007_4(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(425)).to_string()
}

fn s007_6(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(621)).to_string(),
        1 => tr(MsgId(886)).to_string(),
        _ => tr(MsgId(243)).to_string(),
    }
}

fn s007_7(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(445)).to_string()
}

fn s007_9(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(767)).to_string()
}

#[component]
pub fn C007() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{s007_0(n, who, when)}</p>
                <p>{s007_1(n, who, when)}</p>
                <p>{move || s007_2(count.get(), who, when)}</p>
                <p>{tr_args(MsgId(1140), [ArgValue::from(n), ArgValue::from(who), ArgValue::from(who)])}</p>
                <input type="text" aria-label={tr_args(MsgId(488), [ArgValue::from(who), ArgValue::from(who), ArgValue::from(who)])}/>
                <p>{move || tr_args(MsgId(838), [ArgValue::from(count.get()), ArgValue::from(name.get()), ArgValue::from(name.get())])}</p>
                <p>{move || if flag.get() { tr_args(MsgId(1128), [ArgValue::from(who), ArgValue::from(who)]) } else { tr_args(MsgId(1051), [ArgValue::from(n)]) }}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr(MsgId(1511)).to_string(), _ => tr(MsgId(431)).to_string(), });
                }>{tr(MsgId(1338))}</button>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr(MsgId(1193))}</p>
                <ul class="table" title={crate::tables::T007[0].label.to_string()}>
                    {crate::tables::T007.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <p>{s007_4(n, who, when)}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr(MsgId(516)).to_string(), _ => tr(MsgId(718)).to_string(), });
                }>{tr(MsgId(572))}</button>
                <StringBadge text={tr(MsgId(1200))}/>
                <StringBadge text={tr(MsgId(870))}/>
                <p>{move || s007_6(count.get(), who, when)}</p>
                <p>{s007_7(n, who, when)}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{move || if flag.get() { tr(MsgId(449)) } else { tr(MsgId(69)) }}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr(MsgId(642)).to_string(), _ => tr(MsgId(1484)).to_string(), });
                }>"Apply"</button>
                <TextLabel text={tr(MsgId(1452))}/>
                <TextLabel text={tr(MsgId(276))}/>
                <SignalHint text={tr(MsgId(1205))}/>
                <p>{s007_9(n, who, when)}</p>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 7">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
