//! Component C009 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::__mf2::{tr, tr_args, ArgValue, MsgId};

fn s009_1(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr_args(MsgId(1396), [ArgValue::from(who), ArgValue::from(n), ArgValue::from(n)]).to_string(),
        1 => tr_args(MsgId(1432), [ArgValue::from(who)]).to_string(),
        _ => tr_args(MsgId(846), [ArgValue::from(who)]).to_string(),
    }
}

fn s009_2(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr_args(MsgId(428), [ArgValue::from(who)]).to_string(),
        1 => tr(MsgId(1441)).to_string(),
        _ => tr(MsgId(97)).to_string(),
    }
}

fn s009_3(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(723)).to_string()
}

fn s009_5(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(640)).to_string(),
        1 => tr(MsgId(444)).to_string(),
        _ => tr(MsgId(1038)).to_string(),
    }
}

fn s009_7(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(1057)).to_string()
}

fn s009_8(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(808)).to_string()
}

#[component]
pub fn C009() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{tr_args(MsgId(419), [ArgValue::from(who)])}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr_args(MsgId(1105), [ArgValue::from(n), ArgValue::from(n)]).to_string(), _ => tr_args(MsgId(620), [ArgValue::from(n)]).to_string(), });
                }>{tr(MsgId(185))}</button>
                <p>{move || s009_1(count.get(), who, when)}</p>
                <SignalHint text={tr_args(MsgId(1509), [ArgValue::from(n)])}/>
                <p>{move || s009_2(count.get(), who, when)}</p>
                <TextLabel text={tr(MsgId(1201))}/>
                <p>{tr(MsgId(364))}</p>
                <input type="text" aria-label={tr(MsgId(165))} placeholder={tr(MsgId(802))}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{s009_3(n, who, when)}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr(MsgId(87)).to_string(), _ => tr(MsgId(154)).to_string(), });
                }>{tr(MsgId(153))}</button>
                <p>{move || s009_5(count.get(), who, when)}</p>
                <input type="text" aria-label={tr(MsgId(76))} placeholder={tr(MsgId(1264))}/>
                <SignalHint text={tr(MsgId(112))}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr(MsgId(1119)).to_string());
                }>"Apply"</button>
                <SignalHint text={tr(MsgId(1047))}/>
                <SignalHint text={tr(MsgId(970))}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <input type="text" aria-label={tr(MsgId(976))}/>
                <ul class="table" title={crate::tables::T009[0].label.to_string()}>
                    {crate::tables::T009.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <StringBadge text={tr(MsgId(182))}/>
                <p>{s009_7(n, who, when)}</p>
                <p>{s009_8(n, who, when)}</p>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 9">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
