//! Component C011 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::__mf2::{tr, tr_args, ArgValue, MsgId};

fn s011_1(n: i64, who: &'static str, when: &'static str) -> String {
    tr_args(MsgId(1418), [ArgValue::from(who)]).to_string()
}

fn s011_4(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(876)).to_string(),
        1 => tr(MsgId(414)).to_string(),
        _ => tr(MsgId(775)).to_string(),
    }
}

fn s011_5(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(342)).to_string(),
        1 => tr(MsgId(990)).to_string(),
        _ => tr(MsgId(403)).to_string(),
    }
}

#[component]
pub fn C011() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <ul class="table" title={crate::tables::T011[0].label.to_string()}>
                    {crate::tables::T011.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <p>{move || tr_args(MsgId(586), [ArgValue::from(name.get())])}</p>
                <p>{move || tr_args(MsgId(875), [ArgValue::from(name)])}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr_args(MsgId(1160), [ArgValue::from(n), ArgValue::from(who)]).to_string(), _ => tr_args(MsgId(1473), [ArgValue::from(n)]).to_string(), });
                }>{tr(MsgId(442))}</button>
                <p>{s011_1(n, who, when)}</p>
                <SignalHint text={Signal::derive(move || tr_args(MsgId(28), [ArgValue::from(name.get())]).to_string())}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr_args(MsgId(453), [ArgValue::from(who), ArgValue::from(who)]).to_string());
                }>{tr(MsgId(1017))}</button>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr(MsgId(1195)).to_string(), _ => tr(MsgId(1410)).to_string(), });
                }>{tr(MsgId(978))}</button>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr(MsgId(920))}</p>
                <p>{move || if flag.get() { tr(MsgId(1413)) } else { tr(MsgId(725)) }}</p>
                <p>{tr(MsgId(365))}</p>
                <p>{tr(MsgId(1445))}</p>
                <p>{tr(MsgId(1563))}</p>
                <p>{tr(MsgId(974))}</p>
                <p>{move || s011_4(count.get(), who, when)}</p>
                <input type="text" aria-label={tr(MsgId(26))} placeholder={tr(MsgId(125))}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr(MsgId(281))}</p>
                <p>{tr(MsgId(1174))}</p>
                <p>{move || s011_5(count.get(), who, when)}</p>
                <p>{tr(MsgId(1366))}</p>
                <StringBadge text={tr(MsgId(1165))}/>
                <StringBadge text={tr(MsgId(350))}/>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 11">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
