//! Component C012 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::__mf2::{tr, tr_args, ArgValue, MsgId};

fn s012_0(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr_args(MsgId(648), [ArgValue::from(n)]).to_string(),
        1 => tr_args(MsgId(771), [ArgValue::from(who), ArgValue::from(who)]).to_string(),
        _ => tr_args(MsgId(466), [ArgValue::from(n)]).to_string(),
    }
}

fn s012_1(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(742)).to_string()
}

fn s012_2(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(4)).to_string(),
        1 => tr(MsgId(436)).to_string(),
        _ => tr(MsgId(684)).to_string(),
    }
}

#[component]
pub fn C012() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{move || s012_0(count.get(), who, when)}</p>
                <p>{tr_args(MsgId(1523), [ArgValue::from(n)])}</p>
                <ul class="table" title={crate::tables::T012[0].label.to_string()}>
                    {crate::tables::T012.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <StringBadge text={tr_args(MsgId(110), [ArgValue::from(n)])}/>
                <input type="text" aria-label={tr_args(MsgId(1546), [ArgValue::from(who)])} placeholder={tr(MsgId(521))}/>
                <SignalHint text={tr_args(MsgId(753), [ArgValue::from(n)])}/>
                <p>{s012_1(n, who, when)}</p>
                <p>{move || if flag.get() { tr(MsgId(11)) } else { tr(MsgId(1370)) }}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{move || s012_2(count.get(), who, when)}</p>
                <TextLabel text={tr(MsgId(1043))}/>
                <p>{tr(MsgId(797))}</p>
                <StringBadge text={tr(MsgId(508))}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr(MsgId(787)).to_string(), 1 => tr(MsgId(780)).to_string(), _ => tr(MsgId(951)).to_string(), });
                }>{tr(MsgId(608))}</button>
                <p>{tr(MsgId(1530))}</p>
                <p>{tr(MsgId(701))}</p>
                <input type="text" aria-label={tr(MsgId(652))}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr(MsgId(1469)).to_string());
                }>{tr(MsgId(862))}</button>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr(MsgId(1121)).to_string());
                }>{tr(MsgId(1175))}</button>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 12">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
