//! Component C013 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::__mf2::{tr, tr_args, ArgValue, MsgId};

fn s013_1(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(1549)).to_string()
}

fn s013_5(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(848)).to_string()
}

#[component]
pub fn C013() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{move || tr_args(MsgId(0), [ArgValue::from(name.get())])}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr_args(MsgId(1504), [ArgValue::from(n)]).to_string(), _ => tr(MsgId(1299)).to_string(), });
                }>{tr(MsgId(15))}</button>
                <p>{move || tr_args(MsgId(1133), [ArgValue::from(name.get())])}</p>
                <StringBadge text={tr_args(MsgId(1389), [ArgValue::from(who)])}/>
                <StringBadge text={tr_args(MsgId(1400), [ArgValue::from(who)])}/>
                <StringBadge text={tr_args(MsgId(1480), [ArgValue::from(n)])}/>
                <p>{move || tr_args(MsgId(944), [ArgValue::from(count), ArgValue::from(name)])}</p>
                <p>{move || tr_args(MsgId(211), [ArgValue::from(name)])}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <ul class="table" title={crate::tables::T013[0].label.to_string()}>
                    {crate::tables::T013.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <p>{tr(MsgId(660))}</p>
                <p>{s013_1(n, who, when)}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr(MsgId(1562)).to_string(), 1 => tr(MsgId(367)).to_string(), _ => tr(MsgId(948)).to_string(), });
                }>{tr(MsgId(551))}</button>
                <TextLabel text={tr(MsgId(418))}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr(MsgId(784)).to_string(), 1 => tr(MsgId(1039)).to_string(), _ => tr(MsgId(806)).to_string(), });
                }>{tr(MsgId(237))}</button>
                <p>{move || if flag.get() { tr(MsgId(1004)) } else { tr(MsgId(1573)) }}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr(MsgId(397)).to_string(), 1 => tr(MsgId(832)).to_string(), _ => tr(MsgId(164)).to_string(), });
                }>{tr(MsgId(462))}</button>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{move || if flag.get() { tr(MsgId(871)) } else { tr(MsgId(391)) }}</p>
                <input type="text" aria-label={tr(MsgId(564))} placeholder={tr(MsgId(65))}/>
                <p>{s013_5(n, who, when)}</p>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 13">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
