//! Component C014 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::__mf2::{tr, tr_args, ArgValue, MsgId};

fn s014_0(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr_args(MsgId(1128), [ArgValue::from(who), ArgValue::from(who)]).to_string(),
        1 => tr_args(MsgId(587), [ArgValue::from(who), ArgValue::from(n)]).to_string(),
        _ => tr_args(MsgId(1368), [ArgValue::from(who), ArgValue::from(n)]).to_string(),
    }
}

fn s014_1(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(533)).to_string(),
        1 => tr(MsgId(1544)).to_string(),
        _ => tr(MsgId(1466)).to_string(),
    }
}

fn s014_4(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(822)).to_string()
}

fn s014_5(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(1094)).to_string()
}

fn s014_6(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(680)).to_string()
}

#[component]
pub fn C014() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{tr_args(MsgId(1031), [ArgValue::from(who)])}</p>
                <p>{move || s014_0(count.get(), who, when)}</p>
                <p>{move || if flag.get() { tr_args(MsgId(625), [ArgValue::from(who)]) } else { tr_args(MsgId(901), [ArgValue::from(who)]) }}</p>
                <p>{move || tr_args(MsgId(1179), [ArgValue::from(name), ArgValue::from(count)])}</p>
                <SignalHint text={Signal::derive(move || tr_args(MsgId(64), [ArgValue::from(count)]).to_string())}/>
                <p>{move || if flag.get() { tr_args(MsgId(671), [ArgValue::from(who), ArgValue::from(who)]) } else { tr_args(MsgId(659), [ArgValue::from(n)]) }}</p>
                <p>{move || s014_1(count.get(), who, when)}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr(MsgId(653)).to_string(), _ => tr(MsgId(731)).to_string(), });
                }>{tr(MsgId(1353))}</button>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr(MsgId(1525))}</p>
                <ul class="table" title={crate::tables::T014[0].label.to_string()}>
                    {crate::tables::T014.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <p>{tr(MsgId(269))}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr(MsgId(681)).to_string());
                }>{tr(MsgId(1123))}</button>
                <SignalHint text={tr(MsgId(471))}/>
                <p>{s014_4(n, who, when)}</p>
                <p>{tr(MsgId(1203))}</p>
                <input type="text" aria-label={tr(MsgId(331))} placeholder={tr(MsgId(495))}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr(MsgId(328))}</p>
                <p>{s014_5(n, who, when)}</p>
                <input type="text" aria-label={tr(MsgId(192))} placeholder={tr(MsgId(524))}/>
                <StringBadge text={tr(MsgId(261))}/>
                <p>{s014_6(n, who, when)}</p>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 14">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
