//! Component C015 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::__mf2::{tr, tr_args, ArgValue, MsgId};

fn s015_1(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr_args(MsgId(455), [ArgValue::from(n)]).to_string(),
        1 => tr_args(MsgId(1126), [ArgValue::from(who), ArgValue::from(n)]).to_string(),
        _ => tr(MsgId(929)).to_string(),
    }
}

fn s015_4(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(530)).to_string()
}

fn s015_7(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(1068)).to_string(),
        1 => tr(MsgId(1411)).to_string(),
        _ => tr(MsgId(70)).to_string(),
    }
}

#[component]
pub fn C015() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <StringBadge text={tr_args(MsgId(837), [ArgValue::from(who)])}/>
                <p>{move || tr_args(MsgId(1051), [ArgValue::from(count)])}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr_args(MsgId(361), [ArgValue::from(who)]).to_string(), _ => tr_args(MsgId(807), [ArgValue::from(n)]).to_string(), });
                }>{tr(MsgId(491))}</button>
                <p>{move || s015_1(count.get(), who, when)}</p>
                <TextLabel text={move || tr_args(MsgId(320), [ArgValue::from(count.get()), ArgValue::from(name.get())]).to_string()}/>
                <p>{move || tr_args(MsgId(1018), [ArgValue::from(name.get()), ArgValue::from(name.get())])}</p>
                <ul class="table" title={crate::tables::T015[0].label.to_string()}>
                    {crate::tables::T015.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr(MsgId(1025)).to_string(), 1 => tr(MsgId(14)).to_string(), _ => tr(MsgId(913)).to_string(), });
                }>{tr(MsgId(517))}</button>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr(MsgId(1265))}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr(MsgId(413)).to_string());
                }>{tr(MsgId(940))}</button>
                <p>{tr(MsgId(591))}</p>
                <p>{s015_4(n, who, when)}</p>
                <input type="text" aria-label={tr(MsgId(71))} placeholder={tr(MsgId(170))}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr(MsgId(1477)).to_string(), _ => tr(MsgId(1582)).to_string(), });
                }>"Apply"</button>
                <SignalHint text={tr(MsgId(949))}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr(MsgId(1343)).to_string(), _ => tr(MsgId(900)).to_string(), });
                }>"Apply"</button>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <SignalHint text={tr(MsgId(1569))}/>
                <p>{move || s015_7(count.get(), who, when)}</p>
                <SignalHint text={tr(MsgId(829))}/>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 15">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
