//! Component C016 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::__mf2::{tr, tr_args, ArgValue, MsgId};

fn s016_0(n: i64, who: &'static str, when: &'static str) -> String {
    tr_args(MsgId(55), [ArgValue::from(who)]).to_string()
}

fn s016_2(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr_args(MsgId(239), [ArgValue::from(who)]).to_string(),
        1 => tr_args(MsgId(664), [ArgValue::from(who), ArgValue::from(who), ArgValue::from(who)]).to_string(),
        _ => tr(MsgId(614)).to_string(),
    }
}

fn s016_3(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(1113)).to_string(),
        1 => tr(MsgId(702)).to_string(),
        _ => tr(MsgId(481)).to_string(),
    }
}

fn s016_4(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(1543)).to_string(),
        1 => tr(MsgId(1257)).to_string(),
        _ => tr(MsgId(1044)).to_string(),
    }
}

#[component]
pub fn C016() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{move || tr_args(MsgId(1434), [ArgValue::from(name)])}</p>
                <p>{s016_0(n, who, when)}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr_args(MsgId(1358), [ArgValue::from(who), ArgValue::from(who)]).to_string(), _ => tr_args(MsgId(649), [ArgValue::from(n)]).to_string(), });
                }>{tr(MsgId(1224))}</button>
                <p>{move || tr_args(MsgId(212), [ArgValue::from(name.get())])}</p>
                <p>{tr_args(MsgId(1028), [ArgValue::from(n)])}</p>
                <p>{move || s016_2(count.get(), who, when)}</p>
                <p>{tr(MsgId(536))}</p>
                <input type="text" aria-label={tr(MsgId(1369))}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <SignalHint text={tr(MsgId(390))}/>
                <p>{tr(MsgId(1271))}</p>
                <p>{move || s016_3(count.get(), who, when)}</p>
                <SignalHint text={tr(MsgId(356))}/>
                <p>{tr(MsgId(501))}</p>
                <SignalHint text={tr(MsgId(559))}/>
                <p>{move || s016_4(count.get(), who, when)}</p>
                <StringBadge text={tr(MsgId(1586))}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr(MsgId(1385))}</p>
                <p>{tr(MsgId(137))}</p>
                <p>{tr(MsgId(480))}</p>
                <p>{move || if flag.get() { tr(MsgId(123)) } else { tr(MsgId(429)) }}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr(MsgId(437)).to_string(), _ => tr(MsgId(206)).to_string(), });
                }>{tr(MsgId(329))}</button>
                <ul class="table" title={crate::tables::T016[0].label.to_string()}>
                    {crate::tables::T016.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 16">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
