//! Component C017 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::__mf2::{tr, tr_args, ArgValue, MsgId};

fn s017_0(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr_args(MsgId(204), [ArgValue::from(who)]).to_string(),
        1 => tr_args(MsgId(1104), [ArgValue::from(who)]).to_string(),
        _ => tr_args(MsgId(1187), [ArgValue::from(who)]).to_string(),
    }
}

fn s017_1(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(1310)).to_string()
}

fn s017_3(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(1223)).to_string(),
        1 => tr(MsgId(1328)).to_string(),
        _ => tr(MsgId(50)).to_string(),
    }
}

fn s017_4(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(228)).to_string(),
        1 => tr(MsgId(1016)).to_string(),
        _ => tr(MsgId(1092)).to_string(),
    }
}

fn s017_6(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(2) {
        0 => tr(MsgId(1495)).to_string(),
        _ => tr(MsgId(1142)).to_string(),
    }
}

#[component]
pub fn C017() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{move || s017_0(count.get(), who, when)}</p>
                <p>{move || tr_args(MsgId(428), [ArgValue::from(name.get())])}</p>
                <p>{tr_args(MsgId(1591), [ArgValue::from(who), ArgValue::from(n), ArgValue::from(who)])}</p>
                <input type="text" aria-label={move || tr_args(MsgId(1077), [ArgValue::from(name.get())])} placeholder={tr_args(MsgId(825), [ArgValue::from(who)])}/>
                <p>{move || tr_args(MsgId(994), [ArgValue::from(name.get())])}</p>
                <p>{move || if flag.get() { tr(MsgId(603)) } else { tr(MsgId(1229)) }}</p>
                <p>{tr(MsgId(772))}</p>
                <p>{s017_1(n, who, when)}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr(MsgId(1103)).to_string(), _ => tr(MsgId(348)).to_string(), });
                }>{tr(MsgId(344))}</button>
                <p>{tr(MsgId(307))}</p>
                <p>{tr(MsgId(174))}</p>
                <p>{tr(MsgId(997))}</p>
                <p>{move || s017_3(count.get(), who, when)}</p>
                <p>{move || s017_4(count.get(), who, when)}</p>
                <p>{move || if flag.get() { tr(MsgId(1440)) } else { tr(MsgId(609)) }}</p>
                <input type="text" aria-label={tr(MsgId(880))} placeholder={tr(MsgId(1420))}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr(MsgId(953)).to_string(), _ => tr(MsgId(933)).to_string(), });
                }>{tr(MsgId(667))}</button>
                <ul class="table" title={crate::tables::T017[0].label.to_string()}>
                    {crate::tables::T017.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <p>{move || s017_6(count.get(), who, when)}</p>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 17">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
