//! Component C018 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::__mf2::{tr, tr_args, ArgValue, MsgId};

fn s018_0(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr_args(MsgId(1502), [ArgValue::from(n)]).to_string(),
        1 => tr(MsgId(1367)).to_string(),
        _ => tr(MsgId(486)).to_string(),
    }
}

fn s018_1(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(1036)).to_string()
}

fn s018_2(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(1037)).to_string()
}

fn s018_4(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(459)).to_string(),
        1 => tr(MsgId(1075)).to_string(),
        _ => tr(MsgId(1545)).to_string(),
    }
}

fn s018_5(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(798)).to_string()
}

fn s018_6(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(1323)).to_string()
}

fn s018_7(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(722)).to_string(),
        1 => tr(MsgId(1215)).to_string(),
        _ => tr(MsgId(333)).to_string(),
    }
}

#[component]
pub fn C018() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{move || tr_args(MsgId(838), [ArgValue::from(count.get()), ArgValue::from(name.get()), ArgValue::from(name.get())])}</p>
                <p>{tr_args(MsgId(518), [ArgValue::from(n)])}</p>
                <input type="text" aria-label={move || tr_args(MsgId(44), [ArgValue::from(name)])} placeholder={tr(MsgId(119))}/>
                <p>{move || s018_0(count.get(), who, when)}</p>
                <ul class="table" title={crate::tables::T018[0].label.to_string()}>
                    {crate::tables::T018.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <p>{move || tr_args(MsgId(745), [ArgValue::from(count)])}</p>
                <p>{tr_args(MsgId(1241), [ArgValue::from(who)])}</p>
                <TextLabel text={move || tr_args(MsgId(919), [ArgValue::from(name)]).to_string()}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <StringBadge text={tr(MsgId(969))}/>
                <p>{s018_1(n, who, when)}</p>
                <p>{s018_2(n, who, when)}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr(MsgId(62)).to_string(), _ => tr(MsgId(314)).to_string(), });
                }>{tr(MsgId(1027))}</button>
                <p>{move || s018_4(count.get(), who, when)}</p>
                <TextLabel text={tr(MsgId(1073))}/>
                <TextLabel text={tr(MsgId(289))}/>
                <input type="text" aria-label={tr(MsgId(596))}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{s018_5(n, who, when)}</p>
                <p>{tr(MsgId(904))}</p>
                <p>{s018_6(n, who, when)}</p>
                <StringBadge text={tr(MsgId(1478))}/>
                <p>{tr(MsgId(738))}</p>
                <p>{move || s018_7(count.get(), who, when)}</p>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 18">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
