//! Component C019 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::__mf2::{tr, tr_args, ArgValue, MsgId};

fn s019_0(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr_args(MsgId(1405), [ArgValue::from(n)]).to_string(),
        1 => tr_args(MsgId(453), [ArgValue::from(who), ArgValue::from(who)]).to_string(),
        _ => tr_args(MsgId(531), [ArgValue::from(who)]).to_string(),
    }
}

fn s019_1(n: i64, who: &'static str, when: &'static str) -> String {
    tr_args(MsgId(1426), [ArgValue::from(n)]).to_string()
}

fn s019_2(n: i64, who: &'static str, when: &'static str) -> String {
    tr_args(MsgId(220), [ArgValue::from(who), ArgValue::from(who)]).to_string()
}

fn s019_3(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(1298)).to_string(),
        1 => tr(MsgId(20)).to_string(),
        _ => tr(MsgId(1250)).to_string(),
    }
}

fn s019_4(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(1192)).to_string(),
        1 => tr(MsgId(1185)).to_string(),
        _ => tr(MsgId(1209)).to_string(),
    }
}

fn s019_6(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(891)).to_string(),
        1 => tr(MsgId(1157)).to_string(),
        _ => tr(MsgId(550)).to_string(),
    }
}

fn s019_7(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(1511)).to_string()
}

fn s019_8(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(59)).to_string()
}

#[component]
pub fn C019() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{move || s019_0(count.get(), who, when)}</p>
                <p>{s019_1(n, who, when)}</p>
                <p>{tr_args(MsgId(272), [ArgValue::from(who)])}</p>
                <p>{s019_2(n, who, when)}</p>
                <ul class="table" title={crate::tables::T019[0].label.to_string()}>
                    {crate::tables::T019.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <p>{tr(MsgId(240))}</p>
                <p>{move || s019_3(count.get(), who, when)}</p>
                <p>{move || if flag.get() { tr(MsgId(398)) } else { tr(MsgId(357)) }}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{move || s019_4(count.get(), who, when)}</p>
                <TextLabel text={tr(MsgId(1372))}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr(MsgId(623)).to_string(), 1 => tr(MsgId(338)).to_string(), _ => tr(MsgId(1014)).to_string(), });
                }>{tr(MsgId(1201))}</button>
                <p>{move || s019_6(count.get(), who, when)}</p>
                <p>{tr(MsgId(836))}</p>
                <p>{tr(MsgId(1007))}</p>
                <TextLabel text={tr(MsgId(1155))}/>
                <p>{s019_7(n, who, when)}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <SignalHint text={tr(MsgId(156))}/>
                <p>{s019_8(n, who, when)}</p>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 19">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
