//! Component C022 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::__mf2::{tr, tr_args, ArgValue, MsgId};

fn s022_1(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr_args(MsgId(1336), [ArgValue::from(n), ArgValue::from(who), ArgValue::from(who)]).to_string(),
        1 => tr_args(MsgId(464), [ArgValue::from(n)]).to_string(),
        _ => tr(MsgId(1171)).to_string(),
    }
}

fn s022_2(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(1580)).to_string(),
        1 => tr(MsgId(1585)).to_string(),
        _ => tr(MsgId(727)).to_string(),
    }
}

fn s022_4(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(842)).to_string(),
        1 => tr(MsgId(791)).to_string(),
        _ => tr(MsgId(489)).to_string(),
    }
}

fn s022_5(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(2) {
        0 => tr(MsgId(1583)).to_string(),
        _ => tr(MsgId(165)).to_string(),
    }
}

#[component]
pub fn C022() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr_args(MsgId(1546), [ArgValue::from(who)]).to_string(), _ => tr_args(MsgId(671), [ArgValue::from(who), ArgValue::from(who)]).to_string(), });
                }>{tr(MsgId(742))}</button>
                <p>{move || s022_1(count.get(), who, when)}</p>
                <p>{move || if flag.get() { tr_args(MsgId(78), [ArgValue::from(n)]) } else { tr_args(MsgId(1199), [ArgValue::from(n), ArgValue::from(who)]) }}</p>
                <StringBadge text={tr_args(MsgId(132), [ArgValue::from(n)])}/>
                <TextLabel text={move || tr_args(MsgId(360), [ArgValue::from(name), ArgValue::from(name)]).to_string()}/>
                <input type="text" aria-label={move || tr_args(MsgId(47), [ArgValue::from(name.get())])} placeholder={tr(MsgId(327))}/>
                <SignalHint text={tr(MsgId(2))}/>
                <p>{move || s022_2(count.get(), who, when)}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr(MsgId(1076)).to_string(), _ => tr(MsgId(1444)).to_string(), });
                }>"Apply"</button>
                <p>{move || s022_4(count.get(), who, when)}</p>
                <SignalHint text={tr(MsgId(400))}/>
                <p>{tr(MsgId(1423))}</p>
                <StringBadge text={tr(MsgId(1467))}/>
                <p>{tr(MsgId(1266))}</p>
                <ul class="table" title={crate::tables::T022[0].label.to_string()}>
                    {crate::tables::T022.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <TextLabel text={tr(MsgId(503))}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{move || s022_5(count.get(), who, when)}</p>
                <StringBadge text={tr(MsgId(1321))}/>
                <StringBadge text={tr(MsgId(364))}/>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 22">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
