//! Component C023 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::__mf2::{tr, tr_args, ArgValue, MsgId};

fn s023_0(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr_args(MsgId(972), [ArgValue::from(n)]).to_string(),
        1 => tr_args(MsgId(1042), [ArgValue::from(n)]).to_string(),
        _ => tr(MsgId(1399)).to_string(),
    }
}

fn s023_1(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(855)).to_string()
}

fn s023_2(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(968)).to_string(),
        1 => tr(MsgId(613)).to_string(),
        _ => tr(MsgId(254)).to_string(),
    }
}

fn s023_3(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(854)).to_string(),
        1 => tr(MsgId(1414)).to_string(),
        _ => tr(MsgId(1395)).to_string(),
    }
}

fn s023_4(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(1535)).to_string()
}

fn s023_5(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(631)).to_string(),
        1 => tr(MsgId(920)).to_string(),
        _ => tr(MsgId(560)).to_string(),
    }
}

fn s023_6(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(1301)).to_string()
}

#[component]
pub fn C023() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{tr_args(MsgId(944), [ArgValue::from(n), ArgValue::from(who)])}</p>
                <SignalHint text={tr_args(MsgId(659), [ArgValue::from(n)])}/>
                <p>{move || s023_0(count.get(), who, when)}</p>
                <SignalHint text={Signal::derive(move || tr_args(MsgId(592), [ArgValue::from(name), ArgValue::from(name)]).to_string())}/>
                <p>{move || tr_args(MsgId(1287), [ArgValue::from(name.get())])}</p>
                <p>{move || tr_args(MsgId(706), [ArgValue::from(name.get())])}</p>
                <SignalHint text={tr_args(MsgId(1218), [ArgValue::from(who)])}/>
                <ul class="table" title={crate::tables::T023[0].label.to_string()}>
                    {crate::tables::T023.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <SignalHint text={tr(MsgId(74))}/>
                <p>{s023_1(n, who, when)}</p>
                <p>{move || s023_2(count.get(), who, when)}</p>
                <p>{tr(MsgId(340))}</p>
                <p>{tr(MsgId(8))}</p>
                <p>{tr(MsgId(1331))}</p>
                <p>{move || s023_3(count.get(), who, when)}</p>
                <input type="text" aria-label={tr(MsgId(6))}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr(MsgId(1325))}</p>
                <p>{s023_4(n, who, when)}</p>
                <p>{tr(MsgId(184))}</p>
                <p>{move || s023_5(count.get(), who, when)}</p>
                <p>{s023_6(n, who, when)}</p>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 23">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
