//! Component C024 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::__mf2::{tr, tr_args, ArgValue, MsgId};

fn s024_1(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr_args(MsgId(724), [ArgValue::from(n)]).to_string(),
        1 => tr(MsgId(715)).to_string(),
        _ => tr(MsgId(232)).to_string(),
    }
}

fn s024_2(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(1116)).to_string(),
        1 => tr(MsgId(915)).to_string(),
        _ => tr(MsgId(1302)).to_string(),
    }
}

#[component]
pub fn C024() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr_args(MsgId(1368), [ArgValue::from(who), ArgValue::from(n)]).to_string(), _ => tr_args(MsgId(1311), [ArgValue::from(n)]).to_string(), });
                }>{tr(MsgId(1413))}</button>
                <ul class="table" title={crate::tables::T024[0].label.to_string()}>
                    {crate::tables::T024.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <StringBadge text={tr_args(MsgId(104), [ArgValue::from(who)])}/>
                <TextLabel text={move || tr_args(MsgId(266), [ArgValue::from(count.get())]).to_string()}/>
                <p>{tr_args(MsgId(781), [ArgValue::from(who)])}</p>
                <p>{move || s024_1(count.get(), who, when)}</p>
                <input type="text" aria-label={tr(MsgId(522))}/>
                <p>{tr(MsgId(1035))}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr(MsgId(1106))}</p>
                <p>{tr(MsgId(629))}</p>
                <p>{tr(MsgId(446))}</p>
                <p>{tr(MsgId(284))}</p>
                <p>{move || if flag.get() { tr(MsgId(213)) } else { tr(MsgId(355)) }}</p>
                <p>{tr(MsgId(552))}</p>
                <p>{move || s024_2(count.get(), who, when)}</p>
                <StringBadge text={tr(MsgId(910))}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <StringBadge text={tr(MsgId(616))}/>
                <p>{tr(MsgId(589))}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr(MsgId(1002)).to_string(), _ => tr(MsgId(533)).to_string(), });
                }>{tr(MsgId(11))}</button>
                <StringBadge text={tr(MsgId(187))}/>
                <p>{tr(MsgId(746))}</p>
                <SignalHint text={tr(MsgId(365))}/>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 24">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
