//! Component C025 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::__mf2::{tr, tr_args, ArgValue, MsgId};

fn s025_2(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(1282)).to_string(),
        1 => tr(MsgId(809)).to_string(),
        _ => tr(MsgId(457)).to_string(),
    }
}

fn s025_4(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(905)).to_string()
}

#[component]
pub fn C025() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{move || tr_args(MsgId(1126), [ArgValue::from(name), ArgValue::from(count)])}</p>
                <ul class="table" title={crate::tables::T025[0].label.to_string()}>
                    {crate::tables::T025.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr_args(MsgId(1427), [ArgValue::from(n)]).to_string(), _ => tr_args(MsgId(585), [ArgValue::from(n)]).to_string(), });
                }>{tr(MsgId(929))}</button>
                <p>{move || if flag.get() { tr_args(MsgId(1134), [ArgValue::from(n), ArgValue::from(who)]) } else { tr_args(MsgId(210), [ArgValue::from(n)]) }}</p>
                <p>{move || if flag.get() { tr_args(MsgId(42), [ArgValue::from(n)]) } else { tr_args(MsgId(1303), [ArgValue::from(n), ArgValue::from(n), ArgValue::from(who)]) }}</p>
                <p>{move || tr_args(MsgId(627), [ArgValue::from(count)])}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr(MsgId(971)).to_string());
                }>{tr(MsgId(1461))}</button>
                <SignalHint text={tr(MsgId(911))}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr(MsgId(1460))}</p>
                <p>{move || s025_2(count.get(), who, when)}</p>
                <p>{tr(MsgId(421))}</p>
                <p>{tr(MsgId(189))}</p>
                <SignalHint text={tr(MsgId(290))}/>
                <SignalHint text={tr(MsgId(1334))}/>
                <p>{tr(MsgId(965))}</p>
                <p>{tr(MsgId(995))}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr(MsgId(1339))}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr(MsgId(520)).to_string(), _ => tr(MsgId(321)).to_string(), });
                }>{tr(MsgId(843))}</button>
                <TextLabel text={tr(MsgId(732))}/>
                <p>{s025_4(n, who, when)}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr(MsgId(1370)).to_string(), _ => tr(MsgId(436)).to_string(), });
                }>{tr(MsgId(441))}</button>
                <TextLabel text={tr(MsgId(725))}/>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 25">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
