//! Component C026 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::__mf2::{tr, tr_args, ArgValue, MsgId};

fn s026_0(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr_args(MsgId(239), [ArgValue::from(who)]).to_string(),
        1 => tr_args(MsgId(776), [ArgValue::from(n)]).to_string(),
        _ => tr(MsgId(1548)).to_string(),
    }
}

fn s026_1(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(200)).to_string(),
        1 => tr(MsgId(277)).to_string(),
        _ => tr(MsgId(1552)).to_string(),
    }
}

fn s026_2(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(426)).to_string(),
        1 => tr(MsgId(810)).to_string(),
        _ => tr(MsgId(569)).to_string(),
    }
}

fn s026_3(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(730)).to_string(),
        1 => tr(MsgId(507)).to_string(),
        _ => tr(MsgId(660)).to_string(),
    }
}

#[component]
pub fn C026() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{move || s026_0(count.get(), who, when)}</p>
                <p>{move || tr_args(MsgId(1018), [ArgValue::from(name), ArgValue::from(name)])}</p>
                <SignalHint text={tr_args(MsgId(582), [ArgValue::from(who)])}/>
                <p>{move || if flag.get() { tr_args(MsgId(922), [ArgValue::from(n)]) } else { tr_args(MsgId(31), [ArgValue::from(who), ArgValue::from(n), ArgValue::from(who)]) }}</p>
                <StringBadge text={tr_args(MsgId(858), [ArgValue::from(who)])}/>
                <p>{move || if flag.get() { tr_args(MsgId(666), [ArgValue::from(n)]) } else { tr_args(MsgId(1598), [ArgValue::from(who)]) }}</p>
                <ul class="table" title={crate::tables::T026[0].label.to_string()}>
                    {crate::tables::T026.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <p>{move || s026_1(count.get(), who, when)}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <input type="text" aria-label={tr(MsgId(544))} placeholder={tr(MsgId(887))}/>
                <p>{move || s026_2(count.get(), who, when)}</p>
                <p>{move || if flag.get() { tr(MsgId(1131)) } else { tr(MsgId(126)) }}</p>
                <SignalHint text={tr(MsgId(1579))}/>
                <TextLabel text={tr(MsgId(326))}/>
                <p>{tr(MsgId(461))}</p>
                <p>{tr(MsgId(908))}</p>
                <p>{tr(MsgId(665))}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{move || s026_3(count.get(), who, when)}</p>
                <p>{move || if flag.get() { tr(MsgId(298)) } else { tr(MsgId(43)) }}</p>
                <TextLabel text={tr(MsgId(536))}/>
                <SignalHint text={tr(MsgId(4))}/>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 26">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
