//! Component C029 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::__mf2::{tr, tr_args, ArgValue, MsgId};

fn s029_1(n: i64, who: &'static str, when: &'static str) -> String {
    tr_args(MsgId(18), [ArgValue::from(who)]).to_string()
}

fn s029_2(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(251)).to_string(),
        1 => tr(MsgId(894)).to_string(),
        _ => tr(MsgId(7)).to_string(),
    }
}

fn s029_4(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(2) {
        0 => tr(MsgId(614)).to_string(),
        _ => tr(MsgId(1025)).to_string(),
    }
}

#[component]
pub fn C029() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <input type="text" aria-label={tr_args(MsgId(1241), [ArgValue::from(who)])} placeholder={tr(MsgId(390))}/>
                <StringBadge text={tr_args(MsgId(825), [ArgValue::from(who)])}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr_args(MsgId(1197), [ArgValue::from(who), ArgValue::from(who)]).to_string(), 1 => tr_args(MsgId(740), [ArgValue::from(n)]).to_string(), _ => tr_args(MsgId(515), [ArgValue::from(n)]).to_string(), });
                }>{tr(MsgId(448))}</button>
                <p>{s029_1(n, who, when)}</p>
                <p>{tr_args(MsgId(833), [ArgValue::from(n)])}</p>
                <p>{move || s029_2(count.get(), who, when)}</p>
                <p>{tr(MsgId(864))}</p>
                <ul class="table" title={crate::tables::T029[0].label.to_string()}>
                    {crate::tables::T029.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <StringBadge text={tr(MsgId(626))}/>
                <p>{tr(MsgId(1306))}</p>
                <p>{tr(MsgId(768))}</p>
                <p>{tr(MsgId(1362))}</p>
                <p>{tr(MsgId(433))}</p>
                <TextLabel text={tr(MsgId(130))}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr(MsgId(359)).to_string(), 1 => tr(MsgId(1551)).to_string(), _ => tr(MsgId(1371)).to_string(), });
                }>{tr(MsgId(506))}</button>
                <StringBadge text={tr(MsgId(1559))}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <TextLabel text={tr(MsgId(353))}/>
                <TextLabel text={tr(MsgId(477))}/>
                <TextLabel text={tr(MsgId(969))}/>
                <p>{move || s029_4(count.get(), who, when)}</p>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 29">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
