//! Component C037 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::__mf2::{tr, tr_args, ArgValue, MsgId};

fn s037_1(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr_args(MsgId(1172), [ArgValue::from(n), ArgValue::from(who)]).to_string(),
        1 => tr_args(MsgId(118), [ArgValue::from(who), ArgValue::from(who)]).to_string(),
        _ => tr(MsgId(1305)).to_string(),
    }
}

fn s037_3(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(1067)).to_string(),
        1 => tr(MsgId(80)).to_string(),
        _ => tr(MsgId(394)).to_string(),
    }
}

fn s037_4(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(912)).to_string()
}

#[component]
pub fn C037() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr_args(MsgId(776), [ArgValue::from(n)]).to_string());
                }>{tr(MsgId(715))}</button>
                <ul class="table" title={crate::tables::T037[0].label.to_string()}>
                    {crate::tables::T037.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <StringBadge text={tr_args(MsgId(956), [ArgValue::from(n), ArgValue::from(who)])}/>
                <TextLabel text={move || tr_args(MsgId(190), [ArgValue::from(name)]).to_string()}/>
                <p>{move || s037_1(count.get(), who, when)}</p>
                <p>{move || tr_args(MsgId(576), [ArgValue::from(count.get())])}</p>
                <p>{tr(MsgId(1162))}</p>
                <input type="text" aria-label={tr(MsgId(751))} placeholder={tr(MsgId(553))}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <StringBadge text={tr(MsgId(1571))}/>
                <p>{tr(MsgId(249))}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr(MsgId(523)).to_string(), 1 => tr(MsgId(438)).to_string(), _ => tr(MsgId(1084)).to_string(), });
                }>{tr(MsgId(638))}</button>
                <p>{tr(MsgId(1096))}</p>
                <SignalHint text={tr(MsgId(1013))}/>
                <p>{tr(MsgId(1070))}</p>
                <p>{tr(MsgId(984))}</p>
                <p>{tr(MsgId(1348))}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr(MsgId(1409))}</p>
                <p>{move || s037_3(count.get(), who, when)}</p>
                <p>{move || if flag.get() { tr(MsgId(765)) } else { tr(MsgId(73)) }}</p>
                <SignalHint text={tr(MsgId(1548))}/>
                <p>{s037_4(n, who, when)}</p>
                <p>{move || if flag.get() { tr(MsgId(629)) } else { tr(MsgId(1282)) }}</p>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 37">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
