//! Component C039 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::__mf2::{tr, tr_args, ArgValue, MsgId};

fn s039_1(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr_args(MsgId(1354), [ArgValue::from(n), ArgValue::from(who)]).to_string(),
        1 => tr(MsgId(1316)).to_string(),
        _ => tr(MsgId(1153)).to_string(),
    }
}

fn s039_3(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(1578)).to_string(),
        1 => tr(MsgId(850)).to_string(),
        _ => tr(MsgId(1476)).to_string(),
    }
}

fn s039_4(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(1560)).to_string(),
        1 => tr(MsgId(1383)).to_string(),
        _ => tr(MsgId(865)).to_string(),
    }
}

fn s039_5(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(1086)).to_string()
}

fn s039_6(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(200)).to_string()
}

#[component]
pub fn C039() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <ul class="table" title={crate::tables::T039[0].label.to_string()}>
                    {crate::tables::T039.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr_args(MsgId(1102), [ArgValue::from(who), ArgValue::from(who)]).to_string(), _ => tr_args(MsgId(1003), [ArgValue::from(n)]).to_string(), });
                }>{tr(MsgId(1460))}</button>
                <p>{tr_args(MsgId(1357), [ArgValue::from(n), ArgValue::from(n)])}</p>
                <input type="text" aria-label={move || tr_args(MsgId(792), [ArgValue::from(count), ArgValue::from(name)])} placeholder={tr(MsgId(1149))}/>
                <p>{move || s039_1(count.get(), who, when)}</p>
                <p>{move || if flag.get() { tr_args(MsgId(1184), [ArgValue::from(n)]) } else { tr_args(MsgId(1012), [ArgValue::from(n)]) }}</p>
                <p>{move || if flag.get() { tr(MsgId(996)) } else { tr(MsgId(103)) }}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr(MsgId(1455)).to_string());
                }>{tr(MsgId(749))}</button>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <SignalHint text={tr(MsgId(324))}/>
                <StringBadge text={tr(MsgId(94))}/>
                <p>{move || s039_3(count.get(), who, when)}</p>
                <StringBadge text={tr(MsgId(941))}/>
                <p>{move || s039_4(count.get(), who, when)}</p>
                <p>{move || if flag.get() { tr(MsgId(27)) } else { tr(MsgId(562)) }}</p>
                <TextLabel text={tr(MsgId(84))}/>
                <p>{tr(MsgId(268))}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{s039_5(n, who, when)}</p>
                <p>{s039_6(n, who, when)}</p>
                <TextLabel text={tr(MsgId(389))}/>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 39">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
