//! Component C041 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::__mf2::{tr, tr_args, ArgValue, MsgId};

fn s041_3(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(218)).to_string(),
        1 => tr(MsgId(1514)).to_string(),
        _ => tr(MsgId(295)).to_string(),
    }
}

fn s041_6(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(395)).to_string(),
        1 => tr(MsgId(1527)).to_string(),
        _ => tr(MsgId(120)).to_string(),
    }
}

fn s041_8(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(224)).to_string()
}

#[component]
pub fn C041() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{tr_args(MsgId(622), [ArgValue::from(who)])}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr_args(MsgId(163), [ArgValue::from(n), ArgValue::from(n)]).to_string(), 1 => tr_args(MsgId(1045), [ArgValue::from(who)]).to_string(), _ => tr_args(MsgId(208), [ArgValue::from(who)]).to_string(), });
                }>{tr(MsgId(1533))}</button>
                <p>{move || tr_args(MsgId(1567), [ArgValue::from(count.get())])}</p>
                <p>{move || tr_args(MsgId(769), [ArgValue::from(count.get())])}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr_args(MsgId(1508), [ArgValue::from(n)]).to_string());
                }>{tr(MsgId(713))}</button>
                <p>{move || if flag.get() { tr(MsgId(1474)) } else { tr(MsgId(482)) }}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr(MsgId(1147)).to_string(), 1 => tr(MsgId(1309)).to_string(), _ => tr(MsgId(643)).to_string(), });
                }>{tr(MsgId(315))}</button>
                <TextLabel text={tr(MsgId(258))}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr(MsgId(889))}</p>
                <p>{tr(MsgId(1251))}</p>
                <p>{move || s041_3(count.get(), who, when)}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr(MsgId(52)).to_string());
                }>{tr(MsgId(1173))}</button>
                <ul class="table" title={crate::tables::T041[0].label.to_string()}>
                    {crate::tables::T041.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr(MsgId(1481)).to_string());
                }>"Apply"</button>
                <p>{move || s041_6(count.get(), who, when)}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr(MsgId(1090)).to_string(), _ => tr(MsgId(811)).to_string(), });
                }>"Apply"</button>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{s041_8(n, who, when)}</p>
                <p>{move || if flag.get() { tr(MsgId(1306)) } else { tr(MsgId(306)) }}</p>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 41">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
