//! Component C043 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::__mf2::{tr, tr_args, ArgValue, MsgId};

fn s043_1(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr_args(MsgId(1510), [ArgValue::from(who), ArgValue::from(n)]).to_string(),
        1 => tr_args(MsgId(1313), [ArgValue::from(n)]).to_string(),
        _ => tr_args(MsgId(1138), [ArgValue::from(who)]).to_string(),
    }
}

fn s043_2(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(537)).to_string()
}

fn s043_3(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(144)).to_string()
}

fn s043_5(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(38)).to_string(),
        1 => tr(MsgId(1554)).to_string(),
        _ => tr(MsgId(794)).to_string(),
    }
}

fn s043_6(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(689)).to_string(),
        1 => tr(MsgId(525)).to_string(),
        _ => tr(MsgId(1207)).to_string(),
    }
}

fn s043_7(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(1062)).to_string(),
        1 => tr(MsgId(1293)).to_string(),
        _ => tr(MsgId(1462)).to_string(),
    }
}

fn s043_8(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(171)).to_string()
}

#[component]
pub fn C043() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr_args(MsgId(938), [ArgValue::from(who)]).to_string(), _ => tr_args(MsgId(1107), [ArgValue::from(n)]).to_string(), });
                }>{tr(MsgId(148))}</button>
                <p>{move || s043_1(count.get(), who, when)}</p>
                <p>{tr_args(MsgId(312), [ArgValue::from(n)])}</p>
                <TextLabel text={tr_args(MsgId(1380), [ArgValue::from(who)])}/>
                <ul class="table" title={crate::tables::T043[0].label.to_string()}>
                    {crate::tables::T043.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <p>{s043_2(n, who, when)}</p>
                <p>{s043_3(n, who, when)}</p>
                <input type="text" aria-label={tr(MsgId(645))} placeholder={tr(MsgId(5))}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr(MsgId(463)).to_string(), _ => tr(MsgId(1074)).to_string(), });
                }>{tr(MsgId(697))}</button>
                <p>{move || s043_5(count.get(), who, when)}</p>
                <p>{move || s043_6(count.get(), who, when)}</p>
                <p>{tr(MsgId(987))}</p>
                <p>{move || s043_7(count.get(), who, when)}</p>
                <p>{s043_8(n, who, when)}</p>
                <StringBadge text={tr(MsgId(1352))}/>
                <input type="text" aria-label={tr(MsgId(626))}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr(MsgId(936)).to_string());
                }>"Apply"</button>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 43">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
