//! Component C045 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::__mf2::{tr, tr_args, ArgValue, MsgId};

fn s045_1(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr_args(MsgId(641), [ArgValue::from(who)]).to_string(),
        1 => tr_args(MsgId(782), [ArgValue::from(who)]).to_string(),
        _ => tr(MsgId(770)).to_string(),
    }
}

fn s045_3(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(1100)).to_string(),
        1 => tr(MsgId(1222)).to_string(),
        _ => tr(MsgId(1152)).to_string(),
    }
}

#[component]
pub fn C045() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <input type="text" aria-label={move || tr_args(MsgId(946), [ArgValue::from(name.get())])} placeholder={tr_args(MsgId(655), [ArgValue::from(n)])}/>
                <StringBadge text={tr_args(MsgId(450), [ArgValue::from(who), ArgValue::from(who)])}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr_args(MsgId(958), [ArgValue::from(n)]).to_string());
                }>{tr(MsgId(54))}</button>
                <p>{move || s045_1(count.get(), who, when)}</p>
                <ul class="table" title={crate::tables::T045[0].label.to_string()}>
                    {crate::tables::T045.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <input type="text" aria-label={tr(MsgId(669))} placeholder={tr(MsgId(1587))}/>
                <p>{tr(MsgId(719))}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr(MsgId(1048)).to_string(), _ => tr(MsgId(1522)).to_string(), });
                }>{tr(MsgId(1269))}</button>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr(MsgId(304))}</p>
                <p>{move || if flag.get() { tr(MsgId(72)) } else { tr(MsgId(167)) }}</p>
                <TextLabel text={tr(MsgId(318))}/>
                <p>{move || if flag.get() { tr(MsgId(1528)) } else { tr(MsgId(650)) }}</p>
                <input type="text" aria-label={tr(MsgId(1110))} placeholder={tr(MsgId(1490))}/>
                <SignalHint text={tr(MsgId(1255))}/>
                <p>{move || s045_3(count.get(), who, when)}</p>
                <StringBadge text={tr(MsgId(225))}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <SignalHint text={tr(MsgId(1443))}/>
                <input type="text" aria-label={tr(MsgId(634))}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr(MsgId(906)).to_string());
                }>"Apply"</button>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr(MsgId(504)).to_string(), _ => tr(MsgId(1183)).to_string(), });
                }>"Apply"</button>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 45">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
