//! Component C047 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::__mf2::{tr, tr_args, ArgValue, MsgId};

fn s047_1(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(814)).to_string(),
        1 => tr(MsgId(430)).to_string(),
        _ => tr(MsgId(101)).to_string(),
    }
}

fn s047_2(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(1277)).to_string()
}

fn s047_3(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(149)).to_string(),
        1 => tr(MsgId(305)).to_string(),
        _ => tr(MsgId(181)).to_string(),
    }
}

fn s047_4(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(1071)).to_string(),
        1 => tr(MsgId(1117)).to_string(),
        _ => tr(MsgId(1300)).to_string(),
    }
}

#[component]
pub fn C047() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <TextLabel text={move || tr_args(MsgId(354), [ArgValue::from(name)]).to_string()}/>
                <ul class="table" title={crate::tables::T047[0].label.to_string()}>
                    {crate::tables::T047.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <TextLabel text={tr_args(MsgId(1393), [ArgValue::from(n)])}/>
                <p>{move || tr_args(MsgId(334), [ArgValue::from(count.get()), ArgValue::from(name.get())])}</p>
                <SignalHint text={Signal::derive(move || tr_args(MsgId(95), [ArgValue::from(count.get()), ArgValue::from(count.get()), ArgValue::from(name.get())]).to_string())}/>
                <p>{tr_args(MsgId(115), [ArgValue::from(who)])}</p>
                <p>{move || tr_args(MsgId(1375), [ArgValue::from(count)])}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr(MsgId(381)).to_string());
                }>{tr(MsgId(498))}</button>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <input type="text" aria-label={tr(MsgId(1292))} placeholder={tr(MsgId(81))}/>
                <p>{move || s047_1(count.get(), who, when)}</p>
                <p>{tr(MsgId(432))}</p>
                <p>{s047_2(n, who, when)}</p>
                <p>{move || s047_3(count.get(), who, when)}</p>
                <p>{tr(MsgId(117))}</p>
                <SignalHint text={tr(MsgId(1537))}/>
                <TextLabel text={tr(MsgId(610))}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{move || s047_4(count.get(), who, when)}</p>
                <input type="text" aria-label={tr(MsgId(844))}/>
                <p>{tr(MsgId(835))}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr(MsgId(943)).to_string(), _ => tr(MsgId(1285)).to_string(), });
                }>{tr(MsgId(1390))}</button>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 47">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
