//! Component C048 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::__mf2::{tr, tr_args, ArgValue, MsgId};

fn s048_0(n: i64, who: &'static str, when: &'static str) -> String {
    tr_args(MsgId(248), [ArgValue::from(n)]).to_string()
}

fn s048_1(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr_args(MsgId(942), [ArgValue::from(who)]).to_string(),
        1 => tr_args(MsgId(134), [ArgValue::from(who)]).to_string(),
        _ => tr(MsgId(1597)).to_string(),
    }
}

fn s048_2(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(841)).to_string(),
        1 => tr(MsgId(637)).to_string(),
        _ => tr(MsgId(1202)).to_string(),
    }
}

fn s048_3(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(278)).to_string()
}

#[component]
pub fn C048() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{move || if flag.get() { tr_args(MsgId(1491), [ArgValue::from(n)]) } else { tr_args(MsgId(576), [ArgValue::from(n)]) }}</p>
                <p>{s048_0(n, who, when)}</p>
                <p>{move || tr_args(MsgId(1520), [ArgValue::from(name)])}</p>
                <p>{tr_args(MsgId(1158), [ArgValue::from(n), ArgValue::from(n)])}</p>
                <p>{move || s048_1(count.get(), who, when)}</p>
                <input type="text" aria-label={move || tr_args(MsgId(1064), [ArgValue::from(name)])} placeholder={tr(MsgId(313))}/>
                <p>{move || s048_2(count.get(), who, when)}</p>
                <p>{tr(MsgId(1412))}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr(MsgId(818))}</p>
                <ul class="table" title={crate::tables::T048[0].label.to_string()}>
                    {crate::tables::T048.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <p>{tr(MsgId(388))}</p>
                <SignalHint text={tr(MsgId(1564))}/>
                <StringBadge text={tr(MsgId(676))}/>
                <p>{tr(MsgId(233))}</p>
                <p>{tr(MsgId(763))}</p>
                <p>{move || if flag.get() { tr(MsgId(1180)) } else { tr(MsgId(748)) }}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{s048_3(n, who, when)}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr(MsgId(264)).to_string());
                }>{tr(MsgId(1129))}</button>
                <input type="text" aria-label={tr(MsgId(909))} placeholder={tr(MsgId(1305))}/>
                <p>{move || if flag.get() { tr(MsgId(927)) } else { tr(MsgId(195)) }}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr(MsgId(1211)).to_string(), 1 => tr(MsgId(1524)).to_string(), _ => tr(MsgId(1384)).to_string(), });
                }>{tr(MsgId(673))}</button>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 48">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
