//! Component C049 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::__mf2::{tr, tr_args, ArgValue, MsgId};

fn s049_2(n: i64, who: &'static str, when: &'static str) -> String {
    tr_args(MsgId(1061), [ArgValue::from(n)]).to_string()
}

fn s049_4(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(1521)).to_string()
}

fn s049_9(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(2) {
        0 => tr(MsgId(636)).to_string(),
        _ => tr(MsgId(694)).to_string(),
    }
}

#[component]
pub fn C049() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <StringBadge text={tr_args(MsgId(661), [ArgValue::from(n)])}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr_args(MsgId(275), [ArgValue::from(who), ArgValue::from(who)]).to_string());
                }>{tr(MsgId(1162))}</button>
                <p>{move || tr_args(MsgId(1516), [ArgValue::from(count.get())])}</p>
                <input type="text" aria-label={move || tr_args(MsgId(146), [ArgValue::from(count)])} placeholder={tr(MsgId(1225))}/>
                <ul class="table" title={crate::tables::T049[0].label.to_string()}>
                    {crate::tables::T049.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr_args(MsgId(529), [ArgValue::from(who), ArgValue::from(who)]).to_string());
                }>{tr(MsgId(368))}</button>
                <p>{s049_2(n, who, when)}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr(MsgId(1278)).to_string());
                }>{tr(MsgId(1256))}</button>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr(MsgId(1512))}</p>
                <p>{tr(MsgId(1082))}</p>
                <p>{s049_4(n, who, when)}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr(MsgId(1213)).to_string(), _ => tr(MsgId(903)).to_string(), });
                }>"Apply"</button>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr(MsgId(1212)).to_string(), _ => tr(MsgId(162)).to_string(), });
                }>"Apply"</button>
                <StringBadge text={tr(MsgId(128))}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr(MsgId(985)).to_string(), _ => tr(MsgId(1464)).to_string(), });
                }>"Apply"</button>
                <p>{tr(MsgId(485))}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <TextLabel text={tr(MsgId(92))}/>
                <p>{move || if flag.get() { tr(MsgId(499)) } else { tr(MsgId(1135)) }}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr(MsgId(1270)).to_string(), 1 => tr(MsgId(528)).to_string(), _ => tr(MsgId(1439)).to_string(), });
                }>"Apply"</button>
                <p>{move || s049_9(count.get(), who, when)}</p>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 49">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
