//! Component C051 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::__mf2::{tr, tr_args, ArgValue, MsgId};

fn s051_0(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr_args(MsgId(285), [ArgValue::from(who)]).to_string(),
        1 => tr_args(MsgId(75), [ArgValue::from(n)]).to_string(),
        _ => tr_args(MsgId(859), [ArgValue::from(who)]).to_string(),
    }
}

fn s051_2(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(152)).to_string()
}

fn s051_6(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(866)).to_string()
}

fn s051_7(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(1132)).to_string(),
        1 => tr(MsgId(1404)).to_string(),
        _ => tr(MsgId(996)).to_string(),
    }
}

fn s051_8(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(2) {
        0 => tr(MsgId(1316)).to_string(),
        _ => tr(MsgId(857)).to_string(),
    }
}

#[component]
pub fn C051() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <StringBadge text={tr_args(MsgId(1012), [ArgValue::from(n)])}/>
                <p>{move || s051_0(count.get(), who, when)}</p>
                <input type="text" aria-label={tr_args(MsgId(663), [ArgValue::from(n), ArgValue::from(n)])} placeholder={tr(MsgId(451))}/>
                <p>{move || tr_args(MsgId(99), [ArgValue::from(name.get()), ArgValue::from(name.get())])}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr_args(MsgId(32), [ArgValue::from(who)]).to_string());
                }>{tr(MsgId(1146))}</button>
                <p>{s051_2(n, who, when)}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr(MsgId(79)).to_string());
                }>{tr(MsgId(896))}</button>
                <TextLabel text={tr(MsgId(1122))}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr(MsgId(1320)).to_string(), _ => tr(MsgId(1290)).to_string(), });
                }>"Apply"</button>
                <p>{tr(MsgId(902))}</p>
                <ul class="table" title={crate::tables::T051[0].label.to_string()}>
                    {crate::tables::T051.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <p>{move || if flag.get() { tr(MsgId(856)) } else { tr(MsgId(711)) }}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr(MsgId(1058)).to_string(), 1 => tr(MsgId(1053)).to_string(), _ => tr(MsgId(557)).to_string(), });
                }>"Apply"</button>
                <SignalHint text={tr(MsgId(881))}/>
                <p>{s051_6(n, who, when)}</p>
                <TextLabel text={tr(MsgId(1054))}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{move || s051_7(count.get(), who, when)}</p>
                <p>{move || s051_8(count.get(), who, when)}</p>
                <StringBadge text={tr(MsgId(67))}/>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 51">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
