//! Component C054 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::__mf2::{tr, tr_args, ArgValue, MsgId};

fn s054_0(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr_args(MsgId(760), [ArgValue::from(n)]).to_string(),
        1 => tr(MsgId(173)).to_string(),
        _ => tr(MsgId(654)).to_string(),
    }
}

fn s054_1(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(677)).to_string()
}

fn s054_3(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(1572)).to_string(),
        1 => tr(MsgId(358)).to_string(),
        _ => tr(MsgId(1355)).to_string(),
    }
}

fn s054_4(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(914)).to_string()
}

fn s054_5(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(543)).to_string(),
        1 => tr(MsgId(1517)).to_string(),
        _ => tr(MsgId(717)).to_string(),
    }
}

fn s054_6(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(898)).to_string()
}

fn s054_7(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(1239)).to_string()
}

fn s054_8(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(1063)).to_string()
}

#[component]
pub fn C054() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{move || tr_args(MsgId(1555), [ArgValue::from(name), ArgValue::from(count)])}</p>
                <StringBadge text={tr_args(MsgId(688), [ArgValue::from(n), ArgValue::from(who)])}/>
                <ul class="table" title={crate::tables::T054[0].label.to_string()}>
                    {crate::tables::T054.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <input type="text" aria-label={tr_args(MsgId(1304), [ArgValue::from(who)])} placeholder={tr(MsgId(273))}/>
                <p>{move || s054_0(count.get(), who, when)}</p>
                <p>{move || if flag.get() { tr_args(MsgId(1143), [ArgValue::from(who)]) } else { tr_args(MsgId(496), [ArgValue::from(n), ArgValue::from(who)]) }}</p>
                <p>{s054_1(n, who, when)}</p>
                <p>{tr(MsgId(1553))}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr(MsgId(1166)).to_string(), 1 => tr(MsgId(1501)).to_string(), _ => tr(MsgId(578)).to_string(), });
                }>{tr(MsgId(1474))}</button>
                <p>{move || s054_3(count.get(), who, when)}</p>
                <p>{s054_4(n, who, when)}</p>
                <p>{move || s054_5(count.get(), who, when)}</p>
                <p>{s054_6(n, who, when)}</p>
                <p>{s054_7(n, who, when)}</p>
                <input type="text" aria-label={tr(MsgId(668))}/>
                <p>{s054_8(n, who, when)}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr(MsgId(392)).to_string(), 1 => tr(MsgId(258)).to_string(), _ => tr(MsgId(1317)).to_string(), });
                }>"Apply"</button>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 54">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
