//! Component C056 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::__mf2::{tr, tr_args, ArgValue, MsgId};

fn s056_2(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(1243)).to_string()
}

fn s056_3(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(1338)).to_string(),
        1 => tr(MsgId(1057)).to_string(),
        _ => tr(MsgId(983)).to_string(),
    }
}

fn s056_4(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(1008)).to_string(),
        1 => tr(MsgId(1124)).to_string(),
        _ => tr(MsgId(795)).to_string(),
    }
}

fn s056_5(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(962)).to_string(),
        1 => tr(MsgId(144)).to_string(),
        _ => tr(MsgId(135)).to_string(),
    }
}

#[component]
pub fn C056() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <StringBadge text={tr_args(MsgId(782), [ArgValue::from(who)])}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr_args(MsgId(899), [ArgValue::from(who)]).to_string(), _ => tr_args(MsgId(35), [ArgValue::from(who)]).to_string(), });
                }>{tr(MsgId(3))}</button>
                <p>{move || if flag.get() { tr_args(MsgId(323), [ArgValue::from(who), ArgValue::from(n)]) } else { tr_args(MsgId(131), [ArgValue::from(n)]) }}</p>
                <ul class="table" title={crate::tables::T056[0].label.to_string()}>
                    {crate::tables::T056.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr_args(MsgId(199), [ArgValue::from(n)]).to_string());
                }>{tr(MsgId(465))}</button>
                <p>{move || tr_args(MsgId(1236), [ArgValue::from(name.get()), ArgValue::from(name.get())])}</p>
                <p>{s056_2(n, who, when)}</p>
                <p>{move || s056_3(count.get(), who, when)}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr(MsgId(615))}</p>
                <p>{tr(MsgId(767))}</p>
                <p>{tr(MsgId(302))}</p>
                <p>{tr(MsgId(309))}</p>
                <SignalHint text={tr(MsgId(1421))}/>
                <p>{tr(MsgId(96))}</p>
                <p>{move || s056_4(count.get(), who, when)}</p>
                <input type="text" aria-label={tr(MsgId(1085))} placeholder={tr(MsgId(683))}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{move || s056_5(count.get(), who, when)}</p>
                <input type="text" aria-label={tr(MsgId(1120))}/>
                <SignalHint text={tr(MsgId(1198))}/>
                <TextLabel text={tr(MsgId(1048))}/>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 56">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
