//! Component C058 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::__mf2::{tr, tr_args, ArgValue, MsgId};

fn s058_0(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr_args(MsgId(999), [ArgValue::from(who), ArgValue::from(who)]).to_string(),
        1 => tr_args(MsgId(1471), [ArgValue::from(n)]).to_string(),
        _ => tr_args(MsgId(1584), [ArgValue::from(who)]).to_string(),
    }
}

fn s058_1(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr_args(MsgId(928), [ArgValue::from(n), ArgValue::from(who)]).to_string(),
        1 => tr_args(MsgId(752), [ArgValue::from(who), ArgValue::from(n)]).to_string(),
        _ => tr(MsgId(1000)).to_string(),
    }
}

fn s058_2(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(1121)).to_string(),
        1 => tr(MsgId(808)).to_string(),
        _ => tr(MsgId(955)).to_string(),
    }
}

fn s058_4(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(696)).to_string(),
        1 => tr(MsgId(1487)).to_string(),
        _ => tr(MsgId(1235)).to_string(),
    }
}

fn s058_5(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(2) {
        0 => tr(MsgId(669)).to_string(),
        _ => tr(MsgId(630)).to_string(),
    }
}

#[component]
pub fn C058() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{move || s058_0(count.get(), who, when)}</p>
                <ul class="table" title={crate::tables::T058[0].label.to_string()}>
                    {crate::tables::T058.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <p>{move || s058_1(count.get(), who, when)}</p>
                <p>{tr_args(MsgId(890), [ArgValue::from(who)])}</p>
                <input type="text" aria-label={tr(MsgId(182))} placeholder={tr(MsgId(432))}/>
                <p>{tr(MsgId(403))}</p>
                <p>{move || s058_2(count.get(), who, when)}</p>
                <p>{tr(MsgId(647))}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr(MsgId(16))}</p>
                <p>{tr(MsgId(1248))}</p>
                <p>{move || if flag.get() { tr(MsgId(1145)) } else { tr(MsgId(712)) }}</p>
                <p>{move || if flag.get() { tr(MsgId(708)) } else { tr(MsgId(372)) }}</p>
                <p>{tr(MsgId(1430))}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr(MsgId(778)).to_string(), 1 => tr(MsgId(601)).to_string(), _ => tr(MsgId(124)).to_string(), });
                }>{tr(MsgId(1587))}</button>
                <p>{tr(MsgId(1506))}</p>
                <TextLabel text={tr(MsgId(1326))}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{move || s058_4(count.get(), who, when)}</p>
                <p>{move || s058_5(count.get(), who, when)}</p>
                <p>{move || if flag.get() { tr(MsgId(1191)) } else { tr(MsgId(1292)) }}</p>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 58">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
