//! Component C059 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::__mf2::{tr, tr_args, ArgValue, MsgId};

fn s059_0(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr_args(MsgId(847), [ArgValue::from(n)]).to_string(),
        1 => tr_args(MsgId(351), [ArgValue::from(who), ArgValue::from(n)]).to_string(),
        _ => tr(MsgId(990)).to_string(),
    }
}

fn s059_2(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(877)).to_string()
}

fn s059_3(n: i64, who: &'static str, when: &'static str) -> String {
    tr(MsgId(1433)).to_string()
}

fn s059_4(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr(MsgId(1536)).to_string(),
        1 => tr(MsgId(1023)).to_string(),
        _ => tr(MsgId(1596)).to_string(),
    }
}

#[component]
pub fn C059() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{move || tr_args(MsgId(1375), [ArgValue::from(count.get())])}</p>
                <p>{move || s059_0(count.get(), who, when)}</p>
                <p>{move || if flag.get() { tr_args(MsgId(1531), [ArgValue::from(n)]) } else { tr_args(MsgId(336), [ArgValue::from(who)]) }}</p>
                <ul class="table" title={crate::tables::T059[0].label.to_string()}>
                    {crate::tables::T059.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <SignalHint text={Signal::derive(move || tr_args(MsgId(419), [ArgValue::from(name)]).to_string())}/>
                <input type="text" aria-label={tr_args(MsgId(1442), [ArgValue::from(n)])}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr(MsgId(707)).to_string(), 1 => tr(MsgId(1392)).to_string(), _ => tr(MsgId(1242)).to_string(), });
                }>{tr(MsgId(719))}</button>
                <p>{tr(MsgId(608))}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr(MsgId(848))}</p>
                <SignalHint text={tr(MsgId(793))}/>
                <p>{tr(MsgId(256))}</p>
                <StringBadge text={tr(MsgId(535))}/>
                <p>{tr(MsgId(883))}</p>
                <p>{s059_2(n, who, when)}</p>
                <p>{s059_3(n, who, when)}</p>
                <StringBadge text={tr(MsgId(1538))}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{move || if flag.get() { tr(MsgId(1401)) } else { tr(MsgId(1346)) }}</p>
                <p>{move || s059_4(count.get(), who, when)}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr(MsgId(1470)).to_string());
                }>{tr(MsgId(841))}</button>
                <TextLabel text={tr(MsgId(121))}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr(MsgId(313)).to_string());
                }>{tr(MsgId(1217))}</button>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 59">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
