//! `mf2-locale-data` — the locale data mf2-two catalogs carry
//! (`plans/05-tooling.md` §7; `plans/02-catalog-format.md` §4), build side
//! only: never linked into a client.
//!
//! The crate ships its data in `data/` (an application's `build.rs` has no
//! `third_party/` and downloads nothing), generated by `cargo xtask
//! locale-data`:
//!
//! * **plural** rules and each locale's **text direction** (Phase 3), from
//!   the vendored CLDR JSON: the UTS #35 rule parser, the canonical encoder
//!   of the `plural.cardinal` / `plural.ordinal` entries; the CLDR
//!   `@integer`/`@decimal` samples of every locale are tests of the client
//!   evaluator (`tests/cldr_samples.rs`);
//! * **numbers** (Phase 4, A2), from every locale's `numbers.json` in the
//!   `cargo xtask cldr-sync` cache: symbols, grouping, numbering systems and
//!   their digits, the percent and currency patterns, deduplicated against
//!   CLDR's parent locales (`data/numbers.txt`), and the `number.symbols` /
//!   `number.patterns` entries built from them ([`number`]).
//!
//! Currency and unit display data follow in Phase 4 (A4).

mod direction;
pub mod error;
#[cfg(feature = "extract")]
pub mod extract;
pub mod number;
pub mod plural;

pub use direction::direction;
pub use error::{Error, ParseError};
pub use mf2_catalog::CldrVersion;
pub use number::{
    CurrencyNeeds, NumberData, NumberNeeds, number_data, number_locale_entries, number_locales,
};
pub use plural::{
    LocaleRules, PluralKind, plural_entry, plural_locale_entries, plural_locales, plural_rules,
};

/// The CLDR release the shipped data comes from (`third_party/cldr-json/PIN`).
pub const CLDR_VERSION: CldrVersion = CldrVersion {
    major: 48,
    minor: 2,
    patch: 1,
};

/// Everything a corpus needs of its locale's data: plural rules of each
/// kind it selects on, and number data ([`NumberNeeds`]). The slicing rule
/// is `plans/02-catalog-format.md` §4.4. Build one with `default()` and set
/// fields.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
#[non_exhaustive]
pub struct LocaleNeeds {
    /// Some selector uses `select=plural` (the default) → `plural.cardinal`.
    pub cardinal: bool,
    /// Some selector uses `select=ordinal` → `plural.ordinal`.
    pub ordinal: bool,
    /// The number entries.
    pub numbers: NumberNeeds,
}

/// The LOCALE entries a catalog for `locale` carries under `needs`, sorted by
/// key, as `mf2_catalog::writer::Options::locale_entries` takes them.
pub fn locale_entries(locale: &str, needs: &LocaleNeeds) -> Result<Vec<(u32, Vec<u8>)>, Error> {
    let mut kinds = Vec::new();
    if needs.cardinal {
        kinds.push(PluralKind::Cardinal);
    }
    if needs.ordinal {
        kinds.push(PluralKind::Ordinal);
    }
    let mut out = plural_locale_entries(locale, &kinds)?;
    out.extend(number_locale_entries(locale, &needs.numbers)?);
    out.sort_by_key(|(k, _)| *k);
    Ok(out)
}
