//! Number data (`plans/05-tooling.md` §7, `plans/02-catalog-format.md`
//! §4.2–§4.4): the shipped all-locale table (`data/numbers.txt`), CLDR's
//! locale resolution for it, and the `number.symbols` / `number.patterns`
//! LOCALE entries of a catalog, sliced to what its corpus needs.
//!
//! A catalog has **one** numbering system — its locale's default, or the
//! one its tag names with `-u-nu-` — because MF2 (at the pinned spec) has no
//! `numberingSystem` option. Its digits travel inside `number.symbols`.

pub mod pattern;
pub mod table;
pub mod tag;

use std::collections::BTreeMap;
use std::sync::OnceLock;

use mf2_catalog::format::locale_key;
use mf2_catalog::number::Style;
use mf2_catalog::writer::number::{SymbolsSpec, patterns, symbols};

pub use self::table::{Record, Table};
pub use self::tag::Tag;

use crate::error::Error;

/// The shipped table: `data/numbers.txt`, generated by `cargo xtask
/// locale-data` from the `cargo xtask cldr-sync` cache.
const TABLE: &str = include_str!("../data/numbers.txt");

fn table() -> Result<&'static Table<'static>, Error> {
    static PARSED: OnceLock<Result<Table<'static>, String>> = OnceLock::new();
    match PARSED.get_or_init(|| Table::parse(TABLE).map_err(|e| e.to_string())) {
        Ok(t) => Ok(t),
        Err(message) => Err(Error::Table {
            line: 0,
            message: message.clone(),
        }),
    }
}

/// What a corpus needs of its locale's number data: the slicing rule of
/// `plans/02-catalog-format.md` §4.4, decided by the build from the functions
/// and literal options the corpus uses. Build one with `default()` and set
/// fields (the currency and unit sets join in Phase 4, A4).
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
#[non_exhaustive]
pub struct NumberNeeds {
    /// Numbers are formatted with the locale's symbols: `fn-number` is on
    /// and the corpus formats a numeric function or has a placeholder that
    /// can receive a number → `number.symbols`.
    pub symbols: bool,
    /// `:percent` is used → `number.symbols` and the percent pattern.
    pub percent: bool,
    /// `:currency` is used → `number.symbols` and its patterns.
    pub currency: Option<CurrencyNeeds>,
}

/// Which currency patterns a corpus's `:currency` may need.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
#[non_exhaustive]
pub struct CurrencyNeeds {
    /// `currencySign=accounting` may occur (a literal `accounting`, or a
    /// variable value) → the accounting patterns.
    pub accounting: bool,
    /// `currencyDisplay=never` may occur (literal or variable) → the
    /// no-symbol patterns.
    pub hidden: bool,
}

impl CurrencyNeeds {
    /// Every currency pattern (the option values are unknown).
    pub const ALL: CurrencyNeeds = CurrencyNeeds {
        accounting: true,
        hidden: true,
    };
}

impl NumberNeeds {
    /// The conservative needs of a corpus known only by its function set
    /// (`ns:name` identifiers, as FUNCS lists them): every numeric function
    /// formats with symbols, `:percent` needs its pattern, `:currency` every
    /// currency pattern (its option values being unknown).
    pub fn from_functions<'a>(functions: impl IntoIterator<Item = &'a str>) -> NumberNeeds {
        let mut n = NumberNeeds::default();
        for f in functions {
            match f {
                "number" | "integer" | "offset" | "unit" => n.symbols = true,
                "percent" => n.percent = true,
                "currency" => n.currency = Some(CurrencyNeeds::ALL),
                _ => {}
            }
        }
        n
    }

    /// Whether any number entry is needed.
    pub const fn any(&self) -> bool {
        self.symbols || self.percent || self.currency.is_some()
    }

    /// The `number.patterns` styles these needs select.
    pub fn styles(&self) -> Vec<Style> {
        let mut out = Vec::new();
        if self.percent {
            out.push(Style::Percent);
        }
        if let Some(c) = self.currency {
            out.extend([Style::Currency, Style::CurrencyAlpha]);
            if c.hidden {
                out.push(Style::CurrencyNoSymbol);
            }
            if c.accounting {
                out.extend([Style::Accounting, Style::AccountingAlpha]);
                if c.hidden {
                    out.push(Style::AccountingNoSymbol);
                }
            }
        }
        out
    }
}

/// The table field of a pattern style.
pub const fn style_field(style: Style) -> &'static str {
    match style {
        Style::Percent => "percent-pattern",
        Style::Currency => "currency",
        Style::CurrencyAlpha => "currency-alpha",
        Style::CurrencyNoSymbol => "currency-none",
        Style::Accounting => "accounting",
        Style::AccountingAlpha => "accounting-alpha",
        Style::AccountingNoSymbol => "accounting-none",
    }
}

/// A locale's number data as CLDR resolves it for one tag.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct NumberData {
    /// The CLDR locale the data comes from (after truncation and parents;
    /// `und` is root).
    pub locale: &'static str,
    /// The catalog's numbering system: `-u-nu-` when it names a numeric
    /// system (`native` → the locale's native one), else the locale's
    /// default.
    pub numbering_system: &'static str,
    /// The system whose symbols and patterns apply: the numbering system when
    /// the locale has data for it, else `latn` (`en-u-nu-arab`: Latin symbols,
    /// Arabic-Indic digits — CLDR's root has no other system).
    pub symbols_system: &'static str,
    /// The ten digits; `None` for `latn`.
    pub digits: Option<&'static str>,
    /// CLDR's `minimumGroupingDigits`.
    pub minimum_grouping_digits: u8,
    pub decimal: &'static str,
    pub group: &'static str,
    pub minus: &'static str,
    pub plus: &'static str,
    pub percent: &'static str,
    /// The decimal pattern (for its grouping).
    pub decimal_pattern: &'static str,
    /// The percent and currency patterns CLDR has, by style.
    pub patterns: BTreeMap<Style, &'static str>,
}

/// Resolves `tag` to a CLDR locale of the table: a region that implies a
/// script other than the language's gains it first (`zh-TW` → `zh-Hant-TW`,
/// when a `zh-Hant` locale exists), then the tag, its parents and
/// truncations, root.
fn resolve_locale(t: &'static Table<'static>, tag: &Tag) -> &'static str {
    let mut tag = tag.clone();
    if tag.script.is_none()
        && let Some(region) = &tag.region
        && let Some(script) = t.likely.get(format!("{}-{region}", tag.language).as_str())
    {
        tag.script = Some((*script).to_owned());
    }
    t.lookup(&tag.base())
}

fn field(
    t: &'static Table<'static>,
    locale: &'static str,
    system: &'static str,
    name: &'static str,
) -> Result<&'static str, Error> {
    t.system_field(locale, system, name)
        .ok_or_else(|| Error::Missing {
            locale: locale.to_owned(),
            system: system.to_owned(),
            field: name,
        })
}

/// The number data for `tag` (BCP 47; `_` is read as `-`, case ignored).
pub fn number_data(tag: &str) -> Result<NumberData, Error> {
    let t = table()?;
    let parsed = Tag::parse(tag);
    let locale = resolve_locale(t, &parsed);
    let default = t.locale_field(locale, "default").unwrap_or("latn");
    let nu: &'static str = match parsed.nu.as_deref() {
        Some("native") => t.locale_field(locale, "native").unwrap_or(default),
        Some(n) => t
            .digits
            .get_key_value(n)
            .map(|(k, _)| *k)
            .or((n == "latn").then_some("latn"))
            .unwrap_or(default),
        None => default,
    };
    let system = if t.has_system(locale, nu) { nu } else { "latn" };
    let digits = if nu == "latn" {
        None
    } else {
        Some(
            t.digits
                .get(nu)
                .map(AsRef::as_ref)
                .ok_or_else(|| Error::Missing {
                    locale: locale.to_owned(),
                    system: nu.to_owned(),
                    field: "digits",
                })?,
        )
    };
    let min = t.locale_field(locale, "min-grouping").unwrap_or("1");
    let minimum_grouping_digits = min.parse().map_err(|_| Error::Table {
        line: 0,
        message: format!("{locale}: min-grouping {min:?}"),
    })?;
    let mut pats = BTreeMap::new();
    for style in Style::ALL {
        if let Some(p) = t.system_field(locale, system, style_field(style)) {
            pats.insert(style, p);
        }
    }
    Ok(NumberData {
        locale,
        numbering_system: nu,
        symbols_system: system,
        digits,
        minimum_grouping_digits,
        decimal: field(t, locale, system, "decimal")?,
        group: field(t, locale, system, "group")?,
        minus: field(t, locale, system, "minus")?,
        plus: field(t, locale, system, "plus")?,
        percent: field(t, locale, system, "percent")?,
        decimal_pattern: field(t, locale, system, "decimal-pattern")?,
        patterns: pats,
    })
}

impl NumberData {
    /// The `number.symbols` payload (§4.2).
    pub fn symbols_entry(&self) -> Result<Vec<u8>, Error> {
        let grouping = pattern::parse(self.decimal_pattern)?.grouping;
        Ok(symbols(&SymbolsSpec {
            grouping,
            minimum_grouping_digits: self.minimum_grouping_digits,
            decimal: self.decimal,
            group: self.group,
            minus: self.minus,
            plus: self.plus,
            percent: self.percent,
            digits: self.digits,
        })?)
    }

    /// The `number.patterns` payload (§4.3) for `styles` (a style CLDR lacks
    /// for this locale — only ever an `…Alpha` variant — is left out; the
    /// reader falls back to its base).
    pub fn patterns_entry(&self, styles: &[Style]) -> Result<Vec<u8>, Error> {
        let mut parsed = Vec::new();
        for style in styles {
            if let Some(p) = self.patterns.get(style) {
                parsed.push((*style, pattern::parse(p)?));
            }
        }
        let specs: Vec<_> = parsed.iter().map(|(s, p)| (*s, p.spec())).collect();
        Ok(patterns(&specs)?)
    }
}

/// The number LOCALE entries for `tag` and `needs`, as
/// `mf2_catalog::writer::Options::locale_entries` takes them: `number.symbols`
/// when any number is formatted, `number.patterns` when a style is needed;
/// nothing when `needs` needs nothing.
pub fn number_locale_entries(tag: &str, needs: &NumberNeeds) -> Result<Vec<(u32, Vec<u8>)>, Error> {
    if !needs.any() {
        return Ok(Vec::new());
    }
    let data = number_data(tag)?;
    let mut out = vec![(locale_key::NUMBER_SYMBOLS, data.symbols_entry()?)];
    let styles = needs.styles();
    if !styles.is_empty() {
        out.push((locale_key::NUMBER_PATTERNS, data.patterns_entry(&styles)?));
    }
    Ok(out)
}

/// Every CLDR locale in the number table, bytewise ascending (`und` is root).
pub fn number_locales() -> Result<Vec<&'static str>, Error> {
    Ok(table()?.locales.keys().copied().collect())
}
