[package]
name = "p10-links-both"
version = "0.0.0"
edition = "2024"
license = "MIT"
publish = false

[dependencies]
mf2 = { package = "p10-links-mf2", path = "../../mf2", features = ["hydrate"] }

[build-dependencies]
mf2 = { package = "p10-links-mf2", path = "../../mf2", features = ["native", "compile"] }
mf2-build = { package = "p10-links-mf2-build", path = "../../mf2-build" }
