//! Reference-workload app (generated by workload-gen; do not edit).
//! Template: `tr`.

#![recursion_limit = "512"]
#![allow(unused, clippy::all, clippy::pedantic)]

pub mod app;
pub mod components;
pub mod support;
pub mod tables;
pub mod widgets;

/// Client entry point; `hydrate_lazy` supports `#[lazy_route]` chunks under
/// `cargo leptos build --split`.
#[cfg(feature = "hydrate")]
#[wasm_bindgen::prelude::wasm_bindgen]
pub fn hydrate() {
    crate::support::boot();
    leptos::mount::hydrate_lazy(app::App);
}
