//! Deferred labels: one `static` table per component (generated by
//! workload-gen; do not edit).

use leptos::prelude::*;
use p09_i18n::tr;

/// One row of a deferred-label table.
pub struct Row {
    /// Row key.
    pub key: &'static str,
    /// The label, in the template's deferred type.
    pub label: p09_i18n::__mf2::Tr,
}

pub static T000: &[Row] = &[
    Row { key: "k0", label: tr!("auth.banner.hint-settings-open-body") },
    Row { key: "k1", label: tr!("chat.labels.code-subscription") },
];

pub static T001: &[Row] = &[
    Row { key: "k0", label: tr!("chat.upload.workspace") },
    Row { key: "k1", label: tr!("chat.menu.quote") },
];

pub static T002: &[Row] = &[
    Row { key: "k0", label: tr!("errors.labels.title") },
];

pub static T003: &[Row] = &[
    Row { key: "k0", label: tr!("admin.tips.report-invite") },
    Row { key: "k1", label: tr!("billing.roles.password") },
    Row { key: "k2", label: tr!("app.security.bot") },
];

pub static T004: &[Row] = &[
    Row { key: "k0", label: tr!("admin.done-share-mode-public-header") },
    Row { key: "k1", label: tr!("moderation.confirm.no") },
    Row { key: "k2", label: tr!("auth.banner.sort-all-filter") },
    Row { key: "k3", label: tr!("settings.empty.online-joined") },
];

pub static T005: &[Row] = &[
    Row { key: "k0", label: tr!("admin.modal.failed-result") },
];

pub static T006: &[Row] = &[
    Row { key: "k0", label: tr!("moderation.form.info-mode-error") },
    Row { key: "k1", label: tr!("admin.input.close") },
];

pub static T007: &[Row] = &[
    Row { key: "k0", label: tr!("auth.list.profile-empty-typing-upload") },
    Row { key: "k1", label: tr!("billing.participant") },
    Row { key: "k2", label: tr!("common.list.on") },
];

pub static T009: &[Row] = &[
    Row { key: "k0", label: tr!("search.list.warning") },
];

pub static T010: &[Row] = &[
    Row { key: "k0", label: tr!("hotkeys.ok") },
    Row { key: "k1", label: tr!("rooms.limits.invite-workspace") },
    Row { key: "k2", label: tr!("hotkeys.confirm.no") },
    Row { key: "k3", label: tr!("commands.table.less-volume-ok") },
];

pub static T011: &[Row] = &[
    Row { key: "k0", label: tr!("hotkeys.confirm.badge-confirmation") },
];

pub static T012: &[Row] = &[
    Row { key: "k0", label: tr!("errors.labels.offline-delete") },
    Row { key: "k1", label: tr!("commands.prompts.on") },
    Row { key: "k2", label: tr!("search.limit-badge") },
    Row { key: "k3", label: tr!("search.account.failed-device") },
    Row { key: "k4", label: tr!("errors.all-result-upload") },
];

pub static T013: &[Row] = &[
    Row { key: "k0", label: tr!("commands.video.join") },
    Row { key: "k1", label: tr!("admin.input.edit-bot-away-info-busy") },
];

pub static T014: &[Row] = &[
    Row { key: "k0", label: tr!("search.account.send") },
    Row { key: "k1", label: tr!("search.account.failed") },
    Row { key: "k2", label: tr!("onboarding.invite") },
];

pub static T015: &[Row] = &[
    Row { key: "k0", label: tr!("rooms.limits.unread-moderator") },
];

pub static T016: &[Row] = &[
    Row { key: "k0", label: tr!("chat.upload.icon-id") },
];

pub static T017: &[Row] = &[
    Row { key: "k0", label: tr!("errors.labels.offline-delete") },
];

pub static T018: &[Row] = &[
    Row { key: "k0", label: tr!("settings.audio.ok") },
    Row { key: "k1", label: tr!("errors.upload.input") },
];

pub static T019: &[Row] = &[
    Row { key: "k0", label: tr!("notifications.theme") },
    Row { key: "k1", label: tr!("chat.prompts.size") },
    Row { key: "k2", label: tr!("admin.reply-notice-permissions") },
    Row { key: "k3", label: tr!("settings.account.id") },
];

pub static T020: &[Row] = &[
    Row { key: "k0", label: tr!("commands.invites.character") },
    Row { key: "k1", label: tr!("rooms.sidebar.view-by") },
];

pub static T021: &[Row] = &[
    Row { key: "k0", label: tr!("auth.upload.hint-background") },
    Row { key: "k1", label: tr!("settings.labels.tag") },
];

pub static T022: &[Row] = &[
    Row { key: "k0", label: tr!("commands.prompts.id-code") },
    Row { key: "k1", label: tr!("app.toolbar.link-add") },
    Row { key: "k2", label: tr!("errors.form.results") },
];

pub static T023: &[Row] = &[
    Row { key: "k0", label: tr!("commands.invites.text-mode-badge-list-hide") },
    Row { key: "k1", label: tr!("language-user-report") },
    Row { key: "k2", label: tr!("settings.audio.joined") },
    Row { key: "k3", label: tr!("profile.security.channel-admin-attachment") },
];

pub static T024: &[Row] = &[
    Row { key: "k0", label: tr!("profile.input.tag-text") },
    Row { key: "k1", label: tr!("commands.invites.moderator") },
    Row { key: "k2", label: tr!("errors.video.public") },
];

pub static T025: &[Row] = &[
    Row { key: "k0", label: tr!("media.prompts.room-add") },
    Row { key: "k1", label: tr!("commands.video.joined") },
];

pub static T026: &[Row] = &[
    Row { key: "k0", label: tr!("settings-camera-footer") },
    Row { key: "k1", label: tr!("commands.form.avatar") },
    Row { key: "k2", label: tr!("moderation.drafts.up") },
    Row { key: "k3", label: tr!("chat.prompts.menu-upload") },
];

pub static T027: &[Row] = &[
    Row { key: "k0", label: tr!("chat.prompts.error-to") },
    Row { key: "k1", label: tr!("auth.upload.help-command-screen") },
    Row { key: "k2", label: tr!("media.labels.tab-tab") },
    Row { key: "k3", label: tr!("search.code-done-new-input-slow-input") },
    Row { key: "k4", label: tr!("settings.toolbar.by") },
    Row { key: "k5", label: tr!("media.tabs.mute-menu-input") },
];

pub static T028: &[Row] = &[
    Row { key: "k0", label: tr!("auth.audio.delete-channel-of") },
    Row { key: "k1", label: tr!("rooms.limits.workspace") },
    Row { key: "k2", label: tr!("app.roles.position-add") },
    Row { key: "k3", label: tr!("billing.member-loading-menu-incoming-emoji") },
    Row { key: "k4", label: tr!("app.form.available-microphone") },
    Row { key: "k5", label: tr!("rooms.limits.unread-moderator") },
];

pub static T029: &[Row] = &[
    Row { key: "k0", label: tr!("moderation.total-reply") },
    Row { key: "k1", label: tr!("moderation.confirm.activity-of") },
    Row { key: "k2", label: tr!("errors.toolbar.limit-subscription") },
];

pub static T030: &[Row] = &[
    Row { key: "k0", label: tr!("admin.labels.up") },
    Row { key: "k1", label: tr!("rooms.dialog.ok-enable-upload") },
    Row { key: "k2", label: tr!("moderation.members.to") },
    Row { key: "k3", label: tr!("rooms.user-token-react-text") },
];

pub static T031: &[Row] = &[
    Row { key: "k0", label: tr!("onboarding.list-public-mode-badge") },
];

pub static T032: &[Row] = &[
    Row { key: "k0", label: tr!("hotkeys.sound-body") },
    Row { key: "k1", label: tr!("admin.badges.read-no") },
];

pub static T033: &[Row] = &[
    Row { key: "k0", label: tr!("errors.form.row") },
    Row { key: "k1", label: tr!("settings.labels.tab") },
    Row { key: "k2", label: tr!("commands.table.react-language") },
    Row { key: "k3", label: tr!("chat.table.close-video") },
];

pub static T034: &[Row] = &[
    Row { key: "k0", label: tr!("notifications.prompts.ok") },
    Row { key: "k1", label: tr!("media.labels.unknown-invite") },
    Row { key: "k2", label: tr!("commands.invites.character") },
];

pub static T035: &[Row] = &[
    Row { key: "k0", label: tr!("chat.upload.notification") },
    Row { key: "k1", label: tr!("guest-by-share-error") },
    Row { key: "k2", label: tr!("common.list.label-character") },
    Row { key: "k3", label: tr!("auth.banner.code-role-usage") },
];

pub static T036: &[Row] = &[
    Row { key: "k0", label: tr!("settings.audio.on") },
    Row { key: "k1", label: tr!("billing.roles.on") },
];

pub static T037: &[Row] = &[
    Row { key: "k0", label: tr!("admin.input.header-dialog-title-no") },
    Row { key: "k1", label: tr!("chat.errors.sent") },
];

pub static T038: &[Row] = &[
    Row { key: "k0", label: tr!("onboarding.confirm.character") },
    Row { key: "k1", label: tr!("common.invites.disabled-invite") },
    Row { key: "k2", label: tr!("chat.prompts.size") },
];

pub static T039: &[Row] = &[
    Row { key: "k0", label: tr!("auth.banner.status-bot") },
    Row { key: "k1", label: tr!("rooms.limits.character") },
    Row { key: "k2", label: tr!("auth.delete-preferences") },
    Row { key: "k3", label: tr!("commands.banner.footer-moderator") },
];

pub static T040: &[Row] = &[
    Row { key: "k0", label: tr!("media.prompts.unknown-help") },
    Row { key: "k1", label: tr!("profile.table.off") },
    Row { key: "k2", label: tr!("admin.labels.private-keyboard") },
    Row { key: "k3", label: tr!("settings.account.row") },
];

pub static T041: &[Row] = &[
    Row { key: "k0", label: tr!("commands.table.guest") },
    Row { key: "k1", label: tr!("settings-camera-footer") },
];

pub static T042: &[Row] = &[
    Row { key: "k0", label: tr!("admin.tips.footer-mode-send") },
];

pub static T043: &[Row] = &[
    Row { key: "k0", label: tr!("notifications.form.up-2") },
    Row { key: "k1", label: tr!("app.input.limit") },
    Row { key: "k2", label: tr!("profile.copy-header-copy-busy") },
];

pub static T044: &[Row] = &[
    Row { key: "k0", label: tr!("common.toolbar.read") },
    Row { key: "k1", label: tr!("commands.video.up") },
];

pub static T045: &[Row] = &[
    Row { key: "k0", label: tr!("profile.input.token") },
    Row { key: "k1", label: tr!("notifications.footer.on") },
];

pub static T046: &[Row] = &[
    Row { key: "k0", label: tr!("errors.language-moderation") },
];

pub static T047: &[Row] = &[
    Row { key: "k0", label: tr!("moderation.drafts.success") },
    Row { key: "k1", label: tr!("auth.upload.kick-upload-sort-ban") },
    Row { key: "k2", label: tr!("app.empty.mode-by-plan-result-url-read") },
];

pub static T048: &[Row] = &[
    Row { key: "k0", label: tr!("settings.dialog.id") },
    Row { key: "k1", label: tr!("profile.input.emoji-by") },
];

pub static T049: &[Row] = &[
    Row { key: "k0", label: tr!("settings.toolbar.no") },
    Row { key: "k1", label: tr!("media.prompts.unknown-required-available") },
    Row { key: "k2", label: tr!("rooms.modal.send-kick-banner") },
];

pub static T050: &[Row] = &[
    Row { key: "k0", label: tr!("billing.invites.online-menu-filter-bot") },
    Row { key: "k1", label: tr!("profile.input.disabled-button") },
    Row { key: "k2", label: tr!("rooms.device-notification") },
    Row { key: "k3", label: tr!("errors.upload.ok") },
    Row { key: "k4", label: tr!("commands.dialog.ok") },
];

pub static T051: &[Row] = &[
    Row { key: "k0", label: tr!("commands.form.admin-language-name-no") },
    Row { key: "k1", label: tr!("app.empty.failed") },
    Row { key: "k2", label: tr!("profile.input.on") },
];

pub static T052: &[Row] = &[
    Row { key: "k0", label: tr!("onboarding.confirm.user-done-guest-text") },
    Row { key: "k1", label: tr!("chat.badges.icon") },
];

pub static T053: &[Row] = &[
    Row { key: "k0", label: tr!("search.account.action") },
    Row { key: "k1", label: tr!("settings.dialog.member-notice") },
    Row { key: "k2", label: tr!("commands.invites.keyboard-failed-volume") },
    Row { key: "k3", label: tr!("billing.roles.apply-text") },
];

pub static T054: &[Row] = &[
    Row { key: "k0", label: tr!("app.status-avatar") },
    Row { key: "k1", label: tr!("commands.dialog.up") },
    Row { key: "k2", label: tr!("media.drafts.invite-thread-public") },
    Row { key: "k3", label: tr!("chat.prompts.name") },
];

pub static T055: &[Row] = &[
    Row { key: "k0", label: tr!("chat.modal.channel-header") },
];

pub static T056: &[Row] = &[
    Row { key: "k0", label: tr!("auth.actions.id") },
    Row { key: "k1", label: tr!("activity-available") },
    Row { key: "k2", label: tr!("errors.form.no") },
];

pub static T057: &[Row] = &[
    Row { key: "k0", label: tr!("settings.drafts.by") },
    Row { key: "k1", label: tr!("errors.row-voice-required") },
    Row { key: "k2", label: tr!("auth.recording-command") },
    Row { key: "k3", label: tr!("settings.toolbar.up") },
];

pub static T058: &[Row] = &[
    Row { key: "k0", label: tr!("common.dialog.keyboard") },
];

pub static T059: &[Row] = &[
    Row { key: "k0", label: tr!("errors.history.download-report") },
    Row { key: "k1", label: tr!("auth.banner.required-failed-private-read") },
    Row { key: "k2", label: tr!("errors.toolbar.item-top") },
];

