//! Shared widgets and plain argument values (generated by workload-gen).

use leptos::prelude::*;

const NAMES: [&str; 4] = ["Ada", "Lin", "Sam", "Kai"];
const TIMES: [&str; 2] = ["2026-09-20T12:00:00", "2026-01-02T08:30:00"];

/// A plain string argument value, chosen at run time.
pub fn pick_name(n: i64) -> &'static str {
    NAMES[(n.unsigned_abs() % 4) as usize]
}

/// A plain date/time argument value, chosen at run time.
pub fn pick_time(n: i64) -> &'static str {
    TIMES[(n.unsigned_abs() % 2) as usize]
}

/// Reactive text through `TextProp`.
#[component]
pub fn TextLabel(#[prop(into)] text: TextProp) -> impl IntoView {
    view! { <span class="label">{move || text.get()}</span> }
}

/// Reactive text through `Signal<String>`.
#[component]
pub fn SignalHint(#[prop(into)] text: Signal<String>) -> impl IntoView {
    view! { <small class="hint">{text}</small> }
}

/// Plain `String` text.
#[component]
pub fn StringBadge(#[prop(into)] text: String) -> impl IntoView {
    view! { <span class="badge">{text}</span> }
}
