[package]
name = "proto"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
leptos = { version = "=0.8.20" }
wasm-bindgen = "0.2"

[features]
ssr = ["leptos/ssr"]
hydrate = ["leptos/hydrate"]
v_base = []
v_tr = []
v_closure = []
v_signal = []
v_attr_base = []
v_attr_tr = []
v_attr_closure = []

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[workspace]
