//! Component C008 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::tr0;

fn s008_0(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("hotkeys.confirm.url-off", reason = who).to_string(),
        1 => tr0!("settings.form.pin-fast", remaining = n).to_string(),
        _ => tr0!("commands.video.position", language = who, reason = who).to_string(),
    }
}

fn s008_1(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("common.invites.dialog-react").to_string(),
        1 => tr0!("profile.audio.new-tag").to_string(),
        _ => tr0!("profile.security.thread-of").to_string(),
    }
}

fn s008_3(n: i64, who: &'static str, when: &'static str) -> String {
    tr0!("moderation.confirm.attachment").to_string()
}

fn s008_4(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("common.toolbar.bot-add").to_string(),
        1 => tr0!("chat.menu.avatar").to_string(),
        _ => tr0!("rooms.modal.thread-menu-id").to_string(),
    }
}

#[component]
pub fn C008() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{move || s008_0(count.get(), who, when)}</p>
                <p>{tr0!("settings.attachment-icon-report", hours = n)}</p>
                <p>{tr0!("app.form.header-button", percent = n)}</p>
                <SignalHint text={Signal::derive(move || tr0!("common.roles.failed-joined", amount = count, topic = name).to_string())}/>
                <p>{tr0!("search.list.notice-plan", minutes = n)}</p>
                <TextLabel text={move || tr0!("admin.modal.room-status-input-show", title = name.get()).to_string()}/>
                <p>{tr0!("auth.upload.unavailable")}</p>
                <p>{move || s008_1(count.get(), who, when)}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <StringBadge text={tr0!("profile.input.dialog-join-off")}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr0!("chat.badges.no").to_string(), _ => tr0!("common.list.moderator-input-kick-pin").to_string(), });
                }>{tr0!("settings.panel.less-row")}</button>
                <p>{s008_3(n, who, when)}</p>
                <p>{move || s008_4(count.get(), who, when)}</p>
                <SignalHint text={tr0!("settings.footer-hide-by")}/>
                <p>{move || if flag.get() { tr0!("media.drafts.actions-settings") } else { tr0!("hotkeys.confirm.by") }}</p>
                <input type="text" aria-label={tr0!("auth.upload.bot")} placeholder={tr0!("notifications.footer.on-2")}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr0!("rooms.filter-avatar").to_string(), _ => tr0!("profile.input.tag-text").to_string(), });
                }>{tr0!("hotkeys.confirm.badge")}</button>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <StringBadge text={tr0!("moderation.members.tag")}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr0!("profile.security.ok").to_string(), 1 => tr0!("auth.recording-command").to_string(), _ => tr0!("media.prompts.title-notice-body").to_string(), });
                }>{tr0!("help.recording")}</button>
                <StringBadge text={tr0!("billing.upload-time-unread")}/>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 8">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
