//! Component C011 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::tr0;

fn s011_1(n: i64, who: &'static str, when: &'static str) -> String {
    tr0!("settings.account.ban", channel = who).to_string()
}

fn s011_4(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("hotkeys.confirm.id").to_string(),
        1 => tr0!("chat.members.send-away").to_string(),
        _ => tr0!("errors.list.to").to_string(),
    }
}

fn s011_5(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("chat.banner.size-close").to_string(),
        1 => tr0!("media.tabs.unread-member").to_string(),
        _ => tr0!("chat.members.kick").to_string(),
    }
}

#[component]
pub fn C011() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <ul class="table" title={crate::tables::T011[0].label.to_string()}>
                    {crate::tables::T011.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <p>{move || tr0!("commands.prompts.badge-of", user = name.get())}</p>
                <p>{move || tr0!("hotkeys.confirm.hide", reason = name)}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr0!("onboarding.confirm.security-tab", limit = n, tag = who).to_string(), _ => tr0!("settings.dialog.on", count = n).to_string(), });
                }>{tr0!("chat.modal.hint-code-sort-retry")}</button>
                <p>{s011_1(n, who, when)}</p>
                <SignalHint text={Signal::derive(move || tr0!("admin.labels.ban-owner", host = name.get()).to_string())}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr0!("chat.private-network", name = who, user = who).to_string());
                }>{tr0!("moderation.drafts.success")}</button>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr0!("profile.audio.header-microphone").to_string(), _ => tr0!("search.result-cancel").to_string(), });
                }>{tr0!("media.prompts.to-avatar-screen-private")}</button>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr0!("media.drafts.close-password-to")}</p>
                <p>{move || if flag.get() { tr0!("search.topic-unread-of-unread-result") } else { tr0!("errors.banner.total-to") }}</p>
                <p>{tr0!("chat.errors.hint-typing")}</p>
                <p>{tr0!("settings.audio.cancel")}</p>
                <p>{tr0!("settings.panel.read")}</p>
                <p>{tr0!("media.prompts.open-off")}</p>
                <p>{move || s011_4(count.get(), who, when)}</p>
                <input type="text" aria-label={tr0!("admin.input.total-footer-member")} placeholder={tr0!("app.hint-incoming-row")}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr0!("billing.invites.file-microphone")}</p>
                <p>{tr0!("onboarding.form.subscription")}</p>
                <p>{move || s011_5(count.get(), who, when)}</p>
                <p>{tr0!("rooms.token-done-banner-device")}</p>
                <StringBadge text={tr0!("onboarding.confirm.workspace")}/>
                <StringBadge text={tr0!("chat.confirm.error")}/>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 11">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
