//! Component C014 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::tr0;

fn s014_0(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("notifications.prompts.of", device = who, file_name = who).to_string(),
        1 => tr0!("commands.prompts.by", file_name = who, percent = n).to_string(),
        _ => tr0!("rooms.upload-level-level-notice", language = who, total = n).to_string(),
    }
}

fn s014_1(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("commands.banner.position").to_string(),
        1 => tr0!("settings.level-reset-row-camera-search").to_string(),
        _ => tr0!("settings.dialog.id-profile").to_string(),
    }
}

fn s014_4(n: i64, who: &'static str, when: &'static str) -> String {
    tr0!("errors.upload.open-id").to_string()
}

fn s014_5(n: i64, who: &'static str, when: &'static str) -> String {
    tr0!("notifications.footer.of-3").to_string()
}

fn s014_6(n: i64, who: &'static str, when: &'static str) -> String {
    tr0!("common.roles.date").to_string()
}

#[component]
pub fn C014() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{tr0!("moderation.form.plan-ban", email = who)}</p>
                <p>{move || s014_0(count.get(), who, when)}</p>
                <p>{move || if flag.get() { tr0!("commands.video.camera-invite", item = who) } else { tr0!("hotkeys.list.theme-tag", role = who) }}</p>
                <p>{move || tr0!("onboarding.form.warning", device = name, remaining = count)}</p>
                <SignalHint text={Signal::derive(move || tr0!("admin.role-owner-enable-banner", pages = count).to_string())}/>
                <p>{move || if flag.get() { tr0!("common.labels.ok", channel = who, plan = who) } else { tr0!("common.invites.footer-invitation", days = n) }}</p>
                <p>{move || s014_1(count.get(), who, when)}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr0!("common.dialog.keyboard-invitation").to_string(), _ => tr0!("errors.form.date-bot-invitation").to_string(), });
                }>{tr0!("rooms.network-action")}</button>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr0!("settings.labels.id")}</p>
                <ul class="table" title={crate::tables::T014[0].label.to_string()}>
                    {crate::tables::T014.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <p>{tr0!("auth.upload.thread-row")}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr0!("common.roles.disabled-add").to_string());
                }>{tr0!("notifications.on")}</button>
                <SignalHint text={tr0!("chat.quality-session")}/>
                <p>{s014_4(n, who, when)}</p>
                <p>{tr0!("profile.audio.public-share-to")}</p>
                <input type="text" aria-label={tr0!("chat.banner.joined")} placeholder={tr0!("chat.top-profile")}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr0!("chat.banner.enable")}</p>
                <p>{s014_5(n, who, when)}</p>
                <input type="text" aria-label={tr0!("auth.audio.download")} placeholder={tr0!("commands.banner.id-success")}/>
                <StringBadge text={tr0!("auth.upload.help-command-screen")}/>
                <p>{s014_6(n, who, when)}</p>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 14">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
