//! Component C018 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::tr0;

fn s018_0(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("settings.errors.icon-apply", index = n).to_string(),
        1 => tr0!("rooms.tooltip-unread").to_string(),
        _ => tr0!("chat.table.no").to_string(),
    }
}

fn s018_1(n: i64, who: &'static str, when: &'static str) -> String {
    tr0!("moderation.form.url").to_string()
}

fn s018_2(n: i64, who: &'static str, when: &'static str) -> String {
    tr0!("moderation.form.view-missing").to_string()
}

fn s018_4(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("chat.prompts.filter-tooltip").to_string(),
        1 => tr0!("moderation.profile-security").to_string(),
        _ => tr0!("settings.name").to_string(),
    }
}

fn s018_5(n: i64, who: &'static str, when: &'static str) -> String {
    tr0!("errors.toolbar.avatar").to_string()
}

fn s018_6(n: i64, who: &'static str, when: &'static str) -> String {
    tr0!("rooms.limits.members-no").to_string()
}

fn s018_7(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("errors.banner.mode-plan-actions").to_string(),
        1 => tr0!("profile.incoming-moderator").to_string(),
        _ => tr0!("chat.banner.list-upload-read-bot").to_string(),
    }
}

#[component]
pub fn C018() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{move || tr0!("help.audio.count-reply-owner-ban", members = count.get(), tag = name.get(), title = name.get())}</p>
                <p>{tr0!("commands.banner.avatar-url", level = n)}</p>
                <input type="text" aria-label={move || tr0!("admin.modal.body", topic = name)} placeholder={tr0!("app.form.shortcut-pin")}/>
                <p>{move || s018_0(count.get(), who, when)}</p>
                <ul class="table" title={crate::tables::T018[0].label.to_string()}>
                    {crate::tables::T018.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <p>{move || tr0!("errors.history.delete-thread", max_size = count)}</p>
                <p>{tr0!("profile.security.loading-up", email = who)}</p>
                <TextLabel text={move || tr0!("media.drafts.body-of", command = name).to_string()}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <StringBadge text={tr0!("media.prompts.count-settings-audio")}/>
                <p>{s018_1(n, who, when)}</p>
                <p>{s018_2(n, who, when)}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr0!("admin.modal.view-text-topic").to_string(), _ => tr0!("chat.badges.permissions").to_string(), });
                }>{tr0!("moderation.form.info-mode-error")}</button>
                <p>{move || s018_4(count.get(), who, when)}</p>
                <TextLabel text={tr0!("moderation.privacy.volume")}/>
                <TextLabel text={tr0!("billing.profile-notification")}/>
                <input type="text" aria-label={tr0!("commands.prompts.to")}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{s018_5(n, who, when)}</p>
                <p>{tr0!("hotkeys.mode-delete-menu-voice")}</p>
                <p>{s018_6(n, who, when)}</p>
                <StringBadge text={tr0!("settings.dialog.text-add")}/>
                <p>{tr0!("errors.form.row")}</p>
                <p>{move || s018_7(count.get(), who, when)}</p>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 18">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
