//! Component C020 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::tr0;

fn s020_0(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("help.audio.of-visibility-add", tag = who).to_string(),
        1 => tr0!("hotkeys.id", members = n).to_string(),
        _ => tr0!("common.toolbar.bot", channel = who).to_string(),
    }
}

fn s020_1(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("admin.modal.sent-private-ok", percent = n, sender = who).to_string(),
        1 => tr0!("chat.labels.tag", minutes = n).to_string(),
        _ => tr0!("chat.modal.email-react-by", size = n).to_string(),
    }
}

fn s020_3(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("commands.prompts.reset").to_string(),
        1 => tr0!("auth.list.device").to_string(),
        _ => tr0!("errors.toolbar.recording").to_string(),
    }
}

#[component]
pub fn C020() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{move || s020_0(count.get(), who, when)}</p>
                <TextLabel text={move || tr0!("errors.history.preferences", pages = count).to_string()}/>
                <p>{move || tr0!("errors.toolbar.ok", count = count.get())}</p>
                <p>{move || s020_1(count.get(), who, when)}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr0!("away-error-keyboard").to_string(), 1 => tr0!("app.form.leave-save-confirmation").to_string(), _ => tr0!("chat.members.no").to_string(), });
                }>{tr0!("profile.audio.by-footer")}</button>
                <p>{tr0!("common.toolbar.share")}</p>
                <ul class="table" title={crate::tables::T020[0].label.to_string()}>
                    {crate::tables::T020.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <SignalHint text={tr0!("chat.members.retry-camera-date-of")}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr0!("settings.panel.ok")}</p>
                <p>{tr0!("rooms.modal.apply-id")}</p>
                <SignalHint text={tr0!("rooms.dialog.by")}/>
                <p>{move || s020_3(count.get(), who, when)}</p>
                <p>{move || if flag.get() { tr0!("chat.labels.notification") } else { tr0!("app.input.typing-enable") }}</p>
                <p>{tr0!("common.list.no")}</p>
                <p>{tr0!("commands.notification")}</p>
                <input type="text" aria-label={tr0!("commands.invites.title")}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{move || if flag.get() { tr0!("rooms.modal.user-sort-online-all") } else { tr0!("common.roles.body-actions") }}</p>
                <TextLabel text={tr0!("settings.audio.ok")}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr0!("app.unavailable").to_string(), 1 => tr0!("common.invites.dialog-react").to_string(), _ => tr0!("chat.labels.activity-level").to_string(), });
                }>{tr0!("settings.up")}</button>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 20">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
