//! Component C021 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::tr0;

fn s021_0(n: i64, who: &'static str, when: &'static str) -> String {
    tr0!("settings.labels.thread", tag = who).to_string()
}

fn s021_3(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("common.toolbar.page-screen", members = n).to_string(),
        1 => tr0!("rooms.limits.edit-size", tag = who).to_string(),
        _ => tr0!("errors.form.quality-tooltip").to_string(),
    }
}

fn s021_4(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("commands.account.share-apply").to_string(),
        1 => tr0!("chat.labels.icon-more").to_string(),
        _ => tr0!("app.input.id").to_string(),
    }
}

fn s021_5(n: i64, who: &'static str, when: &'static str) -> String {
    tr0!("auth.form.report-delete").to_string()
}

fn s021_6(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("chat.errors.channel-report").to_string(),
        1 => tr0!("rooms.limits.workspace").to_string(),
        _ => tr0!("settings.account.view").to_string(),
    }
}

#[component]
pub fn C021() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{move || if flag.get() { tr0!("onboarding.form.unavailable", limit = n, page = n) } else { tr0!("admin.labels.ban-owner", host = who) }}</p>
                <p>{move || tr0!("auth.banner.permissions", reason = name.get())}</p>
                <p>{s021_0(n, who, when)}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr0!("errors.list.report-error-device-cancel", amount = n, target = who).to_string());
                }>{tr0!("help.recording")}</button>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr0!("media.labels.tag-url", room = who).to_string(), _ => tr0!("rooms.dialog.apply-id", file_name = who).to_string(), });
                }>{tr0!("media.tabs.unread-delete")}</button>
                <p>{move || s021_3(count.get(), who, when)}</p>
                <input type="text" aria-label={tr0!("rooms.sidebar.confirm-sound-plan")} placeholder={tr0!("commands.form.to")}/>
                <p>{move || s021_4(count.get(), who, when)}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr0!("chat.table.by")}</p>
                <ul class="table" title={crate::tables::T021[0].label.to_string()}>
                    {crate::tables::T021.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <TextLabel text={tr0!("admin.upload-dialog")}/>
                <p>{tr0!("notifications.apply")}</p>
                <p>{tr0!("hotkeys.confirm.workspace")}</p>
                <p>{move || if flag.get() { tr0!("errors.upload.enable") } else { tr0!("onboarding.confirm.header") }}</p>
                <p>{s021_5(n, who, when)}</p>
                <p>{tr0!("errors.history.thread-speaker-slow-footer")}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <StringBadge text={tr0!("moderation.drafts.admin")}/>
                <p>{tr0!("settings.account.of")}</p>
                <p>{move || s021_6(count.get(), who, when)}</p>
                <input type="text" aria-label={tr0!("profile.audio.header-microphone")}/>
                <p>{move || if flag.get() { tr0!("chat.menu.role-available-title-preferences") } else { tr0!("profile.input.dialog-join-off") }}</p>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 21">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
