//! Component C023 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::tr0;

fn s023_0(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("media.prompts.member-online", size = n).to_string(),
        1 => tr0!("moderation.header.no", count = n).to_string(),
        _ => tr0!("search.list.available-volume").to_string(),
    }
}

fn s023_1(n: i64, who: &'static str, when: &'static str) -> String {
    tr0!("help.audio.up").to_string()
}

fn s023_2(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("media.prompts.camera").to_string(),
        1 => tr0!("commands.table.id").to_string(),
        _ => tr0!("auth.sidebar.ok").to_string(),
    }
}

fn s023_3(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("help.audio.title-usage-id").to_string(),
        1 => tr0!("search.typing-limit-off-reply").to_string(),
        _ => tr0!("search.disabled-id").to_string(),
    }
}

fn s023_4(n: i64, who: &'static str, when: &'static str) -> String {
    tr0!("settings.labels.owner").to_string()
}

fn s023_5(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("commands.video.join").to_string(),
        1 => tr0!("media.drafts.close-password-to").to_string(),
        _ => tr0!("commands.form.next-placeholder").to_string(),
    }
}

fn s023_6(n: i64, who: &'static str, when: &'static str) -> String {
    tr0!("rooms.empty.invite").to_string()
}

#[component]
pub fn C023() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{tr0!("media.labels.expired-joined", hours = n, language = who)}</p>
                <SignalHint text={tr0!("common.invites.footer-invitation", days = n)}/>
                <p>{move || s023_0(count.get(), who, when)}</p>
                <SignalHint text={Signal::derive(move || tr0!("commands.prompts.profile-next-row-video", command = name, device = name).to_string())}/>
                <p>{move || tr0!("rooms.dialog.thread-filter-invite", query = name.get())}</p>
                <p>{move || tr0!("common.upload.error", role = name.get())}</p>
                <SignalHint text={tr0!("profile.input.device-ok-count-label", item = who)}/>
                <ul class="table" title={crate::tables::T023[0].label.to_string()}>
                    {crate::tables::T023.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <SignalHint text={tr0!("admin.tips.result")}/>
                <p>{s023_1(n, who, when)}</p>
                <p>{move || s023_2(count.get(), who, when)}</p>
                <p>{tr0!("chat.banner.result-public")}</p>
                <p>{tr0!("admin.badges.moderation")}</p>
                <p>{tr0!("rooms.limits.upload-react-prompt-join")}</p>
                <p>{move || s023_3(count.get(), who, when)}</p>
                <input type="text" aria-label={tr0!("admin.badges.bot-date")}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr0!("rooms.limits.of-fast-help-label")}</p>
                <p>{s023_4(n, who, when)}</p>
                <p>{tr0!("auth.actions.id")}</p>
                <p>{move || s023_5(count.get(), who, when)}</p>
                <p>{s023_6(n, who, when)}</p>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 23">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
