//! Component C024 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::tr0;

fn s024_1(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("errors.banner.tab-reply-avatar", index = n).to_string(),
        1 => tr0!("count-badge-date-moderation-more").to_string(),
        _ => tr0!("auth.form.text-tooltip").to_string(),
    }
}

fn s024_2(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("notifications.form.to-2").to_string(),
        1 => tr0!("limit-time-position-admin").to_string(),
        _ => tr0!("rooms.empty.moderation").to_string(),
    }
}

#[component]
pub fn C024() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr0!("rooms.upload-level-level-notice", language = who, total = n).to_string(), _ => tr0!("rooms.enable-emoji-hide-open", level = n).to_string(), });
                }>{tr0!("search.topic-unread-of-unread-result")}</button>
                <ul class="table" title={crate::tables::T024[0].label.to_string()}>
                    {crate::tables::T024.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <StringBadge text={tr0!("app.form.email-dialog-new", name = who)}/>
                <TextLabel text={move || tr0!("auth.upload.of", max_size = count.get()).to_string()}/>
                <p>{tr0!("errors.menu.share-of", query = who)}</p>
                <p>{move || s024_1(count.get(), who, when)}</p>
                <input type="text" aria-label={tr0!("commands.banner.footer-moderator")}/>
                <p>{tr0!("moderation.form.up")}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr0!("notifications.form.id-3")}</p>
                <p>{tr0!("commands.video.guest-ban")}</p>
                <p>{tr0!("chat.ok-filter-button")}</p>
                <p>{tr0!("billing.invites.results-url")}</p>
                <p>{move || if flag.get() { tr0!("auth.banner.required") } else { tr0!("chat.confirm.new") }}</p>
                <p>{tr0!("commands.edit-attachment")}</p>
                <p>{move || s024_2(count.get(), who, when)}</p>
                <StringBadge text={tr0!("hotkeys.up")}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <StringBadge text={tr0!("commands.table.menu-on")}/>
                <p>{tr0!("commands.prompts.notification")}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr0!("moderation.confirm.retry-leave").to_string(), _ => tr0!("commands.banner.position").to_string(), });
                }>{tr0!("admin.badges.up")}</button>
                <StringBadge text={tr0!("auth.actions.to")}/>
                <p>{tr0!("errors.history.download-report")}</p>
                <SignalHint text={tr0!("chat.errors.hint-typing")}/>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 24">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
