//! Component C025 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::tr0;

fn s025_2(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("rooms.dialog.of-user").to_string(),
        1 => tr0!("errors.toolbar.to").to_string(),
        _ => tr0!("chat.prompts.enable").to_string(),
    }
}

fn s025_4(n: i64, who: &'static str, when: &'static str) -> String {
    tr0!("hotkeys.ok").to_string()
}

#[component]
pub fn C025() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{move || tr0!("notifications.prompts.id", file_name = name, votes = count)}</p>
                <ul class="table" title={crate::tables::T025[0].label.to_string()}>
                    {crate::tables::T025.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr0!("settings.account.notice", count = n).to_string(), _ => tr0!("commands.prompts.back-to", page = n).to_string(), });
                }>{tr0!("media.drafts.recording")}</button>
                <p>{move || if flag.get() { tr0!("notifications.prompts.up-2", pages = n, role = who) } else { tr0!("auth.banner.participant", pages = n) }}</p>
                <p>{move || if flag.get() { tr0!("admin.modal.attachment", size = n) } else { tr0!("rooms.empty.on", level = n, max_size = n, reason = who) }}</p>
                <p>{move || tr0!("commands.video.failed-next-no", count = count)}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr0!("media.prompts.enable-leave-cancel-warning").to_string());
                }>{tr0!("settings.dialog.by")}</button>
                <SignalHint text={tr0!("icon-moderator-react")}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr0!("settings.confirm.workspace")}</p>
                <p>{move || s025_2(count.get(), who, when)}</p>
                <p>{tr0!("chat.menu.badge-new")}</p>
                <p>{tr0!("auth.actions.user")}</p>
                <SignalHint text={tr0!("billing.recording-title-input")}/>
                <SignalHint text={tr0!("rooms.modal.activity-thread-of")}/>
                <p>{tr0!("media.notification")}</p>
                <p>{tr0!("moderation.confirm.id")}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr0!("rooms.modal.error-add")}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr0!("commands.banner.connection").to_string(), _ => tr0!("chat.badges.typing-url-participant").to_string(), });
                }>{tr0!("help.audio.id")}</button>
                <TextLabel text={tr0!("errors.form.edit-all-actions")}/>
                <p>{s025_4(n, who, when)}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr0!("save-audio-leave-role-ban").to_string(), _ => tr0!("chat.modal.action-delete").to_string(), });
                }>{tr0!("chat.modal.fast-loading")}</button>
                <TextLabel text={tr0!("errors.banner.total-to")}/>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 25">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
