//! Component C027 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::tr0;

fn s027_1(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("media.tabs.tooltip-copy", count = n).to_string(),
        1 => tr0!("chat.upload.theme-hide-new", language = who).to_string(),
        _ => tr0!("errors.list.report-top", version = who).to_string(),
    }
}

fn s027_2(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("app.form.less-emoji-pin-preferences").to_string(),
        1 => tr0!("chat.banner.quality").to_string(),
        _ => tr0!("auth.form.device").to_string(),
    }
}

fn s027_4(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("billing.sidebar.row-tag").to_string(),
        1 => tr0!("commands.invites.id").to_string(),
        _ => tr0!("chat.errors.tab-name-footer-public").to_string(),
    }
}

fn s027_5(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("chat.errors.invalid-notice").to_string(),
        1 => tr0!("help.audio.no").to_string(),
        _ => tr0!("rooms.empty.empty").to_string(),
    }
}

fn s027_6(n: i64, who: &'static str, when: &'static str) -> String {
    tr0!("common.dialog.keyboard-invitation").to_string()
}

#[component]
pub fn C027() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <ul class="table" title={crate::tables::T027[0].label.to_string()}>
                    {crate::tables::T027.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr0!("common.invites.of-required", host = who, room = who, sender = who).to_string(), _ => tr0!("onboarding.confirm.to", query = who).to_string(), });
                }>{tr0!("settings.level-reset-row-camera-search")}</button>
                <p>{move || s027_1(count.get(), who, when)}</p>
                <p>{move || s027_2(count.get(), who, when)}</p>
                <p>{tr0!("rooms.modal.header")}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr0!("chat.labels.private-moderator").to_string(), 1 => tr0!("rooms.sidebar.code-unread-to").to_string(), _ => tr0!("hotkeys.confirm.up").to_string(), });
                }>{tr0!("billing.roles.on")}</button>
                <p>{tr0!("notifications.to")}</p>
                <p>{tr0!("settings.labels.kick-delete-info")}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <input type="text" aria-label={tr0!("settings.dialog.title-cancel-cancel")}/>
                <StringBadge text={tr0!("admin.labels.no")}/>
                <p>{move || s027_4(count.get(), who, when)}</p>
                <p>{move || s027_5(count.get(), who, when)}</p>
                <TextLabel text={tr0!("commands.status.react")}/>
                <p>{s027_6(n, who, when)}</p>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 27">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
