//! Component C037 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::tr0;

fn s037_1(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("onboarding.form.of", remaining = n, role = who).to_string(),
        1 => tr0!("app.form.session-confirm", device = who, title = who).to_string(),
        _ => tr0!("rooms.empty.participant").to_string(),
    }
}

fn s037_3(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("moderation.members.up").to_string(),
        1 => tr0!("app.audio-sort-retry-row").to_string(),
        _ => tr0!("chat.labels.to").to_string(),
    }
}

fn s037_4(n: i64, who: &'static str, when: &'static str) -> String {
    tr0!("language-user-report").to_string()
}

#[component]
pub fn C037() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr0!("errors.menu.by", count = n).to_string());
                }>{tr0!("count-badge-date-moderation-more")}</button>
                <ul class="table" title={crate::tables::T037[0].label.to_string()}>
                    {crate::tables::T037.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <StringBadge text={tr0!("media.labels.role-visibility", max_size = n, target = who)}/>
                <TextLabel text={move || tr0!("auth.audio.code-member-dialog-by", email = name).to_string()}/>
                <p>{move || s037_1(count.get(), who, when)}</p>
                <p>{move || tr0!("commands.invites.up", members = count.get())}</p>
                <p>{tr0!("onboarding.confirm.total-of")}</p>
                <input type="text" aria-label={tr0!("errors.history.placeholder")} placeholder={tr0!("commands.failed-camera")}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <StringBadge text={tr0!("settings.theme-role-loading")}/>
                <p>{tr0!("auth.sidebar.confirmation")}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr0!("commands.banner.id").to_string(), 1 => tr0!("chat.modal.channel-upload").to_string(), _ => tr0!("notifications.block-input").to_string(), });
                }>{tr0!("commands.video.on")}</button>
                <p>{tr0!("notifications.footer.ok")}</p>
                <SignalHint text={tr0!("moderation.drafts.on")}/>
                <p>{tr0!("moderation.privacy.no")}</p>
                <p>{tr0!("media.tabs.of")}</p>
                <p>{tr0!("rooms.modal.share-item-status-cancel")}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr0!("search.public-join-success-session-delete")}</p>
                <p>{move || s037_3(count.get(), who, when)}</p>
                <p>{move || if flag.get() { tr0!("errors.labels.title") } else { tr0!("admin.tips.report-invite") }}</p>
                <SignalHint text={tr0!("settings.panel.ban")}/>
                <p>{s037_4(n, who, when)}</p>
                <p>{move || if flag.get() { tr0!("commands.video.guest-ban") } else { tr0!("rooms.dialog.of-user") }}</p>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 37">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
