//! Component C046 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::tr0;

fn s046_0(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("errors.labels.email-limit", owner = who).to_string(),
        1 => tr0!("chat.members.retry-size", seconds = n).to_string(),
        _ => tr0!("settings.dialog.no").to_string(),
    }
}

fn s046_1(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("auth.upload.new-password-header-avatar").to_string(),
        1 => tr0!("rooms.empty.close-of").to_string(),
        _ => tr0!("billing.roles.member").to_string(),
    }
}

fn s046_2(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("errors.toolbar.enable-save-chat-upload").to_string(),
        1 => tr0!("auth.list.tab-admin").to_string(),
        _ => tr0!("search.list.of-enable-public").to_string(),
    }
}

#[component]
pub fn C046() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <input type="text" aria-label={tr0!("media.prompts.pin-menu", hours = n, pages = n)} placeholder={tr0!("commands.dialog.on", count = n)}/>
                <p>{move || s046_0(count.get(), who, when)}</p>
                <input type="text" aria-label={move || tr0!("media.of-workspace-moderation-close", query = name)} placeholder={tr0!("app.form.status-unknown-less-on")}/>
                <TextLabel text={move || tr0!("onboarding.confirm.up", count = count.get(), language = name.get(), pages = count.get()).to_string()}/>
                <p>{tr0!("moderation.confirm.of", name = who, title = who)}</p>
                <p>{tr0!("profile.audio.background")}</p>
                <input type="text" aria-label={tr0!("auth.sidebar.no")} placeholder={tr0!("errors.up-save-password-no")}/>
                <p>{tr0!("auth.sidebar.new-status")}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <TextLabel text={tr0!("commands.banner.by")}/>
                <p>{tr0!("commands.limit-row")}</p>
                <p>{tr0!("chat.labels.on")}</p>
                <p>{move || s046_1(count.get(), who, when)}</p>
                <p>{move || if flag.get() { tr0!("moderation.menu-hide") } else { tr0!("chat.prompts.button-by") }}</p>
                <SignalHint text={tr0!("common.toolbar.search")}/>
                <p>{move || s046_2(count.get(), who, when)}</p>
                <ul class="table" title={crate::tables::T046[0].label.to_string()}>
                    {crate::tables::T046.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr0!("commands.status.busy-ok").to_string(), 1 => tr0!("rooms.modal.placeholder").to_string(), _ => tr0!("settings.labels.tab").to_string(), });
                }>{tr0!("commands.table.attachment")}</button>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr0!("onboarding.form.moderation").to_string());
                }>{tr0!("common.list.reconnect")}</button>
                <TextLabel text={tr0!("chat.slow")}/>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 46">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
