//! Component C048 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::tr0;

fn s048_0(n: i64, who: &'static str, when: &'static str) -> String {
    tr0!("auth.sidebar.camera-prompt", amount = n).to_string()
}

fn s048_1(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("media.labels.block", room = who).to_string(),
        1 => tr0!("app.input.moderator", reason = who).to_string(),
        _ => tr0!("subscription").to_string(),
    }
}

fn s048_2(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("help.audio.footer-token-text-delete").to_string(),
        1 => tr0!("commands.video.of").to_string(),
        _ => tr0!("profile.audio.position").to_string(),
    }
}

fn s048_3(n: i64, who: &'static str, when: &'static str) -> String {
    tr0!("billing.invites.avatar-body-all").to_string()
}

#[component]
pub fn C048() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{move || if flag.get() { tr0!("settings.drafts.to", members = n) } else { tr0!("commands.invites.up", members = n) }}</p>
                <p>{s048_0(n, who, when)}</p>
                <p>{move || tr0!("settings.form.save-ban-shortcut", plan = name)}</p>
                <p>{tr0!("onboarding.confirm.react-close", days = n, size = n)}</p>
                <p>{move || s048_1(count.get(), who, when)}</p>
                <input type="text" aria-label={move || tr0!("moderation.members.status", reason = name)} placeholder={tr0!("chat.badges.open-emoji")}/>
                <p>{move || s048_2(count.get(), who, when)}</p>
                <p>{tr0!("search.save-confirm-prompt")}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr0!("errors.upload.item-ban")}</p>
                <ul class="table" title={crate::tables::T048[0].label.to_string()}>
                    {crate::tables::T048.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <p>{tr0!("chat.labels.password-url")}</p>
                <SignalHint text={tr0!("settings.panel.search")}/>
                <StringBadge text={tr0!("common.list.of")}/>
                <p>{tr0!("auth.form.url-guest-search")}</p>
                <p>{tr0!("errors.labels.on")}</p>
                <p>{move || if flag.get() { tr0!("onboarding.id") } else { tr0!("errors.history.id-incoming") }}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{s048_3(n, who, when)}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr0!("auth.upload.missing").to_string());
                }>{tr0!("notifications.prompts.ok")}</button>
                <input type="text" aria-label={tr0!("hotkeys.to")} placeholder={tr0!("rooms.empty.participant")}/>
                <p>{move || if flag.get() { tr0!("media.drafts.microphone-guest") } else { tr0!("auth.audio.microphone") }}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr0!("profile.email-language-hint-ban").to_string(), 1 => tr0!("settings.labels.expired-shortcut").to_string(), _ => tr0!("search.account.on").to_string(), });
                }>{tr0!("common.list.label-character")}</button>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 48">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
