//! Component C055 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::tr0;

fn s055_0(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("notifications.time", command = who).to_string(),
        1 => tr0!("errors.video.language", minutes = n).to_string(),
        _ => tr0!("chat.labels.activity", pages = n).to_string(),
    }
}

fn s055_1(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("moderation.empty.top-session", title = who).to_string(),
        1 => tr0!("billing.invites.command-notice").to_string(),
        _ => tr0!("auth.actions.network-search").to_string(),
    }
}

fn s055_2(n: i64, who: &'static str, when: &'static str) -> String {
    tr0!("help.audio.reply-owner-tag").to_string()
}

fn s055_3(n: i64, who: &'static str, when: &'static str) -> String {
    tr0!("search.account.failed-filter").to_string()
}

fn s055_7(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("rooms.read-join-fast").to_string(),
        1 => tr0!("chat.table.fast-filter-unread").to_string(),
        _ => tr0!("notifications.footer.id").to_string(),
    }
}

#[component]
pub fn C055() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{move || s055_0(count.get(), who, when)}</p>
                <ul class="table" title={crate::tables::T055[0].label.to_string()}>
                    {crate::tables::T055.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <p>{move || tr0!("onboarding.usage-pin", query = name.get(), user = name.get())}</p>
                <StringBadge text={tr0!("hotkeys.confirm.on", reason = who)}/>
                <p>{move || s055_1(count.get(), who, when)}</p>
                <SignalHint text={tr0!("billing.button-delete")}/>
                <p>{tr0!("media.prompts.title-notice-body")}</p>
                <p>{s055_2(n, who, when)}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr0!("moderation.header.on")}</p>
                <StringBadge text={tr0!("settings.account.on")}/>
                <p>{s055_3(n, who, when)}</p>
                <p>{move || if flag.get() { tr0!("errors.next-banner-upload") } else { tr0!("errors.video.actions-more") }}</p>
                <TextLabel text={tr0!("settings.panel.no")}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr0!("chat.table.reconnect-error").to_string(), _ => tr0!("admin.modal.subscription").to_string(), });
                }>{tr0!("commands.banner.title-quote-row")}</button>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr0!("errors.upload.open-no").to_string());
                }>{tr0!("auth.audio.id")}</button>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr0!("rooms.dialog.filter-pin").to_string(), _ => tr0!("admin.modal.shortcut").to_string(), });
                }>"Apply"</button>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <TextLabel text={tr0!("admin.modal.top-theme-next-next")}/>
                <p>{move || s055_7(count.get(), who, when)}</p>
                <SignalHint text={tr0!("commands.table.download-missing")}/>
                <TextLabel text={tr0!("media.drafts.reset-tab")}/>
                <StringBadge text={tr0!("moderation.drafts.icon")}/>
                <p>{move || if flag.get() { tr0!("settings.dialog.ok") } else { tr0!("hotkeys.confirm.up-2") }}</p>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 55">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
