//! Component C059 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::tr0;

fn s059_0(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("help.audio.ok-no-moderator-no", level = n).to_string(),
        1 => tr0!("chat.confirm.expired-public", language = who, remaining = n).to_string(),
        _ => tr0!("media.tabs.unread-member").to_string(),
    }
}

fn s059_2(n: i64, who: &'static str, when: &'static str) -> String {
    tr0!("hotkeys.confirm.mode-preferences").to_string()
}

fn s059_3(n: i64, who: &'static str, when: &'static str) -> String {
    tr0!("settings.account.pin-network").to_string()
}

fn s059_4(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr0!("settings.labels.profile").to_string(),
        1 => tr0!("moderation.empty.status").to_string(),
        _ => tr0!("settings.visibility-background").to_string(),
    }
}

#[component]
pub fn C059() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{move || tr0!("search.account.done-new", days = count.get())}</p>
                <p>{move || s059_0(count.get(), who, when)}</p>
                <p>{move || if flag.get() { tr0!("settings.labels.of-all-network", position = n) } else { tr0!("chat.banner.public-footer", item = who) }}</p>
                <ul class="table" title={crate::tables::T059[0].label.to_string()}>
                    {crate::tables::T059.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <SignalHint text={Signal::derive(move || tr0!("chat.members.voice-new-email-attachment", title = name).to_string())}/>
                <input type="text" aria-label={tr0!("settings.attachment-icon-report", hours = n)}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr0!("common.upload.off").to_string(), 1 => tr0!("search.account.warning").to_string(), _ => tr0!("profile.security.of").to_string(), });
                }>{tr0!("errors.banner.done")}</button>
                <p>{tr0!("commands.table.command-of-view")}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr0!("help.audio.open")}</p>
                <SignalHint text={tr0!("errors.security.keyboard")}/>
                <p>{tr0!("auth.sidebar.tooltip")}</p>
                <StringBadge text={tr0!("commands.banner.required")}/>
                <p>{tr0!("hotkeys.confirm.ok-2")}</p>
                <p>{s059_2(n, who, when)}</p>
                <p>{s059_3(n, who, when)}</p>
                <StringBadge text={tr0!("settings.labels.size-view-kick")}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{move || if flag.get() { tr0!("search.list.guest-typing-joined") } else { tr0!("rooms.modal.public-joined") }}</p>
                <p>{move || s059_4(count.get(), who, when)}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr0!("settings.dialog.no").to_string());
                }>{tr0!("help.audio.footer-token-text-delete")}</button>
                <TextLabel text={tr0!("app.form.status-unknown-less-on")}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr0!("chat.badges.open-emoji").to_string());
                }>{tr0!("profile.input.delete")}</button>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 59">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
