//! Word lists. Everything the generator writes is assembled from these tables,
//! so they are part of the output's definition: editing them changes the
//! corpus (and the committed `bench/corpora/workload-1600.json`).

/// English UI vocabulary for message text and comments. Grouped by byte length
/// at run time; every length from 1 to 13 must be present so that text of any
/// exact byte length can be assembled. A few words carry non-ASCII
/// typography (`’`, `…`), as real UI text does.
pub const EN_WORDS: &[&str] = &[
    // 1–2
    "a",
    "OK",
    "no",
    "on",
    "to",
    "in",
    "of",
    "is",
    "it",
    "by",
    "at",
    "or",
    "up",
    "go",
    "me",
    "my",
    "we",
    "be",
    "do",
    "if",
    "as",
    "an",
    "so",
    "×",
    // 3
    "add",
    "all",
    "and",
    "are",
    "can",
    "new",
    "off",
    "yes",
    "the",
    "you",
    "for",
    "not",
    "now",
    "one",
    "out",
    "set",
    "use",
    "see",
    "try",
    "own",
    "few",
    "any",
    "day",
    "key",
    "log",
    "map",
    "max",
    "min",
    "row",
    "tab",
    "tag",
    "top",
    "via",
    "way",
    "was",
    "has",
    "get",
    "bot",
    "mic",
    "fix",
    "…",
    // 4
    "save",
    "edit",
    "send",
    "open",
    "room",
    "chat",
    "user",
    "name",
    "file",
    "list",
    "view",
    "help",
    "back",
    "next",
    "done",
    "show",
    "hide",
    "more",
    "less",
    "this",
    "that",
    "with",
    "from",
    "your",
    "been",
    "have",
    "will",
    "when",
    "then",
    "than",
    "here",
    "mute",
    "ping",
    "role",
    "kick",
    "sign",
    "type",
    "time",
    "link",
    "copy",
    "move",
    "join",
    "left",
    "keep",
    "sure",
    "page",
    "menu",
    "mode",
    "text",
    "code",
    "none",
    "only",
    "each",
    "last",
    "item",
    "plan",
    "free",
    "sort",
    "live",
    "it’s",
    // 5
    "about",
    "after",
    "again",
    "allow",
    "apply",
    "audio",
    "block",
    "clear",
    "close",
    "could",
    "delay",
    "empty",
    "enter",
    "error",
    "every",
    "field",
    "first",
    "guest",
    "image",
    "input",
    "invite",
    "later",
    "leave",
    "limit",
    "local",
    "owner",
    "panel",
    "reply",
    "reset",
    "retry",
    "right",
    "rules",
    "share",
    "sound",
    "start",
    "still",
    "theme",
    "there",
    "title",
    "topic",
    "until",
    "video",
    "voice",
    "while",
    "would",
    "can’t",
    "don’t",
    // 6
    "access",
    "accept",
    "action",
    "active",
    "always",
    "banned",
    "cancel",
    "change",
    "choose",
    "delete",
    "device",
    "direct",
    "enable",
    "failed",
    "filter",
    "follow",
    "friend",
    "hidden",
    "inside",
    "member",
    "method",
    "minute",
    "moment",
    "online",
    "people",
    "please",
    "portal",
    "public",
    "reason",
    "remove",
    "report",
    "result",
    "screen",
    "search",
    "second",
    "select",
    "server",
    "should",
    "signed",
    "status",
    "stream",
    "typing",
    "unread",
    "update",
    "upload",
    "window",
    "won’t",
    // 7
    "account",
    "allowed",
    "already",
    "another",
    "arrival",
    "avatars",
    "blocked",
    "channel",
    "command",
    "confirm",
    "connect",
    "content",
    "control",
    "current",
    "default",
    "details",
    "disable",
    "display",
    "private",
    "profile",
    "message",
    "missing",
    "network",
    "nothing",
    "offline",
    "picture",
    "pinned",
    "quality",
    "reached",
    "restart",
    "request",
    "session",
    "setting",
    "sharing",
    "speaker",
    "unknown",
    "version",
    "waiting",
    "you’re",
    "saving…",
    // 8
    "accounts",
    "activity",
    "download",
    "language",
    "messages",
    "everyone",
    "channels",
    "continue",
    "disabled",
    "expired",
    "external",
    "favorite",
    "included",
    "incoming",
    "keyboard",
    "location",
    "maximum",
    "minimum",
    "password",
    "position",
    "previous",
    "received",
    "settings",
    "shortcut",
    "selected",
    "requests",
    "required",
    "security",
    "username",
    "visitors",
    // 9
    "available",
    "character",
    "community",
    "completed",
    "connected",
    "currently",
    "customize",
    "important",
    "incorrect",
    "invisible",
    "microphone",
    "necessary",
    "overwrite",
    "recording",
    "reconnect",
    "something",
    "temporary",
    "uploading",
    "workspace",
    "loading…",
    // 10
    "attachment",
    "connection",
    "moderation",
    "permission",
    "microphone",
    "background",
    "characters",
    "downloaded",
    "invitation",
    "management",
    "suggestion",
    "successful",
    "unexpected",
    "visibility",
    "searching…",
    // 11
    "permissions",
    "unavailable",
    "participant",
    "information",
    "maintenance",
    "preferences",
    "moderators",
    "screenshots",
    "temporarily",
    "unsupported",
    "connecting…",
    // 12
    "subscription",
    "notification",
    "successfully",
    "confirmation",
    "participants",
    "unrecognized",
    "reconnecting",
    "accessibility",
    // 13
    "notifications",
    "configuration",
    "unfortunately",
    "automatically",
    "administrator",
    "international",
];

/// Lower-case ASCII words for kebab-case id keys; every length 2–12 present.
pub const KEY_WORDS: &[&str] = &[
    "ok",
    "on",
    "id",
    "to",
    "up",
    "no",
    "by",
    "of",
    "add",
    "all",
    "ban",
    "bot",
    "new",
    "off",
    "pin",
    "row",
    "tab",
    "tag",
    "top",
    "url",
    "copy",
    "edit",
    "send",
    "open",
    "room",
    "chat",
    "user",
    "name",
    "file",
    "list",
    "view",
    "help",
    "back",
    "next",
    "done",
    "show",
    "hide",
    "more",
    "less",
    "mute",
    "kick",
    "role",
    "link",
    "join",
    "page",
    "menu",
    "mode",
    "text",
    "code",
    "item",
    "plan",
    "sort",
    "hint",
    "icon",
    "info",
    "save",
    "body",
    "size",
    "time",
    "date",
    "away",
    "busy",
    "read",
    "sent",
    "title",
    "label",
    "error",
    "empty",
    "close",
    "reset",
    "retry",
    "apply",
    "audio",
    "video",
    "theme",
    "owner",
    "guest",
    "reply",
    "share",
    "limit",
    "count",
    "total",
    "email",
    "token",
    "usage",
    "topic",
    "badge",
    "block",
    "leave",
    "quote",
    "react",
    "emoji",
    "sound",
    "level",
    "slow",
    "fast",
    "input",
    "admin",
    "voice",
    "button",
    "cancel",
    "delete",
    "header",
    "footer",
    "invite",
    "member",
    "status",
    "online",
    "typing",
    "upload",
    "search",
    "result",
    "filter",
    "volume",
    "avatar",
    "banner",
    "dialog",
    "enable",
    "notice",
    "prompt",
    "action",
    "report",
    "thread",
    "unread",
    "camera",
    "screen",
    "device",
    "failed",
    "expired",
    "invalid",
    "missing",
    "unknown",
    "command",
    "channel",
    "private",
    "public",
    "warning",
    "actions",
    "confirm",
    "loading",
    "success",
    "members",
    "offline",
    "results",
    "profile",
    "session",
    "speaker",
    "quality",
    "network",
    "joined",
    "tooltip",
    "settings",
    "language",
    "password",
    "required",
    "download",
    "keyboard",
    "shortcut",
    "position",
    "disabled",
    "security",
    "incoming",
    "activity",
    "reconnect",
    "available",
    "character",
    "moderator",
    "microphone",
    "recording",
    "workspace",
    "connection",
    "moderation",
    "attachment",
    "background",
    "invitation",
    "visibility",
    "placeholder",
    "permissions",
    "participant",
    "preferences",
    "unavailable",
    "notification",
    "subscription",
    "confirmation",
];

/// File namespaces (one `.mf2` file each), with a relative weight: files are
/// uneven in size, as in real projects. `app` must stay first (the canary
/// lives there) and `common` holds the section-less entries.
pub const NAMESPACES: &[(&str, u32)] = &[
    ("app", 7),
    ("auth", 6),
    ("chat", 14),
    ("commands", 9),
    ("errors", 8),
    ("settings", 12),
    ("profile", 5),
    ("rooms", 7),
    ("moderation", 6),
    ("notifications", 4),
    ("hotkeys", 3),
    ("media", 5),
    ("onboarding", 3),
    ("admin", 5),
    ("search", 3),
    ("billing", 2),
    ("help", 2),
    ("common", 6),
    ("editor", 4),
    ("files", 4),
    ("calls", 4),
    ("invites", 3),
    ("reports", 2),
    ("themes", 2),
];

/// The namespace whose first block of entries has no section head.
pub const TOPLEVEL_NAMESPACE: &str = "common";

/// Sub-section names (`[chat.input]`).
pub const SECTION_WORDS: &[&str] = &[
    "input", "list", "dialog", "menu", "status", "errors", "labels", "actions", "tips", "header",
    "footer", "form", "table", "toolbar", "panel", "banner", "empty", "confirm", "sidebar",
    "modal", "tabs", "filters", "upload", "members", "invites", "roles", "audio", "video",
    "privacy", "account", "security", "history", "drafts", "badges", "limits", "prompts",
];

/// Variable names that hold numbers (valid Rust identifiers, snake case).
pub const NUM_VARS: &[&str] = &[
    "count",
    "total",
    "limit",
    "seconds",
    "minutes",
    "hours",
    "days",
    "size",
    "position",
    "max_size",
    "amount",
    "attempts",
    "remaining",
    "members",
    "votes",
    "level",
    "percent",
    "page",
    "pages",
    "index",
];

/// Variable names that hold strings.
pub const STR_VARS: &[&str] = &[
    "user",
    "name",
    "room",
    "channel",
    "file_name",
    "query",
    "role",
    "email",
    "reason",
    "version",
    "title",
    "target",
    "sender",
    "device",
    "language",
    "plan",
    "topic",
    "host",
    "tag",
    "item",
    "command",
    "owner",
];

/// Variable names that hold date/time values (only with `--datetime`).
pub const DATE_VARS: &[&str] = &["when", "date", "deadline", "started_at", "expires_at"];

/// Markup used inside sentences: `(name, possible inner texts)`.
pub const MARKUP: &[(&str, &[&str])] = &[
    (
        "kbd",
        &["Esc", "Enter", "Tab", "Ctrl", "Shift", "Alt", "Space", "?"],
    ),
    ("strong", &["now", "all", "never", "everyone", "this"]),
    ("em", &["not", "only", "before", "after"]),
];

/// Nouns used in `@param` descriptions.
pub const PARAM_NOUNS: &[&str] = &[
    "messages", "people", "rooms", "files", "items", "members", "requests", "attempts", "results",
    "invites",
];

/// A real (non-source, non-pseudo) locale: tag, CLDR cardinal plural
/// categories in canonical order, and the syllables its synthetic text is made
/// of. `spaced = false` writes words without spaces (Japanese). `expansion` is
/// the text-length ratio against English, in percent.
#[derive(Debug, Clone, Copy)]
pub struct RealLocale {
    /// BCP 47 tag.
    pub tag: &'static str,
    /// Cardinal plural categories (the last one, `other`, is written `*`).
    pub plural: &'static [&'static str],
    /// Syllable inventory for synthetic words.
    pub syllables: &'static [&'static str],
    /// Words are separated by spaces.
    pub spaced: bool,
    /// Text length relative to English, percent.
    pub expansion: usize,
}

/// Candidate second-and-further real locales, in the order `--locales` adds them.
pub const REAL_LOCALES: &[RealLocale] = &[
    RealLocale {
        tag: "pl",
        plural: &["one", "few", "many", "other"],
        syllables: &[
            "ka", "ło", "wie", "prze", "szy", "czę", "ść", "ży", "ną", "nie", "dzi", "rz", "go",
            "wa", "ję", "mo", "ta", "po", "wy", "zo", "sta", "ni", "ków", "ał", "ędz", "óż",
        ],
        spaced: true,
        expansion: 118,
    },
    RealLocale {
        tag: "de",
        plural: &["one", "other"],
        syllables: &[
            "ein", "ge", "sch", "ung", "keit", "ber", "ä", "ö", "ü", "ß", "lich", "ver", "zu",
            "an", "stell", "en", "tra", "gen", "wer", "de", "hal", "ten",
        ],
        spaced: true,
        expansion: 125,
    },
    RealLocale {
        tag: "fr",
        plural: &["one", "many", "other"],
        syllables: &[
            "le", "la", "é", "è", "ç", "ment", "tion", "eau", "ou", "re", "de", "que", "par", "ai",
            "on", "cou", "ver", "sa", "ti", "mê",
        ],
        spaced: true,
        expansion: 120,
    },
    RealLocale {
        tag: "ar",
        plural: &["zero", "one", "two", "few", "many", "other"],
        syllables: &[
            "ال", "م", "ر", "س", "ل", "ة", "ت", "ب", "ك", "ي", "و", "ن", "ح", "ع",
        ],
        spaced: true,
        expansion: 105,
    },
    RealLocale {
        tag: "ru",
        plural: &["one", "few", "many", "other"],
        syllables: &[
            "при", "ка", "ло", "ть", "ва", "ние", "ст", "ый", "ой", "жи", "по", "ре", "на", "ми",
            "со", "об", "щ", "ю",
        ],
        spaced: true,
        expansion: 115,
    },
    RealLocale {
        tag: "ja",
        plural: &["other"],
        syllables: &[
            "の", "に", "を", "ま", "す", "ア", "イ", "カ", "設", "定", "送", "信", "表", "示",
            "削", "除", "ル", "ー", "ム",
        ],
        spaced: false,
        expansion: 60,
    },
    RealLocale {
        tag: "cy",
        plural: &["zero", "one", "two", "few", "many", "other"],
        syllables: &[
            "ll", "dd", "yn", "wch", "gwr", "aeth", "ŵ", "ŷ", "rh", "ff", "cy", "mr", "au", "io",
            "neg", "es",
        ],
        spaced: true,
        expansion: 115,
    },
];

/// en-XA accent map for ASCII letters (`a`..`z`, then `A`..`Z`).
pub const ACCENTS_LOWER: [&str; 26] = [
    "å", "ƀ", "ç", "ð", "é", "ƒ", "ĝ", "ĥ", "î", "ĵ", "ķ", "ļ", "ɱ", "ñ", "ö", "þ", "ǫ", "ŕ", "š",
    "ţ", "û", "ṽ", "ŵ", "ẋ", "ý", "ž",
];

/// Upper-case half of the en-XA accent map.
pub const ACCENTS_UPPER: [&str; 26] = [
    "Å", "Ɓ", "Ç", "Ð", "É", "Ƒ", "Ĝ", "Ĥ", "Î", "Ĵ", "Ķ", "Ļ", "Ṁ", "Ñ", "Ö", "Þ", "Ǫ", "Ŕ", "Š",
    "Ţ", "Û", "Ṽ", "Ŵ", "Ẋ", "Ý", "Ž",
];

/// Padding words appended by en-XA to expand text.
pub const PSEUDO_PAD: &[&str] = &[
    "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten",
];
