//! Errors of the probe's `tr` crate.
//!
//! The `Display` impls generated by `thiserror` exist, but nothing on the client
//! path formats them: the client reports failures with fixed `&'static str`
//! messages (see `CatalogError::code`), so no `core::fmt` is pulled in by them.

use thiserror::Error;

/// Why a fetched catalog was rejected by [`crate::Catalog::new`].
#[derive(Debug, Error, Clone, Copy, PartialEq, Eq)]
pub enum CatalogError {
    #[error("catalog is truncated or a section lies outside the buffer")]
    Truncated,
    #[error("bad magic: not an .mf2b catalog")]
    BadMagic,
    #[error("unsupported catalog format version")]
    UnsupportedVersion,
    #[error("manifest hash mismatch: the catalog was built for another wasm (deploy skew)")]
    ManifestMismatch,
    #[error("index offsets are not monotonic or exceed the string pool")]
    BadIndex,
    #[error("string pool is not valid UTF-8")]
    BadUtf8,
    #[error("locale tag is not ASCII")]
    BadLocale,
}

impl CatalogError {
    /// A fixed, fmt-free description for client-side diagnostics.
    pub const fn code(self) -> &'static str {
        match self {
            Self::Truncated => "mf2: catalog rejected (truncated)",
            Self::BadMagic => "mf2: catalog rejected (bad magic)",
            Self::UnsupportedVersion => "mf2: catalog rejected (format version)",
            Self::ManifestMismatch => "mf2: catalog rejected (manifest hash mismatch)",
            Self::BadIndex => "mf2: catalog rejected (bad index)",
            Self::BadUtf8 => "mf2: catalog rejected (pool not UTF-8)",
            Self::BadLocale => "mf2: catalog rejected (locale tag)",
        }
    }
}

/// Why loading a catalog in the browser failed (boot or `set_locale`).
#[derive(Debug, Error)]
pub enum LoadError {
    #[error("no <link rel=preload data-mf2> element in the document")]
    NoPreloadLink,
    #[error("fetching the catalog failed")]
    Fetch,
    #[error("the catalog request returned a non-success status")]
    Status,
    #[error("the catalog's locale differs from <html lang>")]
    LangMismatch,
    #[error(transparent)]
    Catalog(#[from] CatalogError),
}

impl LoadError {
    /// A fixed, fmt-free description for client-side diagnostics.
    pub const fn code(&self) -> &'static str {
        match self {
            Self::NoPreloadLink => "mf2: no <link data-mf2> in the document",
            Self::Fetch => "mf2: catalog fetch failed",
            Self::Status => "mf2: catalog fetch returned an error status",
            Self::LangMismatch => "mf2: catalog locale differs from <html lang>",
            Self::Catalog(e) => e.code(),
        }
    }
}
