//! Component C000 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::tr;

fn s000_2(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("app.security.typing-retry").to_string(),
        1 => tr!("commands.banner.id-success").to_string(),
        _ => tr!("profile.table.on").to_string(),
    }
}

fn s000_3(n: i64, who: &'static str, when: &'static str) -> String {
    tr!("rooms.dialog.unknown-info").to_string()
}

fn s000_6(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("common.roles.notification").to_string(),
        1 => tr!("profile.audio.recording").to_string(),
        _ => tr!("chat.menu.url-send-filter").to_string(),
    }
}

fn s000_8(n: i64, who: &'static str, when: &'static str) -> String {
    tr!("errors.upload.button").to_string()
}

fn s000_9(n: i64, who: &'static str, when: &'static str) -> String {
    tr!("profile.footer-video").to_string()
}

#[component]
pub fn C000() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{tr!("app.canary.zq7-canary-msg", zq7_canary_var = who)}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr!("app.input.moderator", reason = who).to_string(), 1 => tr!("media.prompts.away-leave-tab", remaining = n).to_string(), _ => tr!("media.labels.no", max_size = n, sender = who).to_string(), });
                }>{tr!("auth.sidebar.no")}</button>
                <p>{move || if flag.get() { tr!("auth.audio.moderation-sent-by", level = n) } else { tr!("auth.sidebar.actions-prompt", device = who) }}</p>
                <p>{move || tr!("notifications.footer.to", channel = name, tag = name)}</p>
                <p>{move || tr!("errors.menu.plan-recording", language = name.get())}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr!("notifications.form.id-2", days = n, remaining = n).to_string());
                }>{tr!("settings.filters.volume-new")}</button>
                <p>{tr!("chat.save-page-tooltip-add-joined")}</p>
                <StringBadge text={tr!("chat.modal.hint-code-sort-retry")}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{move || s000_2(count.get(), who, when)}</p>
                <StringBadge text={tr!("rooms.dialog.ok")}/>
                <p>{tr!("rooms.dialog.action-online")}</p>
                <ul class="table" title={crate::tables::T000[0].label.to_string()}>
                    {crate::tables::T000.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <p>{s000_3(n, who, when)}</p>
                <SignalHint text={tr!("commands.dialog.sent")}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr!("auth.actions.unavailable").to_string());
                }>{tr!("chat.badges.chat-screen")}</button>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr!("settings.account.send").to_string());
                }>{tr!("moderation.top")}</button>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{move || s000_6(count.get(), who, when)}</p>
                <TextLabel text={tr!("commands.table.button")}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr!("admin.tips.ban-mode-expired-recording").to_string());
                }>{tr!("commands.invites.to")}</button>
                <p>{s000_8(n, who, when)}</p>
                <p>{s000_9(n, who, when)}</p>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 0">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
