//! Component C002 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::tr;

fn s002_0(n: i64, who: &'static str, when: &'static str) -> String {
    tr!("admin.labels.disabled", item = who).to_string()
}

fn s002_3(n: i64, who: &'static str, when: &'static str) -> String {
    tr!("admin.input.edit-bot-away-info-busy").to_string()
}

fn s002_4(n: i64, who: &'static str, when: &'static str) -> String {
    tr!("auth.banner.offline-connection-body").to_string()
}

fn s002_6(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("rooms.empty.screen-report-action").to_string(),
        1 => tr!("rooms.limits.done").to_string(),
        _ => tr!("errors.form.member-keyboard-avatar").to_string(),
    }
}

fn s002_7(n: i64, who: &'static str, when: &'static str) -> String {
    tr!("commands.invites.page").to_string()
}

fn s002_8(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(2) {
        0 => tr!("hotkeys.confirm.badge-confirmation").to_string(),
        _ => tr!("more-new-audio-delete-shortcut-size-item").to_string(),
    }
}

#[component]
pub fn C002() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <StringBadge text={tr!("app.footer-avatar-icon-email", channel = who, language = who)}/>
                <p>{s002_0(n, who, when)}</p>
                <p>{move || tr!("common.toolbar.banner-mute-guest", votes = count)}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr!("chat.labels.up", channel = who, host = who).to_string(), _ => tr!("chat.errors.copy-header-typing", percent = n).to_string(), });
                }>{tr!("app.apply-confirm-user")}</button>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr!("profile.table.notice-no", item = who).to_string(), 1 => tr!("actions-joined-busy", title = who).to_string(), _ => tr!("admin.room-result-device").to_string(), });
                }>{tr!("rooms.dialog.fast-kick-limit")}</button>
                <ul class="table" title={crate::tables::T002[0].label.to_string()}>
                    {crate::tables::T002.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <p>{s002_3(n, who, when)}</p>
                <input type="text" aria-label={tr!("chat.table.owner-visibility")} placeholder={tr!("profile.input.invalid-public")}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <input type="text" aria-label={tr!("auth.form.incoming")} placeholder={tr!("notifications.form.of-2")}/>
                <p>{tr!("chat.table.up")}</p>
                <p>{s002_4(n, who, when)}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr!("hotkeys.confirm.volume-status").to_string(), 1 => tr!("errors.form.attachment").to_string(), _ => tr!("rooms.modal.code").to_string(), });
                }>"Apply"</button>
                <StringBadge text={tr!("chat.badges.view-actions-to")}/>
                <StringBadge text={tr!("rooms.modal.open-failed-joined")}/>
                <TextLabel text={tr!("settings.view-public")}/>
                <p>{move || s002_6(count.get(), who, when)}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr!("auth.prompts.of")}</p>
                <p>{s002_7(n, who, when)}</p>
                <p>{move || s002_8(count.get(), who, when)}</p>
                <SignalHint text={tr!("errors.upload.item-ban")}/>
                <SignalHint text={tr!("chat.privacy.ok")}/>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 2">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
