//! Component C012 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::tr;

fn s012_0(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("common.dialog.add", count = n).to_string(),
        1 => tr!("errors.list.less-react-character", host = who, target = who).to_string(),
        _ => tr!("chat.prompts.row", count = n).to_string(),
    }
}

fn s012_1(n: i64, who: &'static str, when: &'static str) -> String {
    tr!("errors.form.unread-cancel").to_string()
}

fn s012_2(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("admin.badge").to_string(),
        1 => tr!("chat.modal.action-delete").to_string(),
        _ => tr!("common.roles.loading-top").to_string(),
    }
}

#[component]
pub fn C012() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{move || s012_0(count.get(), who, when)}</p>
                <p>{tr!("settings.labels.dialog", max_size = n)}</p>
                <ul class="table" title={crate::tables::T012[0].label.to_string()}>
                    {crate::tables::T012.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <StringBadge text={tr!("app.form.less-busy-background-connection", count = n)}/>
                <input type="text" aria-label={tr!("settings.new-joined-public", email = who)} placeholder={tr!("commands.banner.footer-member")}/>
                <SignalHint text={tr!("errors.history.preferences", pages = n)}/>
                <p>{s012_1(n, who, when)}</p>
                <p>{move || if flag.get() { tr!("admin.badges.up") } else { tr!("save-audio-leave-role-ban") }}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{move || s012_2(count.get(), who, when)}</p>
                <TextLabel text={tr!("moderation.header.notice-banner-badge")}/>
                <p>{tr!("errors.sort-missing-command-new")}</p>
                <StringBadge text={tr!("chat.upload.recording-cancel")}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr!("errors.recording-avatar-on").to_string(), 1 => tr!("errors.menu.required-on-input").to_string(), _ => tr!("media.labels.no-kick").to_string(), });
                }>{tr!("commands.table.command-of-view")}</button>
                <p>{tr!("settings.labels.of")}</p>
                <p>{tr!("common.toolbar.participant")}</p>
                <input type="text" aria-label={tr!("common.dialog.keyboard")}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr!("settings.dialog.network-background").to_string());
                }>{tr!("help.owner-of-volume-badge-to")}</button>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr!("notifications.less-speaker-visibility").to_string());
                }>{tr!("onboarding.form.tag")}</button>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 12">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
