//! Component C013 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::tr;

fn s013_1(n: i64, who: &'static str, when: &'static str) -> String {
    tr!("settings.panel.by").to_string()
}

fn s013_5(n: i64, who: &'static str, when: &'static str) -> String {
    tr!("help.audio.open").to_string()
}

#[component]
pub fn C013() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{move || tr!("actions-joined-busy", title = name.get())}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr!("settings.errors.search", max_size = n).to_string(), _ => tr!("rooms.empty.empty").to_string(), });
                }>{tr!("admin.done-share-mode-public-header")}</button>
                <p>{move || tr!("notifications.prompts.up", device = name.get())}</p>
                <StringBadge text={tr!("search.account.to", query = who)}/>
                <StringBadge text={tr!("search.list.camera", sender = who)}/>
                <StringBadge text={tr!("settings.dialog.to", days = n)}/>
                <p>{move || tr!("media.labels.expired-joined", hours = count, language = name)}</p>
                <p>{move || tr!("auth.banner.permissions", reason = name)}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <ul class="table" title={crate::tables::T013[0].label.to_string()}>
                    {crate::tables::T013.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <p>{tr!("common.invites.hint-id-keyboard-open-new")}</p>
                <p>{s013_1(n, who, when)}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr!("settings.panel.on").to_string(), 1 => tr!("chat.errors.keyboard").to_string(), _ => tr!("media.labels.incoming").to_string(), });
                }>{tr!("commands.dialog.video")}</button>
                <TextLabel text={tr!("chat.members.unread-camera")}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr!("errors.no").to_string(), 1 => tr!("moderation.header.by").to_string(), _ => tr!("errors.toolbar.result-background").to_string(), });
                }>{tr!("auth.list.reset")}</button>
                <p>{move || if flag.get() { tr!("moderation.confirm.volume-moderator-view") } else { tr!("settings.toolbar.add-preferences") }}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr!("chat.members.attachment-away").to_string(), 1 => tr!("errors.video.notice").to_string(), _ => tr!("app.security.typing-retry").to_string(), });
                }>{tr!("chat.prompts.menu-upload")}</button>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{move || if flag.get() { tr!("hotkeys.confirm.all") } else { tr!("chat.labels.recording-quality") }}</p>
                <input type="text" aria-label={tr!("commands.invites.icon")} placeholder={tr!("admin.room-result-device")}/>
                <p>{s013_5(n, who, when)}</p>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 13">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
