//! Component C015 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::tr;

fn s015_1(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("chat.prompts.away", page = n).to_string(),
        1 => tr!("notifications.prompts.id", file_name = who, votes = n).to_string(),
        _ => tr!("media.drafts.recording").to_string(),
    }
}

fn s015_4(n: i64, who: &'static str, when: &'static str) -> String {
    tr!("commands.banner.on").to_string()
}

fn s015_7(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("moderation.members.up-2").to_string(),
        1 => tr!("search.result-failed").to_string(),
        _ => tr!("admin.tips.on-confirm").to_string(),
    }
}

#[component]
pub fn C015() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <StringBadge text={tr!("help.audio.background", language = who)}/>
                <p>{move || tr!("moderation.members.button", percent = count)}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr!("chat.errors.busy-background", sender = who).to_string(), _ => tr!("errors.toolbar.screen-profile", page = n).to_string(), });
                }>{tr!("chat.table.owner-visibility")}</button>
                <p>{move || s015_1(count.get(), who, when)}</p>
                <TextLabel text={move || tr!("chat.badges.sound-participant", amount = count.get(), owner = name.get()).to_string()}/>
                <p>{move || tr!("moderation.drafts.to", item = name.get(), title = name.get())}</p>
                <ul class="table" title={crate::tables::T015[0].label.to_string()}>
                    {crate::tables::T015.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr!("moderation.form.confirm").to_string(), 1 => tr!("admin.copy-count").to_string(), _ => tr!("less-time-share-banner-footer").to_string(), });
                }>{tr!("commands.ban-done-react-link")}</button>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr!("profile.table.reply")}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr!("chat.members.save-title-list").to_string());
                }>{tr!("media.labels.ban")}</button>
                <p>{tr!("commands.prompts.open-visibility")}</p>
                <p>{s015_4(n, who, when)}</p>
                <input type="text" aria-label={tr!("admin.tips.public-banner")} placeholder={tr!("app.status-avatar")}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr!("settings.dialog.send-hide").to_string(), _ => tr!("settings.toolbar.level").to_string(), });
                }>"Apply"</button>
                <SignalHint text={tr!("media.labels.missing-less-less")}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr!("rooms.modal.on").to_string(), _ => tr!("hotkeys.list.on").to_string(), });
                }>"Apply"</button>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <SignalHint text={tr!("settings.panel.up")}/>
                <p>{move || s015_7(count.get(), who, when)}</p>
                <SignalHint text={tr!("errors.video.id")}/>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 15">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
