//! Component C019 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::tr;

fn s019_0(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("search.list.notice-plan", minutes = n).to_string(),
        1 => tr!("chat.private-network", name = who, user = who).to_string(),
        _ => tr!("commands.banner.participant", tag = who).to_string(),
    }
}

fn s019_1(n: i64, who: &'static str, when: &'static str) -> String {
    tr!("settings.account.no", count = n).to_string()
}

fn s019_2(n: i64, who: &'static str, when: &'static str) -> String {
    tr!("auth.banner.voice-top-invitation-owner", email = who, title = who).to_string()
}

fn s019_3(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("rooms.empty.download").to_string(),
        1 => tr!("admin.input.count").to_string(),
        _ => tr!("profile.table.button").to_string(),
    }
}

fn s019_4(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("profile.audio.by").to_string(),
        1 => tr!("onboarding.unread-header-delete").to_string(),
        _ => tr!("profile.command-sent-id-offline-banner-up").to_string(),
    }
}

fn s019_6(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("hotkeys.confirm.voice-top").to_string(),
        1 => tr!("onboarding.confirm.page").to_string(),
        _ => tr!("commands.dialog.up").to_string(),
    }
}

fn s019_7(n: i64, who: &'static str, when: &'static str) -> String {
    tr!("settings.filters.slow-usage").to_string()
}

fn s019_8(n: i64, who: &'static str, when: &'static str) -> String {
    tr!("admin.modal.tab").to_string()
}

#[component]
pub fn C019() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{move || s019_0(count.get(), who, when)}</p>
                <p>{s019_1(n, who, when)}</p>
                <p>{tr!("auth.upload.view-thread", command = who)}</p>
                <p>{s019_2(n, who, when)}</p>
                <ul class="table" title={crate::tables::T019[0].label.to_string()}>
                    {crate::tables::T019.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <p>{tr!("auth.notice-screen")}</p>
                <p>{move || s019_3(count.get(), who, when)}</p>
                <p>{move || if flag.get() { tr!("chat.members.background-plan") } else { tr!("chat.confirm.password-back-of") }}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{move || s019_4(count.get(), who, when)}</p>
                <TextLabel text={tr!("search.account.audio-volume-block-level")}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr!("commands.table.user-missing-usage-up").to_string(), 1 => tr!("chat.banner.quality-email-volume-joined").to_string(), _ => tr!("moderation.drafts.plan").to_string(), });
                }>{tr!("profile.audio.pin")}</button>
                <p>{move || s019_6(count.get(), who, when)}</p>
                <p>{tr!("help.audio.avatar-subscription")}</p>
                <p>{tr!("moderation.drafts.ban-preferences")}</p>
                <TextLabel text={tr!("onboarding.confirm.ok")}/>
                <p>{s019_7(n, who, when)}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <SignalHint text={tr!("app.security.kick-reset")}/>
                <p>{s019_8(n, who, when)}</p>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 19">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
