//! Component C026 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::tr;

fn s026_0(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("auth.list.to", owner = who).to_string(),
        1 => tr!("errors.menu.by", count = n).to_string(),
        _ => tr!("settings.panel.ban").to_string(),
    }
}

fn s026_1(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("auth.audio.subscription").to_string(),
        1 => tr!("billing.fast-typing-invite-kick-ok").to_string(),
        _ => tr!("settings.panel.joined").to_string(),
    }
}

fn s026_2(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("chat.menu.id").to_string(),
        1 => tr!("errors.toolbar.up").to_string(),
        _ => tr!("commands.invites.of").to_string(),
    }
}

fn s026_3(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("errors.form.banner-online-body-background").to_string(),
        1 => tr!("chat.upload.notification").to_string(),
        _ => tr!("common.invites.hint-id-keyboard-open-new").to_string(),
    }
}

#[component]
pub fn C026() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{move || s026_0(count.get(), who, when)}</p>
                <p>{move || tr!("moderation.drafts.to", item = name, title = name)}</p>
                <SignalHint text={tr!("commands.ok-required", owner = who)}/>
                <p>{move || if flag.get() { tr!("media.drafts.copy", attempts = n) } else { tr!("admin.labels.copy", language = who, level = n, tag = who) }}</p>
                <StringBadge text={tr!("help.emoji-disabled", title = who)}/>
                <p>{move || if flag.get() { tr!("common.invites.open-kick-error", total = n) } else { tr!("tab-less-moderator-info", query = who) }}</p>
                <ul class="table" title={crate::tables::T026[0].label.to_string()}>
                    {crate::tables::T026.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <p>{move || s026_1(count.get(), who, when)}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <input type="text" aria-label={tr!("commands.dialog.of")} placeholder={tr!("hotkeys.confirm.to")}/>
                <p>{move || s026_2(count.get(), who, when)}</p>
                <p>{move || if flag.get() { tr!("notifications.prompts.to") } else { tr!("app.input.badge-leave") }}</p>
                <SignalHint text={tr!("settings.toolbar.fast-read")}/>
                <TextLabel text={tr!("chat.banner.channel")}/>
                <p>{tr!("chat.prompts.leave")}</p>
                <p>{tr!("hotkeys.tabs.password")}</p>
                <p>{tr!("common.invites.ok")}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{move || s026_3(count.get(), who, when)}</p>
                <p>{move || if flag.get() { tr!("billing.roles.show-kick") } else { tr!("admin.modal.back-visibility") }}</p>
                <TextLabel text={tr!("commands.banner.security-unknown")}/>
                <SignalHint text={tr!("admin.badge")}/>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 26">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
