//! Component C028 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::tr;

fn s028_1(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("commands.table.upload", reason = who).to_string(),
        1 => tr!("errors.history.menu-total-tag").to_string(),
        _ => tr!("settings.labels.ok-2").to_string(),
    }
}

fn s028_2(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("errors.upload.missing-enable").to_string(),
        1 => tr!("app.security.of").to_string(),
        _ => tr!("settings.panel.add").to_string(),
    }
}

fn s028_3(n: i64, who: &'static str, when: &'static str) -> String {
    tr!("settings.toolbar.to").to_string()
}

#[component]
pub fn C028() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{move || tr!("moderation.confirm.character", role = name.get())}</p>
                <ul class="table" title={crate::tables::T028[0].label.to_string()}>
                    {crate::tables::T028.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr!("app.typing-confirmation", members = n, title = who, total = n).to_string(), _ => tr!("commands.dialog.to", reason = who).to_string(), });
                }>{tr!("admin.copy-count")}</button>
                <StringBadge text={tr!("rooms.dialog.token-cancel", sender = who)}/>
                <p>{move || s028_1(count.get(), who, when)}</p>
                <p>{move || s028_2(count.get(), who, when)}</p>
                <p>{move || if flag.get() { tr!("media.drafts.sort-away") } else { tr!("onboarding.confirm.no") }}</p>
                <input type="text" aria-label={tr!("auth.audio.footer-id")} placeholder={tr!("settings.audio.done-file")}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <StringBadge text={tr!("chat.confirm.emoji-status-apply")}/>
                <TextLabel text={tr!("search.list.menu")}/>
                <p>{tr!("connection-result-view-to")}</p>
                <p>{move || if flag.get() { tr!("common.toolbar.menu-prompt-id") } else { tr!("commands.dialog.by") }}</p>
                <p>{s028_3(n, who, when)}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr!("chat.voice-save-hide-owner").to_string(), 1 => tr!("profile.input.token").to_string(), _ => tr!("profile.input.retry").to_string(), });
                }>{tr!("settings.account.of-2")}</button>
                <p>{tr!("settings.confirm.ok")}</p>
                <input type="text" aria-label={tr!("media.all-retry")}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <TextLabel text={tr!("settings.dialog.id-profile")}/>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 28">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
