//! Component C030 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::tr;

fn s030_0(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("chat.labels.tag", minutes = n).to_string(),
        1 => tr!("media.drafts.body-of", command = who).to_string(),
        _ => tr!("settings.audio.of", sender = who).to_string(),
    }
}

fn s030_1(n: i64, who: &'static str, when: &'static str) -> String {
    tr!("notifications.form.to-4", device = who, size = n).to_string()
}

fn s030_2(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("app.form.online-empty").to_string(),
        1 => tr!("rooms.size-ok-thread").to_string(),
        _ => tr!("app.input.speaker").to_string(),
    }
}

#[component]
pub fn C030() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{move || s030_0(count.get(), who, when)}</p>
                <input type="text" aria-label={tr!("billing.roles.invite-view-id", reason = who)} placeholder={tr!("errors.up")}/>
                <p>{tr!("chat.banner.unknown-thread-avatar", size = n)}</p>
                <p>{s030_1(n, who, when)}</p>
                <p>{move || tr!("media.input.dialog", device = name)}</p>
                <p>{tr!("chat.table.open-members")}</p>
                <p>{tr!("profile.copy-header-copy-busy")}</p>
                <p>{tr!("chat.prompts.screen-send-ok")}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <input type="text" aria-label={tr!("chat.badges.apply-row-invalid")} placeholder={tr!("chat.members.download-notification")}/>
                <ul class="table" title={crate::tables::T030[0].label.to_string()}>
                    {crate::tables::T030.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <p>{tr!("onboarding.confirm.off-bot")}</p>
                <p>{move || s030_2(count.get(), who, when)}</p>
                <p>{tr!("search.account.of")}</p>
                <StringBadge text={tr!("rooms.limits.usage-character")}/>
                <p>{tr!("chat.row-prompt")}</p>
                <p>{tr!("commands.video.mode-time")}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <TextLabel text={tr!("common.toolbar.emoji-on")}/>
                <p>{tr!("app.toolbar.on")}</p>
                <p>{tr!("media.drafts.confirmation")}</p>
                <p>{tr!("notifications.theme")}</p>
                <p>{tr!("auth.notice-screen")}</p>
                <p>{tr!("errors.list.members-device")}</p>
                <TextLabel text={tr!("notifications.form.by-3")}/>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 30">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
