//! Component C031 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::tr;

fn s031_0(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("common.toolbar.page-screen", members = n).to_string(),
        1 => tr!("errors.labels.hide-command-of", channel = who, page = n).to_string(),
        _ => tr!("app.input.required", command = who).to_string(),
    }
}

fn s031_1(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("help.audio.date-room", command = who, item = who).to_string(),
        1 => tr!("chat.banner.report-id").to_string(),
        _ => tr!("commands.notice-unavailable").to_string(),
    }
}

fn s031_2(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("auth.sidebar.input-title-new").to_string(),
        1 => tr!("moderation.header.mute").to_string(),
        _ => tr!("rooms.modal.to").to_string(),
    }
}

#[component]
pub fn C031() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{move || s031_0(count.get(), who, when)}</p>
                <TextLabel text={move || tr!("chat.modal.email-react-by", size = count.get()).to_string()}/>
                <input type="text" aria-label={move || tr!("chat.menu.download-all-show", user = name)} placeholder={tr!("billing.invites.footer-language")}/>
                <p>{move || s031_1(count.get(), who, when)}</p>
                <p>{move || tr!("commands.prompts.show", amount = count.get())}</p>
                <p>{tr!("auth.list.participant")}</p>
                <p>{move || if flag.get() { tr!("chat.members.read-ok") } else { tr!("rooms.moderation-kick-empty-cancel") }}</p>
                <StringBadge text={tr!("rooms.language-done-total")}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <TextLabel text={tr!("chat.upload.header")}/>
                <input type="text" aria-label={tr!("app.owner-joined-apply")} placeholder={tr!("attachment")}/>
                <p>{move || s031_2(count.get(), who, when)}</p>
                <p>{tr!("settings.drafts.up")}</p>
                <TextLabel text={tr!("profile.table.id")}/>
                <p>{tr!("commands.status.member-share")}</p>
                <TextLabel text={tr!("app.invite-share-body-item")}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr!("chat.members.online-invite").to_string(), 1 => tr!("moderation.members.bot").to_string(), _ => tr!("rooms.tooltip-unread").to_string(), });
                }>{tr!("moderation.form.url")}</button>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <input type="text" aria-label={tr!("errors.history.microphone")}/>
                <ul class="table" title={crate::tables::T031[0].label.to_string()}>
                    {crate::tables::T031.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <p>{tr!("hotkeys.sound-body")}</p>
                <SignalHint text={tr!("away-error-keyboard")}/>
                <p>{tr!("rooms.empty.visibility")}</p>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 31">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
