//! Component C034 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::tr;

fn s034_0(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("errors.banner.tab-reply-avatar", index = n).to_string(),
        1 => tr!("common.roles.on", room = who).to_string(),
        _ => tr!("admin.badges.upload", members = n).to_string(),
    }
}

fn s034_1(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("profile.input.busy", votes = n).to_string(),
        1 => tr!("media.prompts.pin-menu", hours = n, pages = n).to_string(),
        _ => tr!("errors.up-save-password-no").to_string(),
    }
}

fn s034_2(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("onboarding.pin").to_string(),
        1 => tr!("errors.result-more-add").to_string(),
        _ => tr!("moderation.confirm.attachment-moderation").to_string(),
    }
}

fn s034_3(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("common.upload.owner").to_string(),
        1 => tr!("common.invites.mute-reply").to_string(),
        _ => tr!("chat.badges.role-id").to_string(),
    }
}

fn s034_4(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("errors.upload.notice-disabled-member").to_string(),
        1 => tr!("onboarding.form.limit-position").to_string(),
        _ => tr!("commands.invites.text-mode-badge-list-hide").to_string(),
    }
}

fn s034_5(n: i64, who: &'static str, when: &'static str) -> String {
    tr!("chat.labels.icon-more").to_string()
}

#[component]
pub fn C034() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{move || s034_0(count.get(), who, when)}</p>
                <input type="text" aria-label={move || tr!("profile.input.device-ok-count-label", item = name)} placeholder={tr!("search.account.up")}/>
                <p>{move || s034_1(count.get(), who, when)}</p>
                <p>{tr!("notifications.recording", tag = who)}</p>
                <StringBadge text={tr!("commands.table.attachment")}/>
                <ul class="table" title={crate::tables::T034[0].label.to_string()}>
                    {crate::tables::T034.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <p>{move || s034_2(count.get(), who, when)}</p>
                <StringBadge text={tr!("chat.members.to")}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <input type="text" aria-label={tr!("common.dialog.id-error")} placeholder={tr!("hotkeys.bot-preferences")}/>
                <TextLabel text={tr!("moderation.members.by")}/>
                <TextLabel text={tr!("app.toolbar.of")}/>
                <p>{tr!("errors.security.top-all")}</p>
                <p>{move || s034_3(count.get(), who, when)}</p>
                <p>{tr!("commands.table.permissions")}</p>
                <p>{move || s034_4(count.get(), who, when)}</p>
                <input type="text" aria-label={tr!("onboarding.confirm.user-done-guest-text")}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <StringBadge text={tr!("rooms.sidebar.confirm-sound-plan")}/>
                <p>{s034_5(n, who, when)}</p>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 34">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
