//! Component C035 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::tr;

fn s035_2(n: i64, who: &'static str, when: &'static str) -> String {
    tr!("media.drafts.id").to_string()
}

fn s035_3(n: i64, who: &'static str, when: &'static str) -> String {
    tr!("media.drafts.banner-search").to_string()
}

fn s035_5(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("settings.dialog.done-no").to_string(),
        1 => tr!("auth.audio.of").to_string(),
        _ => tr!("activity-search-token-busy-id-banner").to_string(),
    }
}

fn s035_6(n: i64, who: &'static str, when: &'static str) -> String {
    tr!("commands.account.share-apply").to_string()
}

#[component]
pub fn C035() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{move || tr!("commands.prompts.back-to", page = count.get())}</p>
                <p>{move || tr!("commands.invites.ok", command = name.get())}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr!("notifications.footer.by-2", channel = who, plan = who).to_string(), 1 => tr!("errors.preferences", days = n).to_string(), _ => tr!("media.labels.count-no").to_string(), });
                }>{tr!("settings.dialog.member-notice")}</button>
                <p>{move || tr!("media.labels.hint-header", title = name)}</p>
                <ul class="table" title={crate::tables::T035[0].label.to_string()}>
                    {crate::tables::T035.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <p>{tr!("chat.confirm.link-action-required-level", item = who)}</p>
                <p>{move || if flag.get() { tr!("profile.input.no") } else { tr!("media.drafts.thread-confirmation") }}</p>
                <p>{tr!("chat.slow")}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <input type="text" aria-label={tr!("chat.labels.add-info-no-ok-delete-report")} placeholder={tr!("search.account.status")}/>
                <p>{tr!("auth.prompts.fast-ok")}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr!("commands.dialog.language").to_string(), _ => tr!("pin-attachment-usage-admin-hide").to_string(), });
                }>{tr!("rooms.limits.join")}</button>
                <p>{s035_2(n, who, when)}</p>
                <p>{s035_3(n, who, when)}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr!("notifications.form.no-2").to_string());
                }>{tr!("media.drafts.delete-input-url")}</button>
                <SignalHint text={tr!("rooms.modal.limit-info-send")}/>
                <p>{move || s035_5(count.get(), who, when)}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <input type="text" aria-label={tr!("moderation.form.up")}/>
                <p>{s035_6(n, who, when)}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr!("settings.toolbar.on").to_string());
                }>{tr!("moderation.drafts.empty-bot-success")}</button>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 35">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
