//! Component C036 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::tr;

fn s036_0(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("settings.pin-label-download-shortcut", owner = who, votes = n).to_string(),
        1 => tr!("errors.labels.of", limit = n).to_string(),
        _ => tr!("settings.labels.expired-shortcut").to_string(),
    }
}

fn s036_1(n: i64, who: &'static str, when: &'static str) -> String {
    tr!("rooms.dialog.preferences").to_string()
}

fn s036_2(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("chat.menu.video-user-hint").to_string(),
        1 => tr!("moderation.form.filter").to_string(),
        _ => tr!("app.by-keyboard").to_string(),
    }
}

fn s036_3(n: i64, who: &'static str, when: &'static str) -> String {
    tr!("profile.table.of-settings").to_string()
}

fn s036_4(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("auth.sidebar.thread").to_string(),
        1 => tr!("settings.confirm.to").to_string(),
        _ => tr!("rooms.empty.shortcut-add").to_string(),
    }
}

fn s036_5(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("commands.banner.less").to_string(),
        1 => tr!("media.prompts.enable-leave-cancel-warning").to_string(),
        _ => tr!("admin.tips.result").to_string(),
    }
}

#[component]
pub fn C036() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <ul class="table" title={crate::tables::T036[0].label.to_string()}>
                    {crate::tables::T036.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <p>{move || s036_0(count.get(), who, when)}</p>
                <StringBadge text={tr!("settings.labels.on", position = n)}/>
                <p>{move || tr!("errors.form.url-url", version = name.get())}</p>
                <p>{move || tr!("settings.drafts.to", members = count)}</p>
                <input type="text" aria-label={tr!("search.account.on")} placeholder={tr!("admin.tips.error-reply-status-all")}/>
                <TextLabel text={tr!("commands.video.no")}/>
                <p>{s036_1(n, who, when)}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{move || s036_2(count.get(), who, when)}</p>
                <p>{tr!("admin.labels.id")}</p>
                <p>{tr!("chat.prompts.id")}</p>
                <p>{tr!("errors.form.activity-react")}</p>
                <p>{s036_3(n, who, when)}</p>
                <TextLabel text={tr!("app.empty.leave-report")}/>
                <p>{move || s036_4(count.get(), who, when)}</p>
                <p>{move || s036_5(count.get(), who, when)}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr!("rooms.badges.no")}</p>
                <input type="text" aria-label={tr!("onboarding.fast-bot")}/>
                <TextLabel text={tr!("errors.row-voice-required")}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr!("settings.toolbar.hint").to_string());
                }>{tr!("billing.invites.body")}</button>
                <StringBadge text={tr!("search.list.available-volume")}/>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 36">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
