//! Component C038 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::tr;

fn s038_0(n: i64, who: &'static str, when: &'static str) -> String {
    tr!("errors.list.report-top", version = who).to_string()
}

fn s038_5(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("onboarding.confirm.by").to_string(),
        1 => tr!("errors.history.error").to_string(),
        _ => tr!("chat.members.id-open").to_string(),
    }
}

fn s038_6(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("rooms.modal.header").to_string(),
        1 => tr!("icon-moderator-react").to_string(),
        _ => tr!("notifications.form.id-3").to_string(),
    }
}

#[component]
pub fn C038() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{s038_0(n, who, when)}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr!("chat.banner.joined-typing", email = who).to_string());
                }>{tr!("app.security.volume-screen")}</button>
                <input type="text" aria-label={move || tr!("profile.security.on", channel = name.get(), size = count.get())} placeholder={tr!("settings.toolbar.id")}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr!("admin.empty-report-search", email = who).to_string(), 1 => tr!("moderator-language-less-by", host = who, tag = who, title = who).to_string(), _ => tr!("common.invites.less", attempts = n).to_string(), });
                }>{tr!("errors.menu.id")}</button>
                <p>{tr!("moderation.header.member-copy-item-badge", votes = n)}</p>
                <SignalHint text={tr!("app.empty.warning-connection-count-ok")}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr!("commands.dialog.ok").to_string(), _ => tr!("chat.upload.upload-subscription").to_string(), });
                }>"Apply"</button>
                <ul class="table" title={crate::tables::T038[0].label.to_string()}>
                    {crate::tables::T038.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr!("common.toolbar.download").to_string(), _ => tr!("media.input.delete-invite").to_string(), });
                }>"Apply"</button>
                <p>{tr!("rooms.badges.ok")}</p>
                <input type="text" aria-label={tr!("moderation.form.unread-more-no")} placeholder={tr!("media.tabs.reply-to")}/>
                <TextLabel text={tr!("profile.audio.save-no")}/>
                <p>{move || s038_5(count.get(), who, when)}</p>
                <StringBadge text={tr!("chat.banner.prompt")}/>
                <input type="text" aria-label={tr!("errors.form.theme-no")}/>
                <p>{move || if flag.get() { tr!("rooms.sidebar.shortcut-reset") } else { tr!("settings.drafts.footer-tab") }}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{move || s038_6(count.get(), who, when)}</p>
                <StringBadge text={tr!("settings.panel.joined")}/>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 38">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
