//! Component C040 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::tr;

fn s040_1(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("commands.video.to-plan-camera-ok", language = who).to_string(),
        1 => tr!("app.form.input-hint", votes = n).to_string(),
        _ => tr!("profile.security.preferences").to_string(),
    }
}

fn s040_2(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("settings.dialog.ok").to_string(),
        1 => tr!("help.block-on").to_string(),
        _ => tr!("moderation.form.screen-dialog").to_string(),
    }
}

fn s040_5(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("admin.badges.up-missing-header-camera").to_string(),
        1 => tr!("search.account.id").to_string(),
        _ => tr!("billing.fast-typing-invite-kick-ok").to_string(),
    }
}

fn s040_6(n: i64, who: &'static str, when: &'static str) -> String {
    tr!("app.security.of").to_string()
}

#[component]
pub fn C040() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <ul class="table" title={crate::tables::T040[0].label.to_string()}>
                    {crate::tables::T040.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr!("settings.filters.failed", name = who).to_string(), _ => tr!("app.security.result-character", item = who, plan = who).to_string(), });
                }>{tr!("chat.banner.quality")}</button>
                <p>{move || tr!("workspace", email = name, name = name, pages = count)}</p>
                <p>{move || s040_1(count.get(), who, when)}</p>
                <p>{move || tr!("chat.confirm.avatar-header", index = count)}</p>
                <TextLabel text={tr!("billing.roles.apply-text")}/>
                <p>{move || s040_2(count.get(), who, when)}</p>
                <p>{tr!("admin.modal.plan-connection")}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr!("moderation.form.unavailable")}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr!("rooms.leave-banner-expired").to_string());
                }>{tr!("commands.video.joined")}</button>
                <SignalHint text={tr!("commands.microphone-quote")}/>
                <TextLabel text={tr!("chat.table.notice-result-level-off")}/>
                <input type="text" aria-label={tr!("chat.labels.id-unread-badge")}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr!("page-unread-bot").to_string(), 1 => tr!("auth.audio.total-invite-public").to_string(), _ => tr!("app.form.emoji-filter-enable").to_string(), });
                }>{tr!("settings.empty.all")}</button>
                <p>{move || s040_5(count.get(), who, when)}</p>
                <TextLabel text={tr!("help.screen-public-reconnect-back-id")}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{s040_6(n, who, when)}</p>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 40">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
