//! Component C047 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::tr;

fn s047_1(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("errors.upload.button").to_string(),
        1 => tr!("chat.menu.quote").to_string(),
        _ => tr!("app.form.busy-command-available").to_string(),
    }
}

fn s047_2(n: i64, who: &'static str, when: &'static str) -> String {
    tr!("rooms.dialog.channel").to_string()
}

fn s047_3(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("app.roles.show-enable-size-on").to_string(),
        1 => tr!("chat.avatar-read").to_string(),
        _ => tr!("app.user-avatar-joined-chat-room").to_string(),
    }
}

fn s047_4(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("moderation.privacy.permissions").to_string(),
        1 => tr!("notifications.form.to-3").to_string(),
        _ => tr!("rooms.empty.file-new").to_string(),
    }
}

#[component]
pub fn C047() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <TextLabel text={move || tr!("chat.confirm.link-action-required-level", item = name).to_string()}/>
                <ul class="table" title={crate::tables::T047[0].label.to_string()}>
                    {crate::tables::T047.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <TextLabel text={tr!("search.button", hours = n)}/>
                <p>{move || tr!("chat.banner.ok", minutes = count.get(), tag = name.get())}</p>
                <SignalHint text={Signal::derive(move || tr!("app.empty.reply-members-apply-no", amount = count.get(), remaining = count.get(), sender = name.get()).to_string())}/>
                <p>{tr!("app.form.open-reconnect-back-copy-kick", host = who)}</p>
                <p>{move || tr!("search.account.done-new", days = count)}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr!("chat.labels.code-subscription").to_string());
                }>{tr!("chat.upload.back-to")}</button>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <input type="text" aria-label={tr!("rooms.dialog.warning")} placeholder={tr!("app.available-search-typing")}/>
                <p>{move || s047_1(count.get(), who, when)}</p>
                <p>{tr!("chat.menu.show-available")}</p>
                <p>{s047_2(n, who, when)}</p>
                <p>{move || s047_3(count.get(), who, when)}</p>
                <p>{tr!("app.form.room-cancel-unread")}</p>
                <SignalHint text={tr!("settings.labels.show-join-status")}/>
                <TextLabel text={tr!("commands.table.device-id")}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{move || s047_4(count.get(), who, when)}</p>
                <input type="text" aria-label={tr!("help.audio.join-ok")}/>
                <p>{tr!("guest-by-share-error")}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr!("media.labels.count-no").to_string(), _ => tr!("rooms.dialog.preferences").to_string(), });
                }>{tr!("search.account.up")}</button>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 47">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
