//! Component C052 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::tr;

fn s052_0(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("search.account.button-invitation", seconds = n).to_string(),
        1 => tr!("commands.banner.to", reason = who).to_string(),
        _ => tr!("admin.labels.character", reason = who, tag = who).to_string(),
    }
}

fn s052_1(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("chat.upload.admin-workspace").to_string(),
        1 => tr!("rooms.dialog.no-reply").to_string(),
        _ => tr!("profile.table.body").to_string(),
    }
}

fn s052_2(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("settings.dialog.up").to_string(),
        1 => tr!("chat.members.retry-view").to_string(),
        _ => tr!("settings.unavailable").to_string(),
    }
}

fn s052_3(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("send-level-row-label").to_string(),
        1 => tr!("chat.members.label-to").to_string(),
        _ => tr!("app.roles.less-button-no").to_string(),
    }
}

fn s052_4(n: i64, who: &'static str, when: &'static str) -> String {
    tr!("settings.panel.more-sound-file-workspace").to_string()
}

fn s052_5(n: i64, who: &'static str, when: &'static str) -> String {
    tr!("app.prompt-leave-subscription").to_string()
}

fn s052_7(n: i64, who: &'static str, when: &'static str) -> String {
    tr!("profile.security.preferences").to_string()
}

fn s052_8(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(2) {
        0 => tr!("onboarding.confirm.of-2").to_string(),
        _ => tr!("profile.table.confirmation").to_string(),
    }
}

#[component]
pub fn C052() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{move || tr!("app.form.input-hint", votes = count.get())}</p>
                <p>{move || tr!("errors.upload.invitation-limit-room", device = name.get())}</p>
                <p>{move || s052_0(count.get(), who, when)}</p>
                <p>{move || tr!("chat.failed-activity-thread", reason = name)}</p>
                <ul class="table" title={crate::tables::T052[0].label.to_string()}>
                    {crate::tables::T052.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <p>{move || s052_1(count.get(), who, when)}</p>
                <p>{tr!("notifications.prompts.by")}</p>
                <input type="text" aria-label={tr!("search.account.ok")} placeholder={tr!("settings.errors.up")}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{move || s052_2(count.get(), who, when)}</p>
                <p>{move || s052_3(count.get(), who, when)}</p>
                <SignalHint text={tr!("help.audio.report-settings")}/>
                <p>{move || if flag.get() { tr!("search.account.url-filter") } else { tr!("errors.video.all-network-add") }}</p>
                <p>{s052_4(n, who, when)}</p>
                <p>{move || if flag.get() { tr!("media.drafts.download-download") } else { tr!("rooms.modal.new-shortcut-usage") }}</p>
                <p>{s052_5(n, who, when)}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr!("moderation.empty.chat-mode").to_string(), _ => tr!("search.account.retry-download-failed").to_string(), });
                }>{tr!("settings.theme-role-loading")}</button>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <input type="text" aria-label={tr!("app.form.device-moderator")}/>
                <p>{s052_7(n, who, when)}</p>
                <p>{move || s052_8(count.get(), who, when)}</p>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 52">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
