//! Component C053 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::tr;

fn s053_0(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("help.off-session", max_size = n, pages = n).to_string(),
        1 => tr!("moderation.privacy.prompt", attempts = n).to_string(),
        _ => tr!("profile.audio.row-pin-moderation").to_string(),
    }
}

fn s053_1(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("settings.dialog.required").to_string(),
        1 => tr!("chat.menu.keyboard-tag").to_string(),
        _ => tr!("settings.audio.public-upload").to_string(),
    }
}

fn s053_2(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("auth.upload.public").to_string(),
        1 => tr!("hotkeys.close").to_string(),
        _ => tr!("notifications.footer.of-4").to_string(),
    }
}

fn s053_3(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("auth.banner.tooltip-settings-connection").to_string(),
        1 => tr!("app.toolbar.participant").to_string(),
        _ => tr!("onboarding.confirm.search").to_string(),
    }
}

fn s053_5(n: i64, who: &'static str, when: &'static str) -> String {
    tr!("admin.tips.footer-mode-send").to_string()
}

#[component]
pub fn C053() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{tr!("settings.filters.no", seconds = n)}</p>
                <input type="text" aria-label={tr!("auth.actions.of", minutes = n)} placeholder={tr!("moderation.drafts.input-no")}/>
                <TextLabel text={move || tr!("profile.security.file-no", language = name).to_string()}/>
                <p>{move || s053_0(count.get(), who, when)}</p>
                <ul class="table" title={crate::tables::T053[0].label.to_string()}>
                    {crate::tables::T053.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <SignalHint text={tr!("profile.table.mode-quality-send")}/>
                <input type="text" aria-label={tr!("media.prompts.tooltip-activity")} placeholder={tr!("onboarding.confirm.email")}/>
                <p>{move || s053_1(count.get(), who, when)}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{move || s053_2(count.get(), who, when)}</p>
                <p>{move || if flag.get() { tr!("profile.mute-permissions") } else { tr!("profile.input.up") }}</p>
                <StringBadge text={tr!("chat.menu.confirmation")}/>
                <p>{move || s053_3(count.get(), who, when)}</p>
                <p>{tr!("commands.form.banner")}</p>
                <TextLabel text={tr!("notifications.form.to")}/>
                <SignalHint text={tr!("commands.table.volume-workspace")}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr!("profile.table.off").to_string(), _ => tr!("chat.upload.upload-subscription").to_string(), });
                }>{tr!("rooms.empty.button-add")}</button>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{s053_5(n, who, when)}</p>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 53">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
