//! Component C056 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::tr;

fn s056_2(n: i64, who: &'static str, when: &'static str) -> String {
    tr!("profile.security.ok").to_string()
}

fn s056_3(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("rooms.modal.count").to_string(),
        1 => tr!("moderation.members.kick-offline-pin").to_string(),
        _ => tr!("media.tabs.next-text-name").to_string(),
    }
}

fn s056_4(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("moderation.drafts.code-of").to_string(),
        1 => tr!("notifications.prompt-result").to_string(),
        _ => tr!("errors.security.show-up").to_string(),
    }
}

fn s056_5(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("media.labels.to").to_string(),
        1 => tr!("app.profile-item-menu-room").to_string(),
        _ => tr!("app.input.ok").to_string(),
    }
}

#[component]
pub fn C056() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <StringBadge text={tr!("errors.next-avatar-header", room = who)}/>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(2) { 0 => tr!("hotkeys.list.no", item = who).to_string(), _ => tr!("admin.labels.on", version = who).to_string(), });
                }>{tr!("admin.audio-notification")}</button>
                <p>{move || if flag.get() { tr!("chat.banner.apply-dialog-background", file_name = who, remaining = n) } else { tr!("app.input.keyboard-expired", attempts = n) }}</p>
                <ul class="table" title={crate::tables::T056[0].label.to_string()}>
                    {crate::tables::T056.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(tr!("auth.audio.search", index = n).to_string());
                }>{tr!("chat.prompts.quote")}</button>
                <p>{move || tr!("profile.security.by", language = name.get(), room = name.get())}</p>
                <p>{s056_2(n, who, when)}</p>
                <p>{move || s056_3(count.get(), who, when)}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr!("commands.table.less-volume-ok")}</p>
                <p>{tr!("errors.less-off-banner-icon-level")}</p>
                <p>{tr!("billing.tab-tag")}</p>
                <p>{tr!("chat.badges.hint")}</p>
                <SignalHint text={tr!("settings.account.error-ban")}/>
                <p>{tr!("app.empty.screen-session-slow")}</p>
                <p>{move || s056_4(count.get(), who, when)}</p>
                <input type="text" aria-label={tr!("notifications.cancel-bot-away")} placeholder={tr!("common.roles.kick")}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{move || s056_5(count.get(), who, when)}</p>
                <input type="text" aria-label={tr!("notifications.form.up-2")}/>
                <SignalHint text={tr!("profile.audio.off-emoji-delete")}/>
                <TextLabel text={tr!("moderation.header.text-no")}/>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 56">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
