//! Component C058 (generated by workload-gen; do not edit).

use leptos::prelude::*;

use crate::widgets::{SignalHint, StringBadge, TextLabel};
use p09_i18n::tr;

fn s058_0(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("moderation.confirm.of", name = who, title = who).to_string(),
        1 => tr!("settings.dialog.of", pages = n).to_string(),
        _ => tr!("settings.toolbar.of", language = who).to_string(),
    }
}

fn s058_1(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("media.drafts.network", page = n, topic = who).to_string(),
        1 => tr!("errors.history.plan-slow-banner-online-off", command = who, size = n).to_string(),
        _ => tr!("moderation.confirm.ok").to_string(),
    }
}

fn s058_2(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("notifications.less-speaker-visibility").to_string(),
        1 => tr!("errors.toolbar.thread").to_string(),
        _ => tr!("media.labels.retry-recording").to_string(),
    }
}

fn s058_4(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(3) {
        0 => tr!("common.toolbar.language").to_string(),
        1 => tr!("settings.drafts.no").to_string(),
        _ => tr!("profile.retry-upload").to_string(),
    }
}

fn s058_5(n: i64, who: &'static str, when: &'static str) -> String {
    match n.rem_euclid(2) {
        0 => tr!("common.labels.ban-send").to_string(),
        _ => tr!("commands.video.incoming").to_string(),
    }
}

#[component]
pub fn C058() -> impl IntoView {
    let (count, set_count) = signal(1_i64);
    let (name, set_name) = signal(String::from("Ada"));
    let (stamp, set_stamp) = signal(String::from("2026-09-20T12:00:00"));
    let (flag, set_flag) = signal(false);
    let (error, set_error) = signal(String::new());
    let n = count.get_untracked();
    let who = crate::widgets::pick_name(n);
    let when = crate::widgets::pick_time(n);
    let mut blocks: Vec<AnyView> = Vec::new();
    blocks.push(
        view! {
            <div class="block">
                <p>{move || s058_0(count.get(), who, when)}</p>
                <ul class="table" title={crate::tables::T058[0].label.to_string()}>
                    {crate::tables::T058.iter().map(|row| view! { <li>{row.label}</li> }).collect_view()}
                </ul>
                <p>{move || s058_1(count.get(), who, when)}</p>
                <p>{tr!("hotkeys.confirm.url-off", reason = who)}</p>
                <input type="text" aria-label={tr!("app.visibility-notification")} placeholder={tr!("chat.menu.show-available")}/>
                <p>{tr!("chat.members.kick")}</p>
                <p>{move || s058_2(count.get(), who, when)}</p>
                <p>{tr!("commands.video.upload")}</p>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{tr!("admin.download-confirm")}</p>
                <p>{tr!("profile.size-missing-upload-url")}</p>
                <p>{move || if flag.get() { tr!("onboarding.confirm.by-2") } else { tr!("common.upload.to") }}</p>
                <p>{move || if flag.get() { tr!("common.upload.on") } else { tr!("chat.failed-member-joined") }}</p>
                <p>{tr!("settings.account.ok")}</p>
                <button type="button" on:click=move |_| {
                    set_count.update(|c| *c += 1);
                    set_flag.update(|f| *f = !*f);
                    set_error.set(match count.get_untracked().rem_euclid(3) { 0 => tr!("errors.menu.placeholder").to_string(), 1 => tr!("commands.status.date-search-bot").to_string(), _ => tr!("app.header").to_string(), });
                }>{tr!("settings.toolbar.public")}</button>
                <p>{tr!("settings.filters.ban-url")}</p>
                <TextLabel text={tr!("rooms.limits.permissions")}/>
            </div>
        }
        .into_any(),
    );
    blocks.push(
        view! {
            <div class="block">
                <p>{move || s058_4(count.get(), who, when)}</p>
                <p>{move || s058_5(count.get(), who, when)}</p>
                <p>{move || if flag.get() { tr!("profile.audio.background") } else { tr!("rooms.dialog.warning") }}</p>
            </div>
        }
        .into_any(),
    );
    view! {
        <section class="component" aria-label="Component 58">
            {blocks}
            <p class="status" role="status">{move || error.get()}</p>
        </section>
    }
}
